import {randomBytes,scryptSync,timingSafeEqual} from 'node:crypto';
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
export class AccountsStore{
 constructor(admin){this.admin=admin;this.db=admin.db;this.db.exec(`CREATE TABLE IF NOT EXISTS archived_accounts(user_id INTEGER PRIMARY KEY REFERENCES admin_users(id),archived_at INTEGER NOT NULL,archived_by INTEGER NOT NULL REFERENCES admin_users(id)); CREATE TABLE IF NOT EXISTS account_events(id INTEGER PRIMARY KEY,actor INTEGER NOT NULL REFERENCES admin_users(id),user_id INTEGER NOT NULL REFERENCES admin_users(id),action TEXT NOT NULL,created_at INTEGER NOT NULL);`);}
 archived(id){return Boolean(this.db.prepare('SELECT 1 FROM archived_accounts WHERE user_id=?').get(id));}
 event(u,id,action){this.db.prepare('INSERT INTO account_events(actor,user_id,action,created_at) VALUES(?,?,?,?)').run(u.id,id,action,Date.now());}
 list(u){if(u.role!=='admin')fail('Только администратор.',403);return this.db.prepare('SELECT u.id,u.login,u.role,a.archived_at FROM admin_users u LEFT JOIN archived_accounts a ON a.user_id=u.id ORDER BY (a.archived_at IS NOT NULL),u.login').all();}
 password(b,u){const id=b.userId??u.id;if(!Number.isSafeInteger(id))fail('Неверный сотрудник.');if(id!==u.id&&u.role!=='admin')fail('Нельзя менять чужой пароль.',403);const row=this.db.prepare('SELECT * FROM admin_users WHERE id=?').get(id);if(!row||this.archived(id))fail('Учётная запись не найдена.',404);
  if(id===u.id){this.admin.limit('password:'+u.id);const [salt,key]=row.password.split(':');if(typeof b.currentPassword!=='string'||b.currentPassword.length>128||!key||!timingSafeEqual(scryptSync(b.currentPassword,salt,64),Buffer.from(key,'hex')))fail('Текущий пароль неверен.',403);}
  if(typeof b.password!=='string'||b.password.length<4||b.password.length>128)fail('Пароль должен содержать от 4 до 128 символов.');const salt=randomBytes(16).toString('hex'),pw=salt+':'+scryptSync(b.password,salt,64).toString('hex');
  return this.admin.workforce.tx(()=>{this.db.prepare('UPDATE admin_users SET password=? WHERE id=?').run(pw,id);this.db.prepare('DELETE FROM admin_sessions WHERE user_id=?').run(id);this.event(u,id,id===u.id?'own_password_changed':'password_reset');return {ok:true,signInAgain:id===u.id};});
 }
 archive(b,u){if(u.role!=='admin')fail('Только администратор.',403);if(!Number.isSafeInteger(b.userId))fail('Неверный сотрудник.');return this.admin.workforce.tx(()=>{const row=this.db.prepare('SELECT * FROM admin_users WHERE id=?').get(b.userId);if(!row)fail('Учётная запись не найдена.',404);if(this.archived(row.id))return {ok:true};if(row.role==='admin'&&this.db.prepare("SELECT count(*) n FROM admin_users u WHERE role='admin' AND NOT EXISTS(SELECT 1 FROM archived_accounts a WHERE a.user_id=u.id)").get().n<=1)fail('Нельзя удалить последнего администратора.',409);if(row.id===u.id)fail('Нельзя удалить свою учётную запись.',409);if(this.db.prepare('SELECT 1 FROM employee_work_sessions WHERE user_id=? AND ended_at IS NULL').get(row.id))fail('Сотрудник ещё на смене. Сначала завершите его смену.',409);this.db.prepare('INSERT INTO archived_accounts VALUES(?,?,?)').run(row.id,Date.now(),u.id);this.db.prepare('DELETE FROM admin_sessions WHERE user_id=?').run(row.id);this.event(u,row.id,'archived');return {ok:true};});}
}
