import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {AdminStore,moscowDay} from './admin.mjs';
function fixture(){const dir=mkdtempSync(join(tmpdir(),'start-admin-'));const file=join(dir,'db');const store=new AdminStore(file);store.setupToken('token');store.setup({token:'token',adminPassword:'admin-test-only-123',staffPassword:'staff-test-only-456'},'setup');const admin=store.user(store.login({login:'admin',password:'admin-test-only-123'},'admin'));const staff=store.user(store.login({login:'station',password:'staff-test-only-456'},'staff'));return {store,file,admin,staff,close:()=>{store.close();rmSync(dir,{recursive:true});}};}
const now=Date.parse('2026-09-21T09:00:00Z');
const rental=(extra={})=>({requestId:randomUUID(),equipment:'sup',quantity:1,name:'Тест',phone:'+70000000000',departed:'2026-09-21T12:00',amount:'1000',method:'cash',...extra});
test('Setup is one-time; roles and password verification enforced',()=>{const f=fixture();try{assert.equal(f.admin.role,'admin');assert.equal(f.staff.role,'staff');assert.throws(()=>f.store.setupToken('again'));assert.throws(()=>f.store.login({login:'admin',password:'wrong'},'wrong'),/Неверный/);assert.throws(()=>f.store.resetStaff({password:'new-staff-test-123'},f.staff),/Только администратор/);}finally{f.close();}});
test('Issue is idempotent, counts actual money once, and return is idempotent',()=>{const f=fixture();try{const b=rental({quantity:3,amount:'2500,50'});const id=f.store.create(b,f.staff,now);assert.equal(f.store.create(b,f.staff,now),id);let d=f.store.dashboard('2026-09-21',f.admin);assert.equal(d.active.length,1);assert.equal(d.fleet.find(x=>x.id==='sup').available,42);assert.equal(d.totals[0].amount,250050);f.store.returned(id,f.staff,now+3600000);f.store.returned(id,f.staff,now+4000000);d=f.store.dashboard('2026-09-21',f.admin);assert.equal(d.active.length,0);assert.equal(d.returned.length,1);assert.equal(d.returned[0].returned,now+3600000);assert.equal(d.totals[0].amount,250050);}finally{f.close();}});
test('Fleet cannot be over-issued across separate connections',()=>{const f=fixture();const other=new AdminStore(f.file);try{f.store.create(rental({equipment:'boat'}),f.staff,now);assert.throws(()=>other.create(rental({equipment:'boat'}),f.staff,now),/Недостаточно/);assert.equal(f.store.dashboard('2026-09-21',f.admin).active.length,1);}finally{other.close();f.close();}});
test('Daily collection follows payment day Moscow, independently of return day',()=>{const f=fixture();try{assert.equal(moscowDay(Date.parse('2026-09-21T21:00:00Z')),'2026-09-22');const id=f.store.create(rental(),f.staff,now);f.store.returned(id,f.staff,now+86400000);assert.equal(f.store.dashboard('2026-09-21',f.admin).totals[0].amount,100000);const d=f.store.dashboard('2026-09-22',f.admin);assert.equal(d.totals.length,0);assert.equal(d.returned.length,1);}finally{f.close();}});
test('Invalid amounts, dates and unavailable equipment rejected; zero payment supported',()=>{const f=fixture();try{for(const extra of [{amount:'-1'},{amount:'1.001'},{equipment:'foil'},{quantity:46},{departed:'2026-09-31T12:00'},{departed:'2027-09-21T12:00'}])assert.throws(()=>f.store.create(rental(extra),f.staff,now));f.store.create(rental({amount:'0'}),f.staff,now);assert.equal(f.store.dashboard('2026-09-21',f.admin).totals[0].amount,0);}finally{f.close();}});
test('Password reset revokes employee sessions but preserves admin',()=>{const f=fixture();try{const token=f.store.login({login:'station',password:'staff-test-only-456'},'staff2');f.store.resetStaff({password:'new-staff-test-123'},f.admin);assert.equal(f.store.user(token),null);assert.throws(()=>f.store.login({login:'station',password:'staff-test-only-456'},'staff3'));assert.ok(f.store.login({login:'station',password:'new-staff-test-123'},'staff4'));}finally{f.close();}});

test('Corrections require admin, preserve history and original payment day, reject stale retries',()=>{const f=fixture();try{const b=rental();const id=f.store.create(b,f.staff,now);const edit={...b,id,revision:0,amount:'1500.50',method:'card',reason:'Ошибка кассира',quantity:2};assert.throws(()=>f.store.edit(edit,f.staff,now),/Только администратор/);assert.throws(()=>f.store.history(id,f.staff),/Только администратор/);f.store.edit(edit,f.admin,now+86400000);assert.throws(()=>f.store.edit(edit,f.admin,now+86400000),/уже изменена/);const d=f.store.dashboard('2026-09-21',f.admin);assert.equal(d.totals[0].method,'card');assert.equal(d.totals[0].amount,150050);assert.equal(d.fleet[0].available,43);assert.equal(f.store.dashboard('2026-09-22',f.admin).totals.length,0);const h=f.store.history(id,f.admin);assert.equal(h.length,1);assert.equal(h[0].actor,'admin');assert.equal(JSON.parse(h[0].before_json).amount,100000);assert.equal(JSON.parse(h[0].after_json).amount,150050);}finally{f.close();}});
test('Correction enforces stock, return ordering and conflicts with concurrent returns',()=>{const f=fixture();try{const b=rental();const id=f.store.create(b,f.staff,now);f.store.create(rental({equipment:'boat'}),f.staff,now);const edit={...b,id,revision:0,equipment:'boat',reason:'Ошибка'};assert.throws(()=>f.store.edit(edit,f.admin,now),/Недостаточно/);assert.equal(f.store.history(id,f.admin).length,0);f.store.returned(id,f.staff,now+3600000);assert.throws(()=>f.store.edit({...edit,equipment:'sup'},f.admin,now+7200000),/уже изменена/);assert.throws(()=>f.store.edit({...edit,revision:1,departed:'2026-09-21T14:00'},f.admin,now+7200000),/позже возврата/);f.store.edit({...edit,revision:1},f.admin,now+7200000);const d=f.store.dashboard('2026-09-21',f.admin);assert.equal(d.returned[0].equipment,'boat');assert.equal(d.fleet.find(x=>x.id==='boat').available,0);}finally{f.close();}});

const inquiryBody=(extra={})=>({equipment:'sup',plan:'hour',quantity:2,duration:1,date:'2026-09-21',time:'13:00',name:'Заявка тест',phone:'+70000000000',...extra});
test('Inbox persists, deduplicates, confirms, issues once and links rental atomically',()=>{const f=fixture();const other=new AdminStore(f.file);try{const b=inquiryBody();const id=f.store.receive('receipt',b,now);assert.equal(f.store.receive('receipt',b,now),id);assert.equal(other.inquiries().rows.length,1);f.store.notification(id,'unknown');assert.equal(other.inquiries().rows[0].notification,'unknown');assert.throws(()=>f.store.create(rental({inquiryId:id}),f.staff,now),/подтверждена/);f.store.inquiryStatus({id,revision:0,status:'confirmed'},f.staff,now);assert.throws(()=>other.inquiryStatus({id,revision:0,status:'cancelled'},f.admin,now),/изменена/);const issue=rental({inquiryId:id,quantity:2});const rentalId=f.store.create(issue,f.staff,now);assert.equal(f.store.create(issue,f.staff,now),rentalId);assert.throws(()=>other.create(rental({inquiryId:id}),f.admin,now),/обработана/);assert.equal(f.store.inquiries('issued').rows[0].rental_id,rentalId);assert.equal(f.store.dashboard('2026-09-21',f.admin).active.length,1);assert.equal(f.store.db.prepare('SELECT count(*) n FROM inquiry_events WHERE inquiry_id=?').get(id).n,2);}finally{other.close();f.close();}});
test('Cancelled and season inquiries cannot issue, insufficient stock leaves confirmed inquiry intact',()=>{const f=fixture();try{const id=f.store.receive('cancel',inquiryBody(),now);f.store.inquiryStatus({id,revision:0,status:'cancelled'},f.staff,now);assert.throws(()=>f.store.create(rental({inquiryId:id}),f.staff,now));const season=f.store.receive('season',inquiryBody({plan:'season',quantity:1}),now);f.store.inquiryStatus({id:season,revision:0,status:'confirmed'},f.staff,now);assert.throws(()=>f.store.create(rental({inquiryId:season}),f.staff,now),/абонемента/);const boat=f.store.receive('boat',inquiryBody({equipment:'boat',quantity:1}),now);f.store.inquiryStatus({id:boat,revision:0,status:'confirmed'},f.staff,now);f.store.create(rental({equipment:'boat'}),f.staff,now);assert.throws(()=>f.store.create(rental({inquiryId:boat,equipment:'boat'}),f.staff,now),/Недостаточно/);assert.equal(f.store.inquiries('confirmed').rows.find(x=>x.id===boat).rental_id,null);assert.throws(()=>f.store.receive('bad',inquiryBody({equipment:'foil'}),now));}finally{f.close();}});
