import {readFileSync} from 'node:fs';
import {InventoryStore,quantity} from './inventory.mjs';
const fail=(message,status=409,extra={})=>{throw Object.assign(new Error(message),{status,...extra});};
export class CafeStock{
 constructor(cafe){this.cafe=cafe;this.db=cafe.db;this.inventory=new InventoryStore(cafe.admin);this.db.exec(readFileSync(new URL('./migrations/003-cafe-stock.sql',import.meta.url),'utf8'));}
 recipe(itemId,component){const r=this.db.prepare('SELECT * FROM cafe_recipes WHERE item_id=? AND component=?').get(itemId,component);return r?{...r,ingredients:JSON.parse(r.body)}:null;}
 config(u){if(u?.role!=='admin')fail('Доступно только admin.',403);return {items:this.cafe.catalog().items,groups:this.cafe.catalog().groups,recipes:this.db.prepare('SELECT * FROM cafe_recipes').all().map(r=>({...r,ingredients:JSON.parse(r.body)})),inventory:this.inventory.catalog(u).items};}
 save(b,u){if(u?.role!=='admin')fail('Доступно только admin.',403);const item=this.cafe.catalog().items.find(i=>i.id===b.itemId);if(!item)fail('Блюдо не найдено.',404);const components=['base',...item.variants.map(v=>'variant:'+v.id),...this.cafe.catalog().groups.filter(g=>item.groupIds.includes(g.id)).flatMap(g=>g.options.map(o=>'option:'+o.id))];if(!components.includes(b.component)||!Array.isArray(b.ingredients)||b.ingredients.length>30||(!b.ingredients.length&&!b.component.startsWith('option:')))fail('Укажите расход на одну порцию.',400);
 return this.cafe.transaction(()=>{const old=this.recipe(b.itemId,b.component);if(b.revision!==(old?.revision??-1))fail('Рецептура изменена. Обновите страницу.');const seen=new Set(),ingredients=b.ingredients.map(i=>{const row=this.inventory.row(i.id),amount=quantity(i.amount);if(!row.active||!amount||seen.has(i.id))fail('Проверьте товар и расход.',400);seen.add(i.id);return {id:i.id,unitId:row.unit_id,amount};});this.db.prepare('INSERT INTO cafe_recipes VALUES(?,?,?,0) ON CONFLICT(item_id,component) DO UPDATE SET body=excluded.body,revision=revision+1').run(b.itemId,b.component,JSON.stringify(ingredients));const after=this.recipe(b.itemId,b.component);this.cafe.audit(u,'recipe',{before:old,after});return after;});}
 requirements(line){const components=[line.variant?'variant:'+line.variant.id:'base',...(line.modifiers||[]).map(m=>'option:'+m.optionId)],all=[];for(const key of components){const recipe=this.recipe(line.itemId,key);if(!recipe)fail(`«${line.name}»: расход ещё не настроен. Обратитесь к администратору.`,409,{stockCode:'UNCONFIGURED',itemId:line.itemId,available:0});all.push(...recipe.ingredients);}return all;}
 check(lines){const total=new Map();for(const l of lines){for(const r of this.requirements(l)){const old=total.get(r.id)||{amount:0,unitId:r.unitId,lines:[]};if(old.unitId!==r.unitId)fail('Изменилась единица склада. Проверьте рецептуру.');old.amount+=r.amount*l.quantity;old.lines.push({line:l,perUnit:r.amount});total.set(r.id,old);}}
 for(const [id,r] of total){const stock=this.inventory.row(id);if(!stock.active||stock.current_milli===null||stock.unit_id!==r.unitId)fail(`«${stock.name}»: фактический остаток или единица не заполнены.`,409,{stockCode:'UNCONFIGURED',available:0,itemId:r.lines[0].line.itemId});if(stock.current_milli<r.amount){const l=r.lines[0].line,own=r.lines.filter(x=>x.line===l).reduce((n,x)=>n+x.perUnit,0),others=r.amount-own*l.quantity,available=Math.max(0,Math.floor((stock.current_milli-others)/own));fail(`«${l.name}»: доступно ${available} шт. Уменьшите количество в корзине.`,409,{stockCode:'INSUFFICIENT',available,itemId:l.itemId});}}
 return total;}
 consume(orderId,lines,u,now){const need=this.check(lines);for(const [id,r] of need){const before=this.inventory.row(id);const result=this.db.prepare('UPDATE inventory_items SET current_milli=current_milli-?,updated_at=?,updated_by=?,revision=revision+1 WHERE id=? AND current_milli>=?').run(r.amount,now,u?.id??null,id,r.amount);if(!result.changes)fail('Остаток изменился. Проверьте заказ.');this.db.prepare('INSERT INTO cafe_stock_usage(order_id,item_id,unit_id,amount_milli,created_at) VALUES(?,?,?,?,?)').run(orderId,id,r.unitId,r.amount,now);this.inventory.event(u||{login:'Заказ кафе'},'SALE',before,this.inventory.row(id),'Заказ кафе №'+orderId,null,null,now);}}
 cancel(order,u,now){
 // Food already in preparation stays consumed. The cancellation and usage remain in history.
 const prepared=order.events.some(e=>['COOKING','READY','DELIVERED'].includes(e.kind));if(prepared)return {restored:false,reason:'Заказ уже готовился; расход сохранён.'};
 for(const usage of this.db.prepare('SELECT * FROM cafe_stock_usage WHERE order_id=? AND restored_at IS NULL').all(order.id)){const before=this.inventory.row(usage.item_id);if(before.unit_id!==usage.unit_id||before.current_milli===null)fail('Перед отменой восстановите единицу и фактический остаток «'+before.name+'».');if(before.current_milli+usage.amount_milli>999999999999)fail('Остаток превышает допустимый предел.');this.db.prepare('UPDATE inventory_items SET current_milli=current_milli+?,updated_at=?,updated_by=?,revision=revision+1 WHERE id=?').run(usage.amount_milli,now,u.id,usage.item_id);this.db.prepare('UPDATE cafe_stock_usage SET restored_at=? WHERE id=?').run(now,usage.id);this.inventory.event(u,'RETURN',before,this.inventory.row(usage.item_id),'Отмена заказа кафе №'+order.id,null,null,now);}return {restored:true};}
 availability(item){const variants=item.variants.filter(v=>v.active);const entries=(variants.length?variants:[null]).map(v=>{try{const req=this.requirements({itemId:item.id,name:item.name,variant:v,modifiers:[]}),totals=new Map();for(const r of req){const old=totals.get(r.id);totals.set(r.id,{amount:(old?.amount||0)+r.amount,unitId:r.unitId});}let available=1000000;for(const [id,r] of totals){const s=this.inventory.row(id);if(!s.active||s.current_milli===null||s.unit_id!==r.unitId)return {variantId:v?.id??null,available:0,configured:false};available=Math.min(available,Math.floor(s.current_milli/r.amount));}return {variantId:v?.id??null,available,configured:true};}catch{return {variantId:v?.id??null,available:0,configured:false};}});return {variants:entries,available:Math.max(0,...entries.map(e=>e.available)),configured:entries.some(e=>e.configured)};}
 menu(d){d.stockRevision=this.db.prepare('SELECT coalesce(max(id),0) n FROM inventory_transactions').get().n+':'+this.db.prepare('SELECT coalesce(sum(revision+1),0) n FROM cafe_recipes').get().n;for(const i of d.items)i.stock=this.availability(i);return d;}
}
