import {fillTestCafeStock} from './testing/cafe-stock-fixture.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {AdminStore} from './admin.mjs';
import {SmsStore} from './sms.mjs';
import {CafeStore,cafeHandler} from './cafe.mjs';
import http from 'node:http';
const now=Date.parse('2026-09-22T14:00:00+03:00');
function fixture(){const a=new AdminStore(':memory:');a.db.exec("INSERT INTO admin_users VALUES(1,'admin','admin','unused'),(2,'station','staff','unused'),(3,'waiter','waiter','unused')");const u={id:1,role:'admin'},w={id:3,role:'waiter'},s=new SmsStore(a,null,{}),messages=[];const c=new CafeStore(a,s,{env:{TELEGRAM_BOT_TOKEN:'fake',TELEGRAM_CHAT_ID:'1',SITE_ORIGIN:'https://spotsup.ru'},request:async(url,o)=>{messages.push(JSON.parse(o.body));return {ok:true,json:async()=>({ok:true})};}});fillTestCafeStock(c);const item=c.catalog().items.find(i=>i.name==='Сырники');const body=()=>({requestId:randomUUID(),name:'Тест',phone:'8 (903) 000-00-00',consent:true,fulfillment:'pickup',payment:'cash',items:[{itemId:item.id,quantity:1,optionIds:[]}],expectedTotalCents:item.priceCents});return {a,u,w,s,c,item,body,messages,close:()=>a.close()};}
function check(name,fn){test(name,async()=>{const f=fixture();try{await fn(f);}finally{f.close();}});}
check('Cafe: place is assigned after order, retries are idempotent and stock and total stay unchanged',async f=>{
 const created=f.c.create({...f.body(),fulfillment:'lounge'},f.w,'test',now),before=f.c.stock.inventory.catalog(f.u).items.map(i=>[i.id,i.current_milli]),body={id:created.id,revision:created.revision,requestId:randomUUID(),location:'Стол 12'};
 const order=f.c.location(body,f.w,now+1000);assert.equal(order.details.location,'Стол 12');assert.equal(order.total_cents,created.totalCents);assert.equal(order.status,'NEW');assert.equal(f.c.location(body,f.w,now+2000).revision,1);assert.equal(order.events.filter(e=>e.kind==='LOCATION').length,1);assert.deepEqual(f.c.stock.inventory.catalog(f.u).items.map(i=>[i.id,i.current_milli]),before);assert.throws(()=>f.c.location({...body,requestId:randomUUID()},f.w,now),/изменён/);assert.throws(()=>f.c.location({...body,revision:1,requestId:randomUUID()},null,now));await f.c.tick(now+2000);assert.equal(f.messages.length,2);assert.match(f.messages[1].text,/Стол 12/);assert.match(f.messages[1].text,/не новый заказ/);
 for(const status of ['ACCEPTED','COOKING','READY','DELIVERED']){const r=f.c.order(created.id,f.u);f.c.status({id:r.id,revision:r.revision,status},f.w,now+3000);}const r=f.c.order(created.id,f.u);assert.throws(()=>f.c.location({...body,revision:r.revision,requestId:randomUUID()},f.w,now),/закрыт/);
});
check('Cafe: source catalog, tea prices and tobacco-free service',f=>{const d=f.c.catalog();assert.equal(d.items.find(i=>i.name==='Классический чай').priceCents,50000);assert.equal(d.items.find(i=>i.name==='Травяной и ягодный чай').variants.length,12);const x=d.items.find(i=>i.station==='tea_hookah');assert.match(x.description,/без табака и никотина/);assert.equal(f.c.calculate([{itemId:x.id,quantity:1}],'lounge').totalCents,300000);assert.throws(()=>f.c.calculate([{itemId:x.id,quantity:1}],'yacht'));assert.equal(d.items.filter(i=>i.station==='hookah').length,0);});
check('Cafe: server pricing and option snapshots in integer kopecks',f=>{const b=f.body();b.items[0].optionIds=['syrniki_toppings-0'];b.items[0].quantity=2;b.expectedTotalCents=90000;const r=f.c.create(b,null,'ip',now);assert.equal(r.totalCents,90000);assert.equal(r.details.items[0].modifiers[0].priceCents,5000);assert.equal(f.a.db.prepare('SELECT count(*) n FROM cafe_notifications').get().n,1);});
check('Cafe: idempotent request, unchanged clients, changed request rejected',f=>{const b=f.body(),r=f.c.create(b,null,'ip',now);assert.equal(f.c.create(b,null,'ip',now).id,r.id);assert.equal(f.c.create(b,null,'ip',now).duplicate,true);assert.throws(()=>f.c.create({...b,name:'Другое'},null,'ip',now),/использован/);assert.equal(f.a.db.prepare('SELECT count(*) n FROM clients').get().n,1);assert.equal(f.a.db.prepare('SELECT count(*) n FROM cafe_orders').get().n,1);assert.equal(f.s.clients()[0].marketing_consent,0);});
check('Cafe: totals and snapshots survive catalog edits',f=>{const r=f.c.create(f.body(),null,'ip',now),d=f.c.catalog();d.items.find(x=>x.id===f.item.id).priceCents=12300;f.c.saveCatalog(d,f.u);assert.equal(f.c.order(r.id,f.u).details.items[0].unitCents,40000);assert.throws(()=>f.c.create(f.body(),null,'ip',now),/Цена изменилась/);});
check('Cafe: required choice, unknown and repeated modifiers, safe quantities',f=>{const x=f.c.catalog().items.find(x=>x.name==='Классический чай');assert.throws(()=>f.c.calculate([{itemId:x.id,quantity:1}],'pickup'));assert.equal(f.c.calculate([{itemId:x.id,variantId:x.variants[0].id,quantity:1}],'pickup').totalCents,50000);for(const l of [{quantity:0},{quantity:1.5},{quantity:21},{quantity:1,optionIds:['bad']},{quantity:1,optionIds:['syrniki_toppings-0','syrniki_toppings-0']}])assert.throws(()=>f.c.calculate([{itemId:f.item.id,...l}],'pickup'));});
check('Cafe: stop list and inactive categories/options enforced server-side',f=>{let d=f.c.catalog();d.items.find(x=>x.id===f.item.id).soldOut=true;f.c.saveCatalog(d,f.u);assert.throws(()=>f.c.create(f.body(),null,'ip',now),/недоступна/);d=f.c.catalog();d.items.find(x=>x.id===f.item.id).soldOut=false;d.groups[3].options[0].soldOut=true;f.c.saveCatalog(d,f.u);assert.throws(()=>f.c.calculate([{itemId:f.item.id,quantity:1,optionIds:['syrniki_toppings-0']}],'pickup'),/недоступна/);d=f.c.catalog();d.categories[0].active=false;f.c.saveCatalog(d,f.u);assert.throws(()=>f.c.create(f.body(),null,'ip',now));});
check('Cafe: consent, opening hours, pause, scheduled delivery',f=>{assert.throws(()=>f.c.create({...f.body(),consent:false},null,'ip',now));assert.throws(()=>f.c.create(f.body(),null,'ip',now-12*3600000));assert.throws(()=>f.c.create({...f.body(),requestedAt:'2026-09-22T14:05'},null,'ip',now));assert.equal(f.c.create({...f.body(),requestedAt:'2026-09-22T16:00'},null,'ip',now).details.requestedAt,'2026-09-22T16:00');let d=f.c.catalog();d.settings.enabled=false;f.c.saveCatalog(d,f.u);assert.throws(()=>f.c.create(f.body(),null,'ip',now),/приостановлен/);});
check('Cafe: yacht requires location and name',f=>{assert.throws(()=>f.c.create({...f.body(),fulfillment:'yacht'},null,'ip',now));const r=f.c.create({...f.body(),fulfillment:'yacht',yacht:'ТЕСТ',location:'Причал 1'},null,'ip',now);assert.equal(r.details.yacht,'ТЕСТ');});
check('Cafe: long place tokens, rotation, disabled places, forged place IDs',f=>{let [p]=f.c.savePlace({name:'Стол 7',type:'table',active:true},f.u);assert.equal(p.token.length,48);assert.throws(()=>f.c.create({...f.body(),fulfillment:'place',placeId:p.id},null,'ip',now));const r=f.c.create({...f.body(),fulfillment:'place',placeToken:p.token},null,'ip',now);assert.equal(r.details.place.name,'Стол 7');const old=p.token;[p]=f.c.savePlace({...p,active:true,rotate:true},f.u);assert.throws(()=>f.c.placeForToken(old));f.c.savePlace({...p,active:false},f.u);assert.throws(()=>f.c.placeForToken(p.token));assert.equal(f.c.order(r.id,f.u).details.place.name,'Стол 7');});
check('Cafe: staff orders, role separation and optimistic settings revisions',f=>{const b={...f.body(),phone:'',name:'Гость',consent:false};const r=f.c.create(b,f.w,'ip',now);assert.equal(f.c.order(r.id,f.u).source,'waiter');assert.throws(()=>f.c.saveCatalog(f.c.catalog(),f.w));assert.throws(()=>f.c.savePlace({name:'Стол',type:'table',active:true},f.w));const d=f.c.catalog();f.c.saveCatalog(d,f.u);assert.throws(()=>f.c.saveCatalog(d,f.u),/изменено/);});
check('Cafe: status lifecycle, duplicate status, stale changes and immutable closed orders',f=>{let r=f.c.order(f.c.create(f.body(),null,'ip',now).id,f.u);for(const status of ['ACCEPTED','COOKING','READY','DELIVERED']){const b={id:r.id,revision:r.revision,status};r=f.c.status(b,f.w,now);assert.equal(f.c.status(b,f.w,now).revision,r.revision);}assert.equal(r.revision,4);assert.throws(()=>f.c.status({id:r.id,revision:4,status:'NEW'},f.u));assert.throws(()=>f.c.append({...f.body(),id:r.id,revision:4},f.w,now));});
check('Cafe: add-on idempotency and separate notification payload',async f=>{const r=f.c.create(f.body(),null,'ip',now),b={...f.body(),id:r.id,revision:0};const added=f.c.append(b,f.w,now);assert.equal(added.total_cents,80000);assert.equal(f.c.append(b,f.w,now).total_cents,80000);assert.throws(()=>f.c.append({...f.body(),id:r.id,revision:0},f.w,now),/изменён/);await f.c.tick(now);assert.equal(f.messages.length,2);assert.match(f.messages[1].text,/дозаказ/);assert.match(f.messages[1].text,/400/);});
check('Cafe: Telegram sent after commit, inline link and no repeated send',async f=>{const r=f.c.create(f.body(),null,'ip',now);assert.equal(f.messages.length,0);await Promise.all([f.c.tick(now),f.c.tick(now)]);assert.equal(f.messages.length,1);assert.equal(f.messages[0].reply_markup.inline_keyboard[0][0].url,'https://spotsup.ru/admin/cafe/#order-'+r.id);await f.c.tick(now+60000);assert.equal(f.messages.length,1);});
check('Cafe: uncertain Telegram failure retains order and requires explicit retry',async f=>{const r=f.c.create(f.body(),null,'ip',now);f.c.request=async()=>{throw Error('secret-token network error');};await f.c.tick(now);let n=f.c.order(r.id,f.u).notifications[0];assert.equal(n.status,'unknown');assert.doesNotMatch(n.last_error,/secret/);f.c.retryNotification(n.id,f.u);assert.equal(f.c.order(r.id,f.u).notifications[0].status,'queued');});
check('Cafe: explicit provider rejection retries with backoff',async f=>{const r=f.c.create(f.body(),null,'ip',now);f.c.request=async()=>({ok:false,json:async()=>({ok:false})});await f.c.tick(now);const n=f.c.order(r.id,f.u).notifications[0];assert.equal(n.status,'queued');assert.equal(n.attempts,1);await f.c.tick(now+1000);assert.equal(f.c.order(r.id,f.u).notifications[0].attempts,1);});
check('Cafe: rate limit and random order receipt access',f=>{for(let i=0;i<5;i++)f.c.create(f.body(),null,'ip',now);assert.throws(()=>f.c.create(f.body(),null,'ip',now),/Слишком много/);assert.throws(()=>f.c.publicOrder('1'));const r=f.c.create(f.body(),f.u,'ip',now);assert.equal(f.c.publicOrder(r.token).details.phone,undefined);assert.equal(f.c.publicOrder(r.token).details.name,undefined);});
check('Cafe: menu validation rejects bad prices and duplicate modifier IDs',f=>{const d=f.c.catalog();d.items[0].priceCents=1.1;assert.throws(()=>f.c.saveCatalog(d,f.u));d.items[0].priceCents=40000;d.groups[1].options[0].id=d.groups[0].options[0].id;assert.throws(()=>f.c.saveCatalog(d,f.u),/уникальны/);});
check('Cafe: waiter uses existing password auth and cannot overwrite admin',f=>{f.c.saveStaff({login:'test_waiter',password:'test-only-password'},f.u);const token=f.a.login({login:'test_waiter',password:'test-only-password'},'ip');assert.equal(f.a.user(token).role,'waiter');f.c.saveStaff({login:'test_waiter',password:'test-only-password2'},f.u);assert.equal(f.a.user(token),null);assert.throws(()=>f.c.saveStaff({login:'admin',password:'test-only-password'},f.u));});
check('Cafe HTTP: authentication, CSRF, body limits and no secrets in public menu',async f=>{let origin;const server=http.createServer(async(req,res)=>{await cafeHandler(f.c,f.a,origin)(req,res,new URL(req.url,origin));});await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;try{let r=await fetch(origin+'/api/admin/cafe/orders');assert.equal(r.status,401);r=await fetch(origin+'/api/cafe/orders',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://wrong.test'},body:JSON.stringify(f.body())});assert.equal(r.status,403);r=await fetch(origin+'/api/cafe/menu');assert.equal(r.status,200);assert.doesNotMatch(await r.text(),/fake|TELEGRAM_BOT_TOKEN/);r=await fetch(origin+'/api/cafe/orders',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:' '.repeat(33000)});assert.equal(r.status,413);}finally{await new Promise(r=>server.close(r));}});
