import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {AdminStore} from './admin.mjs';
import {CafeStore} from './cafe.mjs';
import {SmsStore} from './sms.mjs';
import {CafeList,cafeListRow} from './cafe-list.mjs';
import {TableVersion} from './table-version.mjs';
import {InventoryStore} from './inventory.mjs';
const date='2026-10-02',now=Date.parse(date+'T12:00:00+03:00'),u={id:1,role:'admin'};
function fixture(t){const a=new AdminStore(':memory:');t.after(()=>a.close());a.db.exec("INSERT INTO admin_users VALUES(1,'admin','admin','unused')");const c=new CafeStore(a,new SmsStore(a,null,{})),l=new CafeList(c);let n=0;const add=(status='COOKING',details={},time=now)=>Number(a.db.prepare('INSERT INTO cafe_orders(request_id,fingerprint,public_token,source,details,total_cents,status,created,updated) VALUES(?,?,?,?,?,?,?,?,?)').run('r'+(++n),'private-fingerprint','secret-token'+n,'admin',JSON.stringify({name:'Гость',phone:'79000000000',fulfillment:'pickup',items:[{name:'Кофе',quantity:2}],terminalPaidAt:now,consent:true,...details}),35000,status,time,time).lastInsertRowid);const read=p=>l.read(new URLSearchParams({date,...p}));return {a,c,l,add,read};}
test('Closed day sends no active rows but preserves totals; history is explicitly loaded without private internals',t=>{const f=fixture(t);for(let i=0;i<37;i++)f.add(i<29?'DELIVERED':'CANCELLED');const d=f.read({});assert.equal(d.rows.length,0);assert.equal(d.dayCount,37);assert.equal(d.totalCents,29*35000);const all=f.read({status:''});assert.equal(all.rows.length,37);for(const text of ['fingerprint','public_token','secret-token','79000000000','consent','terminalPayment'])assert.ok(!JSON.stringify(all).includes(text),text);assert.deepEqual(f.read({since:d.revision}),{unchanged:true,revision:d.revision});});
test('Active orders include previous days, server filters and pages before returning rows',t=>{const f=fixture(t);f.add('COOKING',{name:'ИВАН'},now-86400000);for(let i=0;i<120;i++)f.add('COOKING');f.add('DELIVERED');f.add('NEW',{guestBillId:9});const d=f.read({});assert.equal(d.total,121);assert.equal(d.rows.length,50);assert.equal(f.read({limit:'100'}).rows.length,100);assert.equal(f.read({q:'иван'}).rows.length,1);assert.equal(f.read({q:'9000'}).total,121);assert.equal(f.read({status:'DELIVERED'}).rows.length,1);assert.equal(f.read({status:'CANCELLED'}).rows.length,0);assert.throws(()=>f.read({date:'2026-02-31'}));});
test('Unchanged polls skip list queries; payment changes invalidate without an order revision; unrelated writes do not',t=>{const f=fixture(t);f.a.db.exec('CREATE TABLE aqsi_cafe(id TEXT,state TEXT)');let lookups=0;f.c.terminal={payments:rows=>{lookups++;return new Map(rows.map(r=>[r.id,{state:f.a.db.prepare('SELECT state FROM aqsi_cafe').get()?.state||'done',paid:true,label:'Статус'}]));},terminalIssues:()=>[]};const id=f.add();const d=f.read({});assert.equal(lookups,1);f.a.db.exec("UPDATE admin_users SET login='owner' WHERE id=1");assert.equal(f.read({since:d.revision}).unchanged,true);assert.equal(lookups,1);f.a.db.exec("INSERT INTO aqsi_cafe VALUES('p','receipt_unknown')");const changed=f.read({since:d.revision});assert.equal(changed.rows[0].tone,'red');assert.notEqual(changed.revision,d.revision);assert.equal(lookups,2);f.a.db.prepare("UPDATE cafe_orders SET status='DELIVERED',revision=revision+1 WHERE id=?").run(id);assert.equal(f.read({since:changed.revision}).rows.length,0);});
test('Row actions preserve payment and fulfilment guards',()=>{const base={id:1,status:'NEW',revision:0,created:now,total_cents:35000,details:{name:'',items:[],fulfillment:'pickup',terminalPaymentRequired:true}};let r=cafeListRow(base,null);assert.equal(r.ready,false);assert.equal(r.action,'pay');r=cafeListRow(base,{state:'payment_unknown',paid:false});assert.equal(r.action,'check');assert.equal(r.tone,'red');r=cafeListRow({...base,details:{...base.details,terminalPaidAt:now}},{state:'done',paid:true});assert.equal(r.ready,true);assert.equal(r.action,'complete');assert.equal(r.tone,'green');assert.equal(cafeListRow({...base,status:'CANCELLED'},null).action,null);});
test('Revision watcher detects writes from another SQLite connection and rolls back counters with failed transactions',()=>{const folder=mkdtempSync(join(tmpdir(),'cafe-revision-')),path=join(folder,'test.sqlite'),a=new DatabaseSync(path),b=new DatabaseSync(path);try{a.exec('CREATE TABLE orders(id INTEGER)');const w=new TableVersion(a,'test',['orders']);const first=w.read();b.exec('INSERT INTO orders VALUES(1)');assert.notEqual(w.read(),first);const second=w.read();a.exec('BEGIN; INSERT INTO orders VALUES(2); ROLLBACK');assert.equal(w.read(),second);a.exec('INSERT INTO orders VALUES(3)');assert.notEqual(w.read(),second);}finally{a.close();b.close();rmSync(folder,{recursive:true,force:true});}});
test('Compact purchase summary matches full purchase rules and returns four short rows',t=>{const a=new AdminStore(':memory:');t.after(()=>a.close());a.db.exec("INSERT INTO admin_users VALUES(1,'admin','admin','unused')");const store=new InventoryStore(a,{seed:false});for(let i=0;i<12;i++)store.save({name:'Товар '+i,category:'Кафе',unit:'шт',current:i%3===0?null:'0',minimum:'1',target:'5',comment:'private-stock-note',manualBuy:i%3===0,requestId:randomUUID()},u);const full=store.summary(u),small=store.summary(u,true);assert.equal(small.count,full.items.length);assert.equal(small.items.length,4);assert.deepEqual(small.items,full.items.slice(0,4).map(({id,name,unit,buyQuantity,urgent})=>({id,name,unit,buyQuantity,urgent})));assert.ok(!JSON.stringify(small).includes('private-stock-note'));assert.throws(()=>store.summary(null,true));});

test('Completed guest bill orders remain visible in history and search without duplicate totals',t=>{const f=fixture(t);const id=f.add('DELIVERED',{guestBillId:9});f.add('CANCELLED',{guestBillId:10});f.add('COOKING',{guestBillId:11});assert.equal(f.read({}).total,0);const history=f.read({status:''});assert.equal(history.total,2);assert.equal(history.dayCount,3);assert.equal(history.totalCents,70000);const row=f.read({status:'DELIVERED',q:String(id)}).rows[0];assert.equal(row.id,id);assert.equal(row.guestBillId,9);assert.match(row.statusLabel,/Счёт гостя №9/);assert.equal(row.action,null);assert.equal(f.read({status:'CANCELLED'}).total,1);});

test('List labels retain valid Russian text after deployment',()=>{const row=cafeListRow({id:149,status:'DELIVERED',revision:0,created:now,total_cents:80000,details:{guestBillId:9,terminalPaidAt:now,fulfillment:'pickup',items:[{name:'Tea',quantity:1}]}},null);assert.equal(row.placeLabel,'В кафе');assert.equal(row.paymentLabel,'Оплачено');assert.equal(row.statusLabel,'Счёт гостя №9 · Выполнен · Оплачен');assert.equal(row.itemsLabel,'1× Tea');});
