import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {AdminStore,fleet} from './admin.mjs';
import {SmsStore} from './sms.mjs';
import {availability,bookingWindow,calendarData,localStamp} from './calendar.mjs';
const now=localStamp('2026-10-01T12:00'),user={id:1,role:'admin'};
function fixture(){const a=new AdminStore(':memory:');a.db.prepare('INSERT INTO admin_users(id,login,role,password) VALUES(1,?,?,?)').run('admin','admin','unused');const sms=new SmsStore(a,null,{SMS_ENABLED:'true',SMSAERO_EMAIL:'fake',SMSAERO_API_KEY:'fake'});sms.save({...sms.settings(),enabled:true},user);return {a,sms,book(extra={},confirm=true){const id=a.receive(randomUUID(),{name:'Тест',phone:'+79030000000',equipment:'boat',plan:'hour',quantity:1,duration:1,date:'2026-10-01',time:'14:00',...extra},now);if(confirm)a.inquiryStatus({id,revision:0,status:'confirmed'},user,now);return id;},check(equipment='boat',start='14:00',end='15:00',at=now){return availability(a.db,fleet,equipment,localStamp('2026-10-01T'+start),localStamp('2026-10-01T'+end),{now:at});},close(){a.close();}};}
const issue=(extra={})=>({requestId:randomUUID(),equipment:'boat',quantity:1,name:'Тест',phone:'+79030000000',departed:'2026-10-01T12:00',expectedReturn:'2026-10-01T13:00',amount:'1000',method:'cash',...extra});
test('Confirmed intervals reserve capacity; new requests do not; adjacent slots allowed',()=>{const f=fixture();try{f.book({},false);assert.equal(f.check().available,1);f.book();assert.equal(f.check().available,0);assert.throws(()=>f.book(),/Недостаточно/);f.book({time:'15:00'});assert.equal(f.check('boat','16:00','17:00').available,1);}finally{f.close();}});
test('Peak simultaneous count, not sum of disjoint reservations; BIG SUP reserves one craft',()=>{const f=fixture();try{f.book({equipment:'sup',quantity:20});f.book({equipment:'sup',quantity:20,time:'15:00'});assert.equal(f.check('sup','14:00','16:00').available,25);f.book({equipment:'big',quantity:6});assert.equal(f.check('big').available,0);assert.throws(()=>f.book({equipment:'big',quantity:2}),/Недостаточно/);}finally{f.close();}});
test('Day and takeaway cover the whole interval; season never reserves a board',()=>{const f=fixture();try{f.book({equipment:'sup',quantity:1,plan:'season'});assert.equal(f.check('sup').available,45);f.book({equipment:'sup',quantity:1,plan:'day'});assert.equal(f.check('sup','20:00','21:00').available,44);f.book({equipment:'sup',quantity:1,plan:'takeaway',returnDate:'2026-10-03'});assert.equal(availability(f.a.db,fleet,'sup',localStamp('2026-10-02T09:00'),localStamp('2026-10-02T10:00'),{now}).available,44);assert.equal(bookingWindow({plan:'day',date:'2026-10-01',time:'14:00',equipment:'sup',quantity:1},'20:30').end,localStamp('2026-10-01T20:30'));}finally{f.close();}});
test('Conflicting move rolls back booking and SMS; successful move releases old slot',()=>{const f=fixture();try{const id=f.book();f.book({time:'16:00'});f.sms.sync(now);const old=f.sms.jobs(id);assert.throws(()=>f.sms.reschedule({id,revision:1,date:'2026-10-01',time:'16:00'},user,now),/Недостаточно/);assert.equal(JSON.parse(f.a.db.prepare('SELECT details FROM inquiries WHERE id=?').get(id).details).time,'14:00');assert.deepEqual(f.sms.jobs(id),old);f.sms.reschedule({id,revision:1,date:'2026-10-01',time:'18:00'},user,now);assert.equal(f.check().available,1);assert.equal(f.check('boat','18:00','19:00').available,0);assert.equal(f.sms.jobs(id).filter(j=>j.status==='cancelled').length,1);}finally{f.close();}});
test('Walk-in cannot overlap future booking; overdue craft blocks future reservations until returned',()=>{const f=fixture();try{f.book();assert.throws(()=>f.a.create(issue({expectedReturn:'2026-10-01T14:30'}),user,now),/Недостаточно/);const id=f.a.create(issue(),user,now);assert.equal(f.check('boat','16:00','17:00').available,1);assert.equal(f.check('boat','16:00','17:00',now+7200000).available,0);f.a.returned(id,user,now+7200000);assert.equal(f.check('boat','16:00','17:00',now+7200000).available,1);}finally{f.close();}});
test('No-show requires elapsed grace, explicitly cancels and cancels queued SMS',()=>{const f=fixture();try{const id=f.book();f.sms.sync(now);const b={id,revision:1,status:'cancelled',reason:'no_show'};assert.throws(()=>f.a.inquiryStatus(b,user,localStamp('2026-10-01T14:10')),/опоздания/);assert.equal(calendarData(f.a,fleet,'2026-10-01',1,localStamp('2026-10-01T14:16')).rows[0].late,true);f.a.inquiryStatus(b,user,localStamp('2026-10-01T14:16'));f.sms.sync(localStamp('2026-10-01T14:16'));assert.equal(f.check().available,1);assert.equal(f.sms.jobs(id)[0].cancel_reason,'cancelled');assert.equal(f.a.db.prepare('SELECT status FROM inquiry_events ORDER BY id DESC').get().status,'no_show');}finally{f.close();}});
test('Complete station day: booking, reminder, issue, return, revenue without duplicate stock or payment',async()=>{const f=fixture();try{const id=f.book({time:'12:30'});let sends=0;await f.sms.tick({send:async()=>({ok:true,data:{id:++sends,status:0}})},now);assert.equal(sends,1);const b=issue({inquiryId:id,departed:'2026-10-01T12:30',expectedReturn:'2026-10-01T13:30'}),at=now+1800000,rental=f.a.create(b,user,at);assert.equal(f.a.create(b,user,at),rental);assert.equal(f.check('boat','12:30','13:30').occupied,1);let cal=calendarData(f.a,fleet,'2026-10-01',1,at);assert.equal(cal.rows[0].state,'issued');f.a.returned(rental,user,at+3600000);f.a.returned(rental,user,at+3600001);assert.equal(f.a.dashboard('2026-10-01',user).totals[0].amount,100000);assert.equal(calendarData(f.a,fleet,'2026-10-01').rows[0].state,'completed');assert.equal(f.check('boat','12:30','13:30').available,1);}finally{f.close();}});

test('Glowing SUP has two separate units and rejects a third overlapping booking',()=>{const f=fixture();try{assert.equal(fleet.find(i=>i[0]==='glow')[2],2);f.book({equipment:'glow',quantity:2});assert.equal(f.check('glow').available,0);assert.throws(()=>f.book({equipment:'glow'}),/Недостаточно/);assert.equal(f.check('sup').available,45);}finally{f.close();}});
