import {createHash} from 'node:crypto';
const fail=(m,status=400)=>{throw Object.assign(Error(m),{status});};
const staff=u=>{if(!['admin','staff','waiter'].includes(u?.role))fail('Войдите в админку.',403);};
export class CashLedger {
 constructor(admin){this.admin=admin;this.db=admin.db;this.db.exec(`CREATE TABLE IF NOT EXISTS cash_ledger(id INTEGER PRIMARY KEY,request_id TEXT UNIQUE NOT NULL,shift_id INTEGER NOT NULL,kind TEXT NOT NULL,cents INTEGER NOT NULL,reason TEXT NOT NULL,body_json TEXT NOT NULL,actor INTEGER NOT NULL,created INTEGER NOT NULL);`);if(!this.db.prepare('PRAGMA table_info(customer_refunds)').all().some(c=>c.name==='method'))this.db.exec("ALTER TABLE customer_refunds ADD COLUMN method TEXT NOT NULL DEFAULT 'unspecified'");}
 get enabled(){return this.admin.env?.CASH_LEDGER_ENABLED==='1'||this.db.prepare("SELECT value FROM admin_config WHERE key='cash_ledger_enabled'").get()?.value==='1';}
 // The caller holds the day-close transaction; a physical count becomes the cash baseline.
 closingCount(shiftId,amountCents,u,now){const s=this.summary(u,now,shiftId);this.db.prepare('INSERT INTO cash_ledger(request_id,shift_id,kind,cents,reason,body_json,actor,created) VALUES(?,?,?,?,?,?,?,?)').run('shift-close:'+shiftId,shiftId,'count',amountCents-s.balanceCents,'Пересчёт при сохранении итога дня',JSON.stringify({kind:'count',amountCents,source:'day-close'}),u.id,now);}
 summary(u,now=Date.now(),shiftId){staff(u);const s=shiftId?this.db.prepare('SELECT * FROM shifts WHERE id=?').get(shiftId):this.db.prepare('SELECT * FROM shifts WHERE day<=? ORDER BY day DESC,id DESC LIMIT 1').get(this.admin.workforce.accountingDay(now));if(!s)return {shift:null,balanceCents:null};const next=this.db.prepare('SELECT min(opened_at) at FROM shifts WHERE opened_at>?').get(s.opened_at).at,until=Math.min(now,next===null?now:next-1);
 const rental=this.db.prepare("SELECT coalesce(sum(amount),0) n FROM payments WHERE created>=? AND created<=? AND method='cash'").get(s.opened_at,until).n;
 const exists=!!this.db.prepare("SELECT name FROM sqlite_master WHERE name='cafe_orders'").get();
 const cafe=exists?this.db.prepare("SELECT coalesce(sum(total_cents),0) n FROM cafe_orders WHERE json_extract(details,'$.cashPaidAt')>=? AND json_extract(details,'$.cashPaidAt')<=?").get(s.opened_at,until).n:0;
 const refunds=this.db.prepare("SELECT coalesce(sum(amount_cents),0) n FROM customer_refunds WHERE created_at>=? AND created_at<=? AND method='cash'").get(s.opened_at,until).n;
 const withdrawals=this.db.prepare("SELECT coalesce(sum(amount_cents),0) n FROM cash_movements WHERE shift_id=? AND created_at<=? AND (voided_at IS NULL OR voided_at>?)").get(s.id,until,until).n;
 const entries=this.db.prepare('SELECT l.*,u.login FROM cash_ledger l JOIN admin_users u ON u.id=l.actor WHERE shift_id=? AND created<=? ORDER BY id DESC').all(s.id,until),deposits=entries.filter(e=>e.kind==='deposit').reduce((n,e)=>n+e.cents,0),corrections=entries.filter(e=>e.kind==='count').reduce((n,e)=>n+e.cents,0);
 const payroll=this.db.prepare("SELECT coalesce(sum(amount_cents),0) n FROM payroll_payments WHERE method='cash' AND paid_at>=? AND paid_at<=?").get(s.opened_at,until).n;
 const balance=s.cash_start_cents+rental+cafe-refunds-withdrawals+deposits+corrections-payroll;
 const knownFrom=Math.max(s.opened_at,...entries.filter(e=>e.kind==='count').map(e=>e.created));const unknown=this.db.prepare("SELECT count(*) n FROM payments WHERE created>=? AND created<=? AND method='unspecified' AND amount>0").get(knownFrom,until).n+(exists?this.db.prepare("SELECT count(*) n FROM cafe_orders WHERE updated>=? AND updated<=? AND status='DELIVERED' AND total_cents>0 AND json_extract(details,'$.terminalPaymentRequired') IS NULL AND json_extract(details,'$.terminalPaidAt') IS NULL").get(knownFrom,until).n:0)+this.db.prepare("SELECT count(*) n FROM customer_refunds WHERE created_at>=? AND created_at<=? AND method=\'unspecified\'").get(knownFrom,until).n;
 const corrected=this.db.prepare("SELECT actor,created_at FROM financial_audit_log WHERE action='opening_balance_correct' AND entity_id=? ORDER BY created_at DESC,id DESC LIMIT 1").get(s.id);
 const actor=corrected?.actor??s.opened_by,at=corrected?.created_at??s.opened_at;
 const person=this.db.prepare("SELECT coalesce(nullif(p.display_name,''),u.login) name FROM admin_users u LEFT JOIN employee_profiles p ON p.user_id=u.id WHERE u.id=?").get(actor);
 const openingCount={name:person?.name??'Сотрудник',at,corrected:!!corrected};
 const data={shift:{id:s.id,day:s.day,closed:!!s.closed_at},openingCents:s.cash_start_cents,openingCount,salesCents:rental+cafe,rentalCents:rental,cafeCents:cafe,payrollCents:payroll,refundsCents:refunds,withdrawalsCents:withdrawals,depositsCents:deposits,correctionsCents:corrections,adjustmentsCents:corrections,balanceCents:balance,unknownPayments:unknown,unknownCount:unknown,entries};return {...data,version:createHash('sha256').update(JSON.stringify(data)).digest('hex')};
 }
 change(b,u,now=Date.now()){staff(u);if(!/^[a-f0-9-]{36}$/.test(b.requestId||'')||!['deposit','count'].includes(b.kind)||!Number.isSafeInteger(b.amountCents)||b.amountCents<0||b.amountCents>100000000||typeof b.reason!=='string'||!b.reason.trim()||b.reason.length>300)fail('Проверьте сумму и укажите причину.');return this.admin.workforce.tx(()=>{const old=this.db.prepare('SELECT * FROM cash_ledger WHERE request_id=?').get(b.requestId);if(old){if(old.actor!==u.id||old.body_json!==JSON.stringify(b))fail('Запрос уже использован.',409);return this.summary(u,now);}const s=this.summary(u,now);if(!s.shift||s.version!==b.version)fail('Деньги в кассе изменились. Обновите расчёт.',409);const delta=b.kind==='count'?b.amountCents-s.balanceCents:b.amountCents;this.db.prepare('INSERT INTO cash_ledger(request_id,shift_id,kind,cents,reason,body_json,actor,created) VALUES(?,?,?,?,?,?,?,?)').run(b.requestId,s.shift.id,b.kind,delta,b.reason.trim(),JSON.stringify(b),u.id,now);return this.summary(u,now);});}
}
