import {withSiteChrome} from './site-shell.mjs';
import {optimizeImages} from './images.mjs';
import {analyticsTag} from './analytics.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const events={
 concerts:{title:'Концерты у воды',intro:'Музыка, закат и вечер, который хочется продлить.',body:'После прогулки по водохранилищу не обязательно спешить домой. Останьтесь на берегу: разговоры с друзьями, отражения огней и любимая музыка создают особое настроение летнего вечера.',heading:'Вечер в своём ритме',details:'Эта страница — место для анонсов музыкальных встреч «СТАРТА». Состав исполнителей, программа, начало и условия входа будут указаны для каждого концерта отдельно. Сейчас ближайшую дату можно уточнить у станции.',prepare:'Планируя вечер у воды, захватите тёплую одежду: после заката на берегу бывает прохладно.'},
 chess:{title:'Шахматный клуб',intro:'Сделайте ход. Остальное подождёт.',body:'Шахматы у воды — повод замедлиться и встретиться за настоящей доской. Здесь интересно и тем, кто только вспоминает ходы фигур, и тем, кто любит обдумывать комбинации. Можно прийти с другом или узнать о ближайшей клубной встрече.',heading:'Партия с видом на воду',details:'Идея клуба — дружеские партии и общение без спешки. Формат встречи, наличие соперников, досок и условия участия уточняйте заранее. Постоянное расписание пока не опубликовано.',prepare:'Сообщите сотруднику, сколько вас будет и какой у вас опыт игры. Если хотите принести свою доску — тоже предупредите.'},
 painting:{title:'Живопись у воды',intro:'Поймайте свет. Сохраните своё лето на бумаге.',body:'Блики на воде, лодки у причала и зелёный берег — сюжеты, которые постоянно меняются. Творческая встреча на свежем воздухе помогает присмотреться к знакомым деталям и провести время иначе: без суеты, с красками и вниманием к пейзажу.',heading:'Вдохновение совсем рядом',details:'На этой странице будут появляться анонсы занятий и творческих встреч. Технику рисования, участие преподавателя, возрастные условия и стоимость сообщим в анонсе конкретного события. Ближайшие планы можно узнать у сотрудника.',prepare:'Перед приездом уточните, входят ли материалы в занятие и что взять с собой. Для самостоятельных зарисовок удобно захватить скетчбук и карандаши.'}
};
export const eventPaths=()=>Object.keys(events).map(id=>'/afisha/'+id+'/');
export function renderEvent(d,id){
 const e=events[id];if(!e)return null;const url='https://spotsup.ru/afisha/'+id+'/',img='/assets/event-'+id+'.webp';
 return withSiteChrome(optimizeImages(`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${analyticsTag()}<title>${esc(e.title)} в Ореховой бухте | СТАРТ</title><meta name="description" content="${esc(e.intro+' '+e.title+' на станции СТАРТ в Болтино. Ближайшие даты и условия участия уточняйте у станции.')}"><meta name="robots" content="${d.seo.indexable?'index,follow':'noindex,nofollow'}"><link rel="canonical" href="${url}"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/services.css"><meta property="og:title" content="${esc(e.title)} | СТАРТ"><meta property="og:image" content="https://spotsup.ru${img}"><meta property="og:url" content="${url}"><meta property="og:type" content="website"></head><body><header><a class="brand" href="/">СТАРТ<span>Ореховая бухта</span></a><a href="tel:${esc(d.phone.replace(/[^+\d]/g,''))}">${esc(d.phone)}</a></header><main><nav aria-label="Хлебные крошки"><a href="/">Главная</a> / <a href="/#events">Афиша и клубы</a> / ${esc(e.title)}</nav><section class="service-hero"><div><p class="eyebrow">АФИША И КЛУБЫ · СТАРТ</p><h1>${esc(e.title)}</h1><p>${esc(e.intro)}</p><p>${esc(e.body)}</p><a class="button" href="https://t.me/${esc(d.telegram)}" target="_blank" rel="noopener noreferrer">Уточнить ближайшую встречу ↗</a></div><figure style="margin:0"><img src="${img}" alt="Иллюстрация: ${esc(e.title)}" width="1536" height="1024"><figcaption>Художественная иллюстрация, не фотография станции.</figcaption></figure></section><section><h2>${esc(e.heading)}</h2><p>${esc(e.details)}</p><p><strong>Дата и стоимость уточняются.</strong> Запись на событие подтверждает сотрудник.</p></section><section><h2>Перед встречей</h2><p>${esc(e.prepare)}</p><p>Место встречи: ${esc(d.texts.address.value).replace(/\n/g,'<br>')}.</p><a href="/#contacts">Как добраться →</a></section><section><h2>Другие поводы приехать</h2><nav class="service-links">${Object.entries(events).filter(([k])=>k!==id).map(([k,v])=>'<a href="/afisha/'+k+'/">'+esc(v.title)+'</a>').join('')}<a href="/#fleet">Прогулки по воде</a></nav></section></main><footer><a href="/">Вернуться на главную</a><p>${esc(d.texts.address.value)}</p></footer></body></html>`),d);
}
