import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {AdminStore} from './admin.mjs';
import {SmsStore} from './sms.mjs';
import {CafeStore} from './cafe.mjs';
import {AqsiCafe} from './aqsi-cafe.mjs';
import {AqsiRental} from './aqsi-rental.mjs';
import {GuestBills} from './guest-bills.mjs';
import {fillTestCafeStock} from './testing/cafe-stock-fixture.mjs';
import {clientRows,clientsXlsx} from './clients-export.mjs';
import {saleBonuses} from './sale-bonus.mjs';
const u={id:1,login:'admin',role:'admin'},s={id:2,login:'worker',role:'staff'};
function fixture(t){const a=new AdminStore(':memory:');t.after(()=>a.close());a.db.exec("INSERT INTO admin_users VALUES(1,'admin','admin','unused'),(2,'worker','staff','unused')");a.env={CASH_LEDGER_ENABLED:'1'};a.workforce.env=a.env;a.workforce.requireOnDuty=()=>{};const now=Date.now();a.db.prepare('INSERT INTO employee_work_sessions(user_id,started_at) VALUES(?,?)').run(2,now-3600000);const c=new CafeStore(a,new SmsStore(a,null,{}));fillTestCafeStock(c);const calls=[],answers=[],conn={read:()=>({apiKey:'test',deviceId:709740}),request:async(url,options)=>{calls.push({url,...options});const answer=answers.shift();if(answer instanceof Error)throw answer;return {ok:true,json:async()=>answer};}};c.terminal=new AqsiCafe(a,conn,c,{enabled:true});a.rentalTerminal=new AqsiRental(a,conn,{enabled:true});const g=new GuestBills(a,conn,c);a.guestBills=g;const item=c.catalog().items.find(i=>i.name==='Сырники'),body=extra=>({requestId:randomUUID(),name:'Гость',phone:'',fulfillment:'pickup',payment:'unspecified',items:[{itemId:item.id,quantity:1,optionIds:[]}],expectedTotalCents:item.priceCents,...extra}),bill=deferred=>g.create({requestId:randomUUID(),name:'Гость',location:'Стол 5',phone:'',deferred},u);return {a,c,g,calls,answers,body,bill,now};}
test('Guest deferred order: kitchen before payment, zero revenue until cash, one recipient, one accounting record',async t=>{const f=fixture(t),b=f.bill(true),r=f.c.create(f.body({guestBillId:b.id}),u);assert.equal(r.details.pendingKitchen,false);assert.equal(f.a.db.prepare('SELECT count(*) n FROM cafe_notifications').get().n,1);const delivered=f.c.status({id:r.id,revision:0,status:'DELIVERED'},u);const day=f.a.workforce.accountingDay(Date.now());assert.equal(f.a.workforce.sales(day,Date.now()).length,0);await assert.rejects(f.c.terminal.begin({id:r.id,revision:delivered.revision},u),/общий/);const pay={id:b.id,revision:f.g.get(b.id).revision,cash:true};await f.g.begin(pay,s);await f.g.begin(pay,s);const sales=f.a.workforce.sales(day,Date.now()+1);assert.equal(sales.length,1);assert.equal(sales[0].bonusActor,2);assert.equal(f.g.list(u).items.length,0);assert.equal(f.calls.length,0);assert.equal(f.c.order(r.id,u).details.cashPaidAt,f.g.get(b.id).paid_at);assert.throws(()=>f.c.create(f.body({guestBillId:b.id}),u),/оплачен/);});
test('Combined bill: one bank payment, two fiscal positions, retry and unknown-result lock',async t=>{const f=fixture(t),b=f.bill(false),r=f.c.create(f.body({guestBillId:b.id}),u),local=t=>new Date(t+10800000).toISOString().slice(0,16),rental=f.a.create({requestId:randomUUID(),equipment:'sup',quantity:1,name:'Гость',phone:'89030000000',departed:local(f.now),amount:'1000',guestBillId:b.id},u);assert.equal(f.a.db.prepare('SELECT count(*) n FROM payments').get().n,0);assert.equal(f.a.db.prepare('SELECT count(*) n FROM cafe_notifications').get().n,0);const total=f.g.get(b.id).totalCents,op=randomUUID(),receipt=randomUUID();f.answers.push({operationId:op});const req={id:b.id,revision:f.g.get(b.id).revision};await Promise.all([f.g.begin(req,s),f.g.begin(req,u)]);assert.equal(f.calls.length,1);assert.equal(JSON.parse(f.calls[0].body).amount,total);await assert.rejects(f.a.rentalTerminal.begin({id:rental,phase:'issue',revision:0},u),/общий/);assert.throws(()=>f.g.cancel({...req,reason:'Отмена'},u),/оплата/);f.answers.push({operationId:op,deviceId:709740,type:'acquiring.purchase',status:'Completed',result:JSON.stringify({id:randomUUID(),device:{id:709740},content:{type:'purchase',amount:total,responseCode:'000',dateTime:new Date().toISOString(),sequenceNumber:'1'}})},{operationId:receipt});await f.g.tick();assert.equal(f.calls.filter(x=>x.url.endsWith('/purchase')).length,1);const fiscal=JSON.parse(f.calls.find(x=>x.url.endsWith('/Receipts/process')).body);assert.equal(fiscal.positions.length,2);assert.equal(fiscal.positions.reduce((n,x)=>n+x.info.finalPrice,0),total);assert.equal(fiscal.payments[0].amount,total);assert.equal(f.a.db.prepare('SELECT sum(amount) n FROM payments').get().n,100000);assert.ok(f.c.order(r.id,u).details.terminalPaidAt);assert.equal(f.a.db.prepare('SELECT count(*) n FROM cafe_notifications').get().n,1);});
test('Confirmed terminal cancellation allows cash; uncertain result never does',async t=>{const f=fixture(t),b=f.bill(false);f.c.create(f.body({guestBillId:b.id}),u);f.answers.push(new Error('network'));const req={id:b.id,revision:f.g.get(b.id).revision};const p=await f.g.begin(req,u);assert.equal(p.state,'payment_unknown');await f.g.begin({...req,cash:true},s);assert.equal(f.g.get(b.id).paid_at,null);assert.equal(f.calls.length,1);f.g.set(p.id,'cancelled');await f.g.begin({id:b.id,revision:f.g.get(b.id).revision,cash:true,retryPaymentId:p.id},s);assert.ok(f.g.get(b.id).paid_at);});
test('Website manual cash: preparation does not recognize revenue; duplicate marks do not double cash',t=>{const f=fixture(t),now=Date.parse('2026-09-29T12:00:00+03:00'),r=f.c.create(f.body({phone:'89030000000',consent:true,payment:'card_on_delivery'}),null,'local',now);assert.ok(r.details.manualPaymentRequired);f.c.status({id:r.id,revision:0,status:'DELIVERED'},u);assert.equal(f.a.workforce.sales('2026-09-29',now+1).length,0);const latest=f.c.order(r.id,u);f.g.manualWebsite({id:r.id,revision:latest.revision,method:'cash'},s);f.g.manualWebsite({id:r.id,revision:latest.revision,method:'cash'},s);assert.equal(f.c.order(r.id,u).details.paymentMethod,'cash');assert.throws(()=>f.g.manualWebsite({id:r.id,revision:latest.revision,method:'card'},s),/другим/);});
test('Cash balance includes cash only, withdrawals, deposits, recount conflicts and idempotency',async t=>{const f=fixture(t);f.a.db.prepare('INSERT INTO shifts(day,opened_at,opened_by,cash_start_cents) VALUES(?,?,?,?)').run(f.a.workforce.accountingDay(),f.now-5000,1,300000);const b=f.bill(false),r=f.c.create(f.body({guestBillId:b.id}),u);await f.g.begin({id:b.id,revision:f.g.get(b.id).revision,cash:true},s);let state=f.a.cashLedger.summary(s);assert.equal(state.balanceCents,300000+r.totalCents);const deposit={requestId:randomUUID(),kind:'deposit',amountCents:10000,reason:'Размен',version:state.version};state=f.a.cashLedger.change(deposit,s);assert.equal(f.a.cashLedger.change(deposit,s).balanceCents,state.balanceCents);assert.throws(()=>f.a.cashLedger.change({...deposit,amountCents:20000},s),/использован/);assert.throws(()=>f.a.cashLedger.change({...deposit,requestId:randomUUID()},s),/изменились/);state=f.a.cashLedger.change({requestId:randomUUID(),kind:'count',amountCents:200000,reason:'Пересчёт',version:state.version},s);assert.equal(state.balanceCents,200000);});
test('Task edits preserve old completion, archive instead of deleting, order and roles',t=>{const f=fixture(t),id=f.a.tasks.create({requestId:randomUUID(),kind:'opening',text:'Первый'},u),next=f.a.tasks.create({requestId:randomUUID(),kind:'opening',text:'Второй'},u);const day=new Date(Date.now()+10800000).toISOString().slice(0,10);f.a.tasks.complete({id,revision:0,day,done:true},s);f.a.tasks.edit({id,revision:0,action:'text',text:'Новый текст'},u);assert.throws(()=>f.a.tasks.edit({id,revision:1,action:'archive'},s),/администратор/);f.a.tasks.edit({id,revision:1,action:'archive'},u);assert.equal(f.a.tasks.list(u).length,1);assert.equal(f.a.db.prepare('SELECT count(*) n FROM station_task_checks').get().n,1);assert.equal(f.a.db.prepare('SELECT count(*) n FROM station_task_edits').get().n,2);});
test('Deferred bonus goes to recipient; ordinary sale remains shared',()=>{const rows=[1,2].map(user_id=>({user_id,worked_ms:100,sessions:[{started_at:0,ended_at:null}]})),r=saleBonuses([{id:'a',cents:10000,at:1},{id:'b',cents:20000,at:2,bonusActor:2}],rows,5);assert.equal(r.rows[0].bonus_cents,250);assert.equal(r.rows[1].bonus_cents,1250);});
test('Client Excel: phone normalization, one visit per day, net paid value, text-safe workbook',async t=>{const f=fixture(t),b=f.bill(true);const r=f.c.create(f.body({guestBillId:b.id,name:'=FORMULA',phone:'89030000000'}),u);f.c.status({id:r.id,revision:0,status:'DELIVERED'},u);await f.g.begin({id:b.id,revision:f.g.get(b.id).revision,cash:true},s);const rows=clientRows(f.a);assert.equal(rows.length,1);assert.equal(rows[0][1],'+79030000000');assert.equal(rows[0][2],1);assert.equal(rows[0][3],r.totalCents/100);const x=clientsXlsx(f.a);assert.equal(x.readUInt32LE(0),0x04034b50);assert.ok(x.includes(Buffer.from('inlineStr')));assert.ok(!x.includes(Buffer.from('<f>')));});

test('Manual reconciliation unlocks only after explicit verification; cash needs no bank request',async t=>{const f=fixture(t),r=f.c.create(f.body(),u);f.answers.push(new Error('network'));const p=await f.c.terminal.begin({id:r.id,revision:0},u);assert.equal(p.state,'payment_unknown');await assert.rejects(f.c.terminal.reconcile({id:r.id,paymentId:p.id,result:'unpaid',confirmed:true,note:'Проверено'},s),/двух минут/);f.a.db.prepare('UPDATE aqsi_cafe SET created=created-180000 WHERE id=?').run(p.id);await assert.rejects(f.c.terminal.reconcile({id:r.id,paymentId:p.id,result:'unpaid',note:'Проверено'},s),/Проверьте/);await f.c.terminal.reconcile({id:r.id,paymentId:p.id,result:'unpaid',confirmed:true,note:'Нет списания, экран кассы свободен'},s);assert.equal(f.c.terminal.terminalBusy(),false);const latest=f.c.order(r.id,s);await f.c.terminal.begin({id:r.id,revision:latest.revision,cash:true,retryPaymentId:p.id},s);assert.equal(f.calls.length,1);assert.equal(f.c.order(r.id,s).details.paymentMethod,'cash');});
test('Direct cash on first attempt does not call acquiring',async t=>{const f=fixture(t),r=f.c.create(f.body(),u);await f.c.terminal.begin({id:r.id,revision:0,cash:true},s);assert.equal(f.calls.length,0);assert.ok(f.c.order(r.id,s).details.cashPaidAt);});
