import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {AdminStore} from './admin.mjs';
import {SmsStore} from './sms.mjs';
import {CafeStore} from './cafe.mjs';
import {AqsiCafe} from './aqsi-cafe.mjs';
import {AqsiRental} from './aqsi-rental.mjs';
import {GuestBills} from './guest-bills.mjs';
import {fillTestCafeStock} from './testing/cafe-stock-fixture.mjs';
import {clientRows,clientsXlsx} from './clients-export.mjs';
import {saleBonuses} from './sale-bonus.mjs';
const u={id:1,login:'admin',role:'admin'},s={id:2,login:'worker',role:'staff'};
function fixture(t){const a=new AdminStore(':memory:');t.after(()=>a.close());a.db.exec("INSERT INTO admin_users VALUES(1,'admin','admin','unused'),(2,'worker','staff','unused')");a.env={CASH_LEDGER_ENABLED:'1'};a.workforce.env=a.env;a.workforce.requireOnDuty=()=>{};const now=Date.now();a.db.prepare('INSERT INTO employee_work_sessions(user_id,started_at) VALUES(?,?)').run(2,now-3600000);const c=new CafeStore(a,new SmsStore(a,null,{}));fillTestCafeStock(c);const calls=[],answers=[],conn={read:()=>({apiKey:'test',deviceId:709740}),request:async(url,options)=>{if(url.includes('/v4/Shifts'))return {ok:true,json:async()=>url.includes('/v4/Shifts?')?{rows:[{id:'test-shift',device:{id:709740}}]}:{id:'test-shift',device:{id:709740},shiftOpenedReport:{dateTime:new Date().toISOString()},shiftClosedReport:null}};calls.push({url,...options});const answer=answers.shift();if(answer instanceof Error)throw answer;return {ok:true,json:async()=>answer};}};c.terminal=new AqsiCafe(a,conn,c,{enabled:true});a.rentalTerminal=new AqsiRental(a,conn,{enabled:true});const g=new GuestBills(a,conn,c);a.guestBills=g;const item=c.catalog().items.find(i=>i.name==='Сырники'),body=extra=>({requestId:randomUUID(),name:'Гость',phone:'',fulfillment:'pickup',payment:'unspecified',items:[{itemId:item.id,quantity:1,optionIds:[]}],expectedTotalCents:item.priceCents,...extra}),bill=deferred=>g.create({requestId:randomUUID(),name:'Гость',location:'Стол 5',phone:'',deferred},u);return {a,c,g,calls,answers,body,bill,now};}
test('Guest deferred order: kitchen before payment, zero revenue until cash, one recipient, one accounting record',async t=>{const f=fixture(t),b=f.bill(true),r=f.c.create(f.body({guestBillId:b.id}),u);assert.equal(r.details.pendingKitchen,false);assert.equal(f.a.db.prepare('SELECT count(*) n FROM cafe_notifications').get().n,1);const delivered=f.c.status({id:r.id,revision:0,status:'DELIVERED'},u);const day=f.a.workforce.accountingDay(Date.now());assert.equal(f.a.workforce.sales(day,Date.now()).length,0);await assert.rejects(f.c.terminal.begin({id:r.id,revision:delivered.revision},u),/общий/);const pay={id:b.id,revision:f.g.get(b.id).revision,cash:true};await f.g.begin(pay,s);await f.g.begin(pay,s);const sales=f.a.workforce.sales(day,Date.now()+1);assert.equal(sales.length,1);assert.equal(sales[0].bonusActor,2);assert.equal(f.g.list(u).items.length,0);assert.equal(f.calls.length,0);assert.equal(f.c.order(r.id,u).details.cashPaidAt,f.g.get(b.id).paid_at);assert.throws(()=>f.c.create(f.body({guestBillId:b.id}),u),/оплачен/);});
test('Combined bill: one bank payment, two fiscal positions, retry and unknown-result lock',async t=>{const f=fixture(t),b=f.bill(false),r=f.c.create(f.body({guestBillId:b.id}),u),local=t=>new Date(t+10800000).toISOString().slice(0,16),rental=f.a.create({requestId:randomUUID(),equipment:'sup',quantity:1,name:'Гость',phone:'89030000000',departed:local(f.now),amount:'1000',guestBillId:b.id},u);assert.equal(f.a.db.prepare('SELECT count(*) n FROM payments').get().n,0);assert.equal(f.a.db.prepare('SELECT count(*) n FROM cafe_notifications').get().n,0);const total=f.g.get(b.id).totalCents,op=randomUUID(),receipt=randomUUID();f.answers.push({operationId:op});const req={id:b.id,revision:f.g.get(b.id).revision};await Promise.all([f.g.begin(req,s),f.g.begin(req,u)]);assert.equal(f.calls.length,1);assert.equal(JSON.parse(f.calls[0].body).amount,total);await assert.rejects(f.a.rentalTerminal.begin({id:rental,phase:'issue',revision:0},u),/общий/);assert.throws(()=>f.g.cancel({...req,reason:'Отмена'},u),/оплата/);f.answers.push({operationId:op,deviceId:709740,type:'acquiring.purchase',status:'Completed',result:JSON.stringify({id:randomUUID(),device:{id:709740},content:{type:'purchase',amount:total,responseCode:'000',dateTime:new Date().toISOString(),sequenceNumber:'1'}})},{operationId:receipt});await f.g.tick();assert.equal(f.calls.filter(x=>x.url.endsWith('/purchase')).length,1);const fiscal=JSON.parse(f.calls.find(x=>x.url.endsWith('/Receipts/process')).body);assert.equal(fiscal.positions.length,2);assert.equal(fiscal.positions.reduce((n,x)=>n+x.info.finalPrice,0),total);assert.equal(fiscal.payments[0].amount,total);assert.equal(f.a.db.prepare('SELECT sum(amount) n FROM payments').get().n,100000);assert.ok(f.c.order(r.id,u).details.terminalPaidAt);assert.equal(f.a.db.prepare('SELECT count(*) n FROM cafe_notifications').get().n,1);});
test('Confirmed terminal cancellation allows cash; uncertain result never does',async t=>{const f=fixture(t),b=f.bill(false);f.c.create(f.body({guestBillId:b.id}),u);f.answers.push(new Error('network'));const req={id:b.id,revision:f.g.get(b.id).revision};const p=await f.g.begin(req,u);assert.equal(p.state,'payment_unknown');await f.g.begin({...req,cash:true},s);assert.equal(f.g.get(b.id).paid_at,null);assert.equal(f.calls.length,1);f.g.set(p.id,'cancelled');await f.g.begin({id:b.id,revision:f.g.get(b.id).revision,cash:true,retryPaymentId:p.id},s);assert.ok(f.g.get(b.id).paid_at);});
test('Website manual cash: preparation does not recognize revenue; duplicate marks do not double cash',t=>{const f=fixture(t),now=Date.parse('2026-09-29T12:00:00+03:00'),r=f.c.create(f.body({phone:'89030000000',consent:true,payment:'card_on_delivery'}),null,'local',now);assert.ok(r.details.manualPaymentRequired);f.c.status({id:r.id,revision:0,status:'DELIVERED'},u);assert.equal(f.a.workforce.sales('2026-09-29',now+1).length,0);const latest=f.c.order(r.id,u);f.g.manualWebsite({id:r.id,revision:latest.revision,method:'cash'},s);f.g.manualWebsite({id:r.id,revision:latest.revision,method:'cash'},s);assert.equal(f.c.order(r.id,u).details.paymentMethod,'cash');assert.throws(()=>f.g.manualWebsite({id:r.id,revision:latest.revision,method:'card'},s),/другим/);});
test('Cash balance includes cash only, withdrawals, deposits, recount conflicts and idempotency',async t=>{const f=fixture(t);f.a.db.prepare('INSERT INTO shifts(day,opened_at,opened_by,cash_start_cents) VALUES(?,?,?,?)').run(f.a.workforce.accountingDay(),f.now-5000,1,300000);const b=f.bill(false),r=f.c.create(f.body({guestBillId:b.id}),u);await f.g.begin({id:b.id,revision:f.g.get(b.id).revision,cash:true},s);let state=f.a.cashLedger.summary(s);assert.equal(state.balanceCents,300000+r.totalCents);const deposit={requestId:randomUUID(),kind:'deposit',amountCents:10000,reason:'Размен',version:state.version};state=f.a.cashLedger.change(deposit,s);assert.equal(f.a.cashLedger.change(deposit,s).balanceCents,state.balanceCents);assert.throws(()=>f.a.cashLedger.change({...deposit,amountCents:20000},s),/использован/);assert.throws(()=>f.a.cashLedger.change({...deposit,requestId:randomUUID()},s),/изменились/);state=f.a.cashLedger.change({requestId:randomUUID(),kind:'count',amountCents:200000,reason:'Пересчёт',version:state.version},s);assert.equal(state.balanceCents,200000);});
test('Task edits preserve old completion, archive instead of deleting, order and roles',t=>{const f=fixture(t),id=f.a.tasks.create({requestId:randomUUID(),kind:'opening',text:'Первый'},u),next=f.a.tasks.create({requestId:randomUUID(),kind:'opening',text:'Второй'},u);const day=new Date(Date.now()+10800000).toISOString().slice(0,10);f.a.tasks.complete({id,revision:0,day,done:true},s);f.a.tasks.edit({id,revision:0,action:'text',text:'Новый текст'},u);assert.throws(()=>f.a.tasks.edit({id,revision:1,action:'archive'},s),/администратор/);f.a.tasks.edit({id,revision:1,action:'archive'},u);assert.equal(f.a.tasks.list(u).length,1);assert.equal(f.a.db.prepare('SELECT count(*) n FROM station_task_checks').get().n,1);assert.equal(f.a.db.prepare('SELECT count(*) n FROM station_task_edits').get().n,2);});
test('Deferred bonus goes to recipient; ordinary sale remains shared',()=>{const rows=[1,2].map(user_id=>({user_id,worked_ms:100,sessions:[{started_at:0,ended_at:null}]})),r=saleBonuses([{id:'a',cents:10000,at:1},{id:'b',cents:20000,at:2,bonusActor:2}],rows,5);assert.equal(r.rows[0].bonus_cents,250);assert.equal(r.rows[1].bonus_cents,1250);});
test('Client Excel: phone normalization, one visit per day, net paid value, text-safe workbook',async t=>{const f=fixture(t),b=f.bill(true);const r=f.c.create(f.body({guestBillId:b.id,name:'=FORMULA',phone:'89030000000'}),u);f.c.status({id:r.id,revision:0,status:'DELIVERED'},u);await f.g.begin({id:b.id,revision:f.g.get(b.id).revision,cash:true},s);const rows=clientRows(f.a);assert.equal(rows.length,1);assert.equal(rows[0][1],'+79030000000');assert.equal(rows[0][2],1);assert.equal(rows[0][3],r.totalCents/100);const x=clientsXlsx(f.a);assert.equal(x.readUInt32LE(0),0x04034b50);assert.ok(x.includes(Buffer.from('inlineStr')));assert.ok(!x.includes(Buffer.from('<f>')));});

test('Manual reconciliation unlocks only after explicit verification; cash needs no bank request',async t=>{const f=fixture(t),r=f.c.create(f.body(),u);f.answers.push(new Error('network'));const p=await f.c.terminal.begin({id:r.id,revision:0},u);assert.equal(p.state,'payment_unknown');await assert.rejects(f.c.terminal.reconcile({id:r.id,paymentId:p.id,result:'unpaid',confirmed:true,note:'Проверено'},s),/двух минут/);f.a.db.prepare('UPDATE aqsi_cafe SET created=created-180000 WHERE id=?').run(p.id);await assert.rejects(f.c.terminal.reconcile({id:r.id,paymentId:p.id,result:'unpaid',note:'Проверено'},s),/Проверьте/);await f.c.terminal.reconcile({id:r.id,paymentId:p.id,result:'unpaid',confirmed:true,note:'Нет списания, экран кассы свободен'},s);assert.equal(f.c.terminal.terminalBusy(),false);const latest=f.c.order(r.id,s);await f.c.terminal.begin({id:r.id,revision:latest.revision,cash:true,retryPaymentId:p.id},s);assert.equal(f.calls.length,1);assert.equal(f.c.order(r.id,s).details.paymentMethod,'cash');});
test('Direct cash on first attempt does not call acquiring',async t=>{const f=fixture(t),r=f.c.create(f.body(),u);await f.c.terminal.begin({id:r.id,revision:0,cash:true},s);assert.equal(f.calls.length,0);assert.ok(f.c.order(r.id,s).details.cashPaidAt);});

for(const role of ['admin','staff','waiter'])test('Delivered unpaid website order can be cancelled by '+role+' without restoring prepared ingredients',t=>{
 const f=fixture(t),actor=role==='admin'?u:{...s,role},r=f.c.create(f.body(),u);
 const details={...r.details,terminalPaymentRequired:true,manualPaymentRequired:true};
 f.a.db.prepare("UPDATE cafe_orders SET source='customer_web',details=? WHERE id=?").run(JSON.stringify(details),r.id);
 const delivered=f.c.status({id:r.id,revision:r.revision,status:'DELIVERED'},actor);
 const stocks=()=>f.a.db.prepare('SELECT id,current_milli FROM inventory_items ORDER BY id').all();const before=stocks();
 assert.throws(()=>f.c.status({id:r.id,revision:r.revision,status:'CANCELLED'},actor),/изменён/);
 const cancelled=f.c.status({id:r.id,revision:delivered.revision,status:'CANCELLED'},actor);
 assert.equal(cancelled.status,'CANCELLED');assert.deepEqual(stocks(),before);
 assert.equal(f.c.status({id:r.id,revision:delivered.revision,status:'CANCELLED'},actor).status,'CANCELLED');
 assert.equal(cancelled.events.filter(e=>e.kind==='CANCELLED').length,1);
});
test('Delivered paid order keeps accounting and requires refund instead of simple cancellation',t=>{
 const f=fixture(t),r=f.c.create(f.body(),u),details={...r.details,terminalPaymentRequired:true,manualPaymentRequired:true,terminalPaidAt:Date.now(),cashPaidAt:Date.now()};
 f.a.db.prepare("UPDATE cafe_orders SET status='DELIVERED',details=? WHERE id=?").run(JSON.stringify(details),r.id);
 assert.throws(()=>f.c.status({id:r.id,revision:r.revision,status:'CANCELLED'},s),/возврат/);
 assert.equal(f.c.order(r.id,s).status,'DELIVERED');
});

test('Guest bill displays real items and combines consecutive additions without any payment requests',t=>{const f=fixture(t),b=f.bill(true),r1=f.c.create(f.body({guestBillId:b.id}),s),r2=f.c.create(f.body({guestBillId:b.id}),s),g=f.g.get(b.id);assert.equal(g.lines.length,2);assert.equal(g.totalCents,r1.totalCents+r2.totalCents);assert.equal(g.lines[0].items[0].name,'Сырники');assert.equal(f.c.order(r1.id,s).details.guestBillId,b.id);assert.equal(f.c.order(r2.id,s).details.guestBillId,b.id);assert.equal(f.calls.length,0);assert.equal(f.a.workforce.sales(f.a.workforce.accountingDay(),Date.now()).length,0);});
test('Cancel bill positions once, preserve history and pay only remaining items',async t=>{const f=fixture(t),b=f.bill(true),r1=f.c.create(f.body({guestBillId:b.id}),s),r2=f.c.create(f.body({guestBillId:b.id}),s);let g=f.g.get(b.id);const line=g.lines[0],body={id:b.id,revision:g.revision,lineId:line.id,orderRevision:line.orderRevision,reason:'Гость передумал',prepared:false};g=f.g.cancelLine(body,s);f.g.cancelLine(body,s);assert.equal(g.totalCents,r2.totalCents);assert.equal(f.c.order(r1.id,s).status,'CANCELLED');assert.equal(g.lines.length,2);assert.equal(g.lines[0].amount,0);await f.g.begin({id:b.id,revision:g.revision,cash:true},s);assert.equal(f.g.get(b.id).totalCents,r2.totalCents);assert.ok(f.c.order(r2.id,s).details.terminalPaidAt);assert.equal(f.c.order(r1.id,s).details.terminalPaidAt,undefined);assert.equal(f.calls.length,0);assert.throws(()=>f.g.cancelLine({...body,lineId:g.lines[1].id},s),/оплачен/);});
for(const method of ['cash','card'])test('Guest bill manual '+method+' payment records collector once without aQsi or duplicate stock',t=>{const f=fixture(t),b=f.bill(true),r=f.c.create(f.body({guestBillId:b.id}),u),g=f.g.get(b.id),stock=f.a.db.prepare('SELECT * FROM inventory_transactions').all(),body={id:b.id,revision:g.revision,paymentId:null,method,confirmed:true,receiptExists:true,terminalIdle:true};f.g.manualPaid(body,s);f.g.manualPaid(body,s);const paid=f.c.order(r.id,s);assert.equal(paid.details.paymentMethod,method);assert.equal(paid.details.bonusActor,s.id);assert.equal(f.g.get(b.id).paid_by,s.id);assert.equal(!!paid.details.cashPaidAt,method==='cash');assert.equal(f.calls.length,0);assert.deepEqual(f.a.db.prepare('SELECT * FROM inventory_transactions').all(),stock);assert.equal(f.a.db.prepare("SELECT count(*) n FROM cafe_order_events WHERE order_id=? AND kind='PAID'").get(r.id).n,1);assert.throws(()=>f.c.create(f.body({guestBillId:b.id}),s),/оплачен/);});
test('Paid bill remains accessible until its food is issued, then leaves open list',async t=>{const f=fixture(t),b=f.bill(false),r=f.c.create(f.body({guestBillId:b.id}),s);await f.g.begin({id:b.id,revision:f.g.get(b.id).revision,cash:true},s);assert.ok(f.g.list(s).items.some(i=>i.id===b.id));const o=f.c.order(r.id,s);f.c.status({id:o.id,revision:o.revision,status:'DELIVERED'},s);assert.equal(f.g.list(s).items.some(i=>i.id===b.id),false);});

test('Cancelling prepared guest positions preserves ingredient consumption',t=>{const f=fixture(t),b=f.bill(true),r=f.c.create(f.body({guestBillId:b.id}),s),g=f.g.get(b.id),l=g.lines[0],before=f.a.db.prepare('SELECT id,current_milli FROM inventory_items').all();f.g.cancelLine({id:b.id,revision:g.revision,lineId:l.id,orderRevision:l.orderRevision,reason:'Уже готовили',prepared:true},s);assert.deepEqual(f.a.db.prepare('SELECT id,current_milli FROM inventory_items').all(),before);assert.equal(f.g.get(b.id).totalCents,0);});

const billSnapshot=f=>JSON.stringify(['guest_bills','guest_bill_lines','guest_bill_payments','aqsi_guest','cafe_orders','cafe_order_events','cafe_notifications','cafe_stock_usage','inventory_items','inventory_transactions','financial_audit_log'].map(table=>f.a.db.prepare('SELECT * FROM '+table).all()));
test('Guest bill attachment failure rolls back order, stock and association as one unit',t=>{
 const f=fixture(t),b=f.bill(true),body=f.body({guestBillId:b.id}),before=billSnapshot(f),attach=f.g.attach.bind(f.g);
 f.g.attach=(...args)=>{attach(...args);throw Error('Injected attachment failure');};
 assert.throws(()=>f.c.create(body,s),/Injected/);assert.equal(billSnapshot(f),before);
 f.g.attach=attach;const r=f.c.create(body,s);assert.equal(f.g.get(b.id).lines.length,1);assert.equal(f.g.get(b.id).lines[0].source_id,r.id);
});
test('Guest cash accounting failure rolls back every order and payment before safe retry',async t=>{
 const f=fixture(t),b=f.bill(false);f.c.create(f.body({guestBillId:b.id}),s);f.c.create(f.body({guestBillId:b.id}),s);
 const body={id:b.id,revision:f.g.get(b.id).revision,cash:true},before=billSnapshot(f),event=f.c.event.bind(f.c);let paid=0;
 f.c.event=(...args)=>{const result=event(...args);if(args[1]==='PAID'&&++paid===2)throw Error('Injected accounting failure');return result;};
 await assert.rejects(f.g.begin(body,s),/Injected/);assert.equal(billSnapshot(f),before);assert.equal(f.calls.length,0);
 f.c.event=event;await f.g.begin(body,s);await f.g.begin(body,s);const bill=f.g.get(b.id);
 assert.ok(bill.paid_at);assert.equal(f.a.db.prepare('SELECT count(*) n FROM aqsi_guest').get().n,1);assert.equal(f.a.db.prepare("SELECT count(*) n FROM cafe_order_events WHERE kind='PAID'").get().n,2);assert.ok(bill.lines.every(l=>f.c.order(l.source_id,s).details.terminalPaidAt===bill.paid_at));assert.equal(f.calls.length,0);
});
test('Whole bill cancellation failure rolls back preceding stock returns and preserves exact audit on retry',t=>{
 const f=fixture(t),b=f.bill(true);f.c.create(f.body({guestBillId:b.id}),s);f.c.create(f.body({guestBillId:b.id}),s);
 const body={id:b.id,revision:f.g.get(b.id).revision,reason:'Гости ушли'},before=billSnapshot(f),cancel=f.c.stock.cancel.bind(f.c.stock);let calls=0;
 f.c.stock.cancel=(...args)=>{const result=cancel(...args);if(++calls===2)throw Error('Injected cancellation failure');return result;};
 assert.throws(()=>f.g.cancel(body,s),/Injected/);assert.equal(billSnapshot(f),before);
 f.c.stock.cancel=cancel;f.g.cancel(body,s);const bill=f.g.get(b.id);assert.ok(bill.cancelled_at);
 for(const line of bill.lines){const order=f.c.order(line.source_id,s);assert.equal(order.status,'CANCELLED');const event=order.events.find(e=>e.kind==='CANCELLED');assert.equal(event.comment,body.reason);assert.equal(event.stock.state,'restored');}
 assert.equal(f.calls.length,0);
});
