import {randomUUID} from 'node:crypto';
import {AqsiPilot} from './aqsi-pilot.mjs';
import {purchaseRequest} from './aqsi-protocol.mjs';
const fail=(m,status=409)=>{throw Object.assign(Error(m),{status});};
const staff=u=>{if(!['admin','staff','waiter'].includes(u?.role))fail('Войдите в админку.',403);};
const uuid=s=>/^[a-f0-9-]{36}$/.test(s||'');
export class GuestBills extends AqsiPilot {
 constructor(admin,connection,cafe){super(admin,connection,'aqsi_guest');this.admin=admin;this.cafe=cafe;this.db.exec(`
 CREATE TABLE IF NOT EXISTS guest_bills(id INTEGER PRIMARY KEY,request_id TEXT UNIQUE NOT NULL,name TEXT NOT NULL,location TEXT NOT NULL,phone TEXT NOT NULL,deferred INTEGER NOT NULL,created INTEGER NOT NULL,actor INTEGER NOT NULL,revision INTEGER NOT NULL DEFAULT 0,paid_at INTEGER,paid_by INTEGER,method TEXT,payment_id TEXT,cancelled_at INTEGER);
 CREATE TABLE IF NOT EXISTS guest_bill_lines(id INTEGER PRIMARY KEY,bill_id INTEGER NOT NULL REFERENCES guest_bills(id),kind TEXT NOT NULL,source_id INTEGER NOT NULL,amount INTEGER NOT NULL,UNIQUE(kind,source_id));
 CREATE TABLE IF NOT EXISTS guest_bill_payments(payment_id TEXT PRIMARY KEY,bill_id INTEGER NOT NULL REFERENCES guest_bills(id));
 `);}
 link(kind,id){return this.db.prepare('SELECT b.*,l.amount FROM guest_bills b JOIN guest_bill_lines l ON l.bill_id=b.id WHERE l.kind=? AND l.source_id=?').get(kind,id);}
 get(id){const b=this.db.prepare('SELECT * FROM guest_bills WHERE id=?').get(id);if(!b)fail('Счёт не найден.',404);const lines=this.db.prepare('SELECT * FROM guest_bill_lines WHERE bill_id=? ORDER BY id').all(id).map(l=>{if(l.kind==='cafe'){const r=this.db.prepare('SELECT details,status,revision FROM cafe_orders WHERE id=?').get(l.source_id);return {...l,items:r?JSON.parse(r.details).items:[],status:r?.status,orderRevision:r?.revision};}const r=this.db.prepare('SELECT equipment,returned FROM rentals WHERE id=?').get(l.source_id);return {...l,title:r?.equipment||'Прокат',status:r?.returned?'DELIVERED':'ACCEPTED'};});return {...b,lines,totalCents:lines.reduce((n,l)=>n+l.amount,0),payment:b.payment_id?{...this.view(this.row(b.payment_id)),...(b.method==='card'&&this.row(b.payment_id)?.state==='cash_done'?{label:'Оплачено картой / QR на другой кассе — подтверждено сотрудником'}:{})}:null};}
 list(u){staff(u);return {items:this.db.prepare("SELECT id FROM guest_bills WHERE cancelled_at IS NULL AND (EXISTS(SELECT 1 FROM guest_bill_lines l JOIN cafe_orders c ON c.id=l.source_id WHERE l.bill_id=guest_bills.id AND l.kind='cafe' AND l.amount>0 AND c.status NOT IN ('DELIVERED','CANCELLED')) OR paid_at IS NULL OR payment_id IN (SELECT id FROM aqsi_guest WHERE state NOT IN ('done','cash_done','cancelled'))) ORDER BY created,id").all().map(r=>this.get(r.id))};}
 create(b,u,now=Date.now()){staff(u);if(!uuid(b.requestId)||typeof b.name!=='string'||!b.name.trim()||b.name.length>100||typeof b.location!=='string'||b.location.length>120||typeof (b.phone||'')!=='string'||(b.phone||'').length>32||typeof b.deferred!=='boolean')fail('Укажите имя гостя и место.',400);this.admin.workforce.requireOnDuty(now,u);return this.admin.workforce.tx(()=>{const old=this.db.prepare('SELECT * FROM guest_bills WHERE request_id=?').get(b.requestId);if(old){if(old.actor!==u.id||old.name!==b.name.trim()||old.deferred!==Number(b.deferred)||old.location!==b.location.trim()||old.phone!==(b.phone||''))fail('Запрос уже использован.');return this.get(old.id);}const id=Number(this.db.prepare('INSERT INTO guest_bills(request_id,name,location,phone,deferred,created,actor) VALUES(?,?,?,?,?,?,?)').run(b.requestId,b.name.trim(),b.location.trim(),b.phone||'',Number(b.deferred),now,u.id).lastInsertRowid);return this.get(id);});}
 editable(id,u){staff(u);if(!Number.isSafeInteger(id))fail('Выберите счёт.',400);const b=this.get(id);if(b.paid_at||b.cancelled_at||b.payment&&!['cancelled'].includes(b.payment.state))fail('Счёт уже оплачен или оплата запущена.');return b;}
 // Called inside the order creation transaction; order and association commit together.
 attach(id,kind,sourceId,amount,u){const b=this.editable(id,u);if(!Number.isSafeInteger(amount)||amount<=0)fail('В счёт добавляются платные позиции.');if(b.totalCents+amount>100000000)fail('Слишком большая сумма счёта.');this.db.prepare('INSERT INTO guest_bill_lines(bill_id,kind,source_id,amount) VALUES(?,?,?,?)').run(id,kind,sourceId,amount);this.db.prepare('UPDATE guest_bills SET revision=revision+1 WHERE id=?').run(id);return b;}
 async begin(b,u){staff(u);if(b.cash!==undefined&&typeof b.cash!=='boolean')fail('Неверный способ оплаты.',400);this.admin.workforce.requireOnDuty(Date.now(),u);let created=false;
 const p=this.admin.workforce.tx(()=>{const bill=this.get(b.id);if(bill.cancelled_at)fail('Счёт отменён.');const previous=bill.payment_id?this.row(bill.payment_id):null;if(previous&&previous.state!=='cancelled')return previous;if(bill.paid_at)fail('Счёт оплачен.');if(b.revision!==bill.revision||!bill.totalCents)fail('Счёт изменился. Проверьте сумму.');if(previous&&b.retryPaymentId!==previous.id)fail('Обновите результат отменённой оплаты.');
 if(bill.deferred&&u.role!=='admin'&&!this.db.prepare('SELECT id FROM employee_work_sessions WHERE user_id=? AND ended_at IS NULL').get(u.id))fail('Сначала отметьтесь на смене: бонус получит сотрудник, принявший деньги.');
 const c=this.connection.read();if(!b.cash&&(!c.apiKey||!c.deviceId))fail('Касса не подключена.');if(!b.cash&&this.terminalBusy())fail('Касса занята или ожидает сверки.');const id=randomUUID(),now=Date.now();this.db.prepare("INSERT INTO aqsi_guest(id,request_id,device_id,amount,state,created,updated,actor) VALUES(?,?,?,?,?,?,?,?)").run(id,randomUUID(),c.deviceId||0,bill.totalCents,b.cash?'cash_done':'payment_sending',now,now,u.id);this.db.prepare('UPDATE guest_bills SET payment_id=?,revision=revision+1 WHERE id=?').run(id,bill.id);this.db.prepare('INSERT INTO guest_bill_payments VALUES(?,?)').run(id,bill.id);created=true;if(b.cash)this.account(this.row(id));return this.row(id);});
 if(created&&p.state!=='cash_done')await this.send(p.id,'payment',purchaseRequest(p.device_id,p.amount));return this.view(this.row(p.id));}
 account(row,manualMethod=null){const map=this.db.prepare('SELECT bill_id FROM guest_bill_payments WHERE payment_id=?').get(row.id),b=this.get(map.bill_id),p=this.row(row.id);if(b.paid_at)return;if(p.state!=='cash_done'&&(p.state!=='paid'||!p.slip))return;if(b.totalCents!==p.amount||b.cancelled_at)fail('Нужна сверка счёта.');const now=Date.now(),t=p.slip?Date.parse(JSON.parse(p.slip).content.dateTime):now,at=Number.isFinite(t)&&t>=p.created-300000&&t<=now+300000?t:now,method=manualMethod||(p.state==='cash_done'?'cash':'card');
 for(const l of b.lines){if(!l.amount)continue;if(l.kind==='cafe'){const r=this.cafe.order(l.source_id,{id:p.actor,role:'staff'}),d=r.details;if(r.status==='CANCELLED'||d.terminalPaidAt||r.total_cents!==l.amount)fail('Заказ требует сверки.');const pending=d.pendingKitchen;d.pendingKitchen=false;d.terminalPaidAt=at;d.paymentMethod=method;if(method==='cash')d.cashPaidAt=at;if(b.deferred)d.bonusActor=p.actor;const status=d.terminalQuickSale?'DELIVERED':r.status==='NEW'?'ACCEPTED':r.status;
 this.db.prepare('UPDATE cafe_orders SET details=?,status=?,updated=?,revision=revision+1 WHERE id=?').run(JSON.stringify(d),status,at,r.id);this.cafe.event(r.id,'PAID',{id:p.actor},{billId:b.id},at);if(pending){const e=this.cafe.event(r.id,'NEW',{id:p.actor},{items:d.items,totalCents:r.total_cents},at);this.db.prepare('INSERT INTO cafe_notifications(event_id,due) VALUES(?,?)').run(e,at);}}
 else{const rental=this.db.prepare('SELECT * FROM rentals WHERE id=?').get(l.source_id);if(!rental||rental.initial_due<0)fail('Аренда требует сверки.');this.db.prepare('INSERT INTO payments(rental_id,amount,method,day,created,user_id,note) VALUES(?,?,?,?,?,?,?)').run(rental.id,l.amount,method,this.admin.workforce.accountingDay(at),at,p.actor,'Счёт гостя №'+b.id);this.db.prepare('UPDATE rentals SET initial_due=0,revision=revision+1 WHERE id=?').run(rental.id);this.db.prepare("UPDATE inquiries SET status='issued',revision=revision+1 WHERE rental_id=? AND status='payment_pending'").run(rental.id);}}
 this.db.prepare('UPDATE guest_bills SET paid_at=?,paid_by=?,method=?,revision=revision+1 WHERE id=?').run(at,p.actor,method,b.id);this.admin.workforce.audit({id:p.actor},'guest_bill_paid',b.id,null,{amount:p.amount,method,deferred:!!b.deferred},'Оплата счёта гостя',at);}
 receiptPositions(row){const map=this.db.prepare('SELECT bill_id FROM guest_bill_payments WHERE payment_id=?').get(row.id),b=this.get(map.bill_id);return ['rental','cafe'].map(kind=>({kind,amount:b.lines.filter(l=>l.kind===kind).reduce((n,l)=>n+l.amount,0)})).filter(x=>x.amount).map(x=>({info:{name:x.kind==='rental'?'Аренда спорт инвентаря':'Лимонад',calculationTypeId:4,calculationSubjectId:x.kind==='rental'?4:1,taxRateId:6,quantityUnitId:0,baseQuantity:'1',finalPrice:x.amount}}));}
 async fiscalize(row){this.admin.workforce.tx(()=>this.account(row));return super.fiscalize(this.row(row.id));}
 cancel(b,u){staff(u);return this.admin.workforce.tx(()=>{const bill=this.editable(b.id,u);if(bill.revision!==b.revision)fail('Счёт изменился.');if(typeof b.reason!=='string'||!b.reason.trim())fail('Укажите причину отмены.');for(const l of bill.lines){if(l.kind==='rental'&&bill.deferred&&!this.db.prepare('SELECT returned FROM rentals WHERE id=?').get(l.source_id)?.returned)fail('Сначала отметьте фактический возврат техники.');if(l.kind==='cafe'){const r=this.cafe.order(l.source_id,u);const stock=this.cafe.stock.cancel(r,u,Date.now());this.db.prepare("UPDATE cafe_orders SET status='CANCELLED',updated=?,revision=revision+1 WHERE id=?").run(Date.now(),r.id);this.cafe.event(r.id,'CANCELLED',u,{comment:b.reason,stock,billId:bill.id},Date.now());}else{this.db.prepare('UPDATE rentals SET initial_due=-1,returned=?,returned_by=?,revision=revision+1 WHERE id=?').run(Date.now(),u.id,l.source_id);this.db.prepare("UPDATE inquiries SET status='confirmed',rental_id=NULL,revision=revision+1 WHERE rental_id=?").run(l.source_id);}}this.db.prepare('UPDATE guest_bills SET cancelled_at=?,revision=revision+1 WHERE id=?').run(Date.now(),bill.id);return {ok:true};});}
 cancelLine(b,u){staff(u);return this.admin.workforce.tx(()=>{const bill=this.editable(b.id,u),l=bill.lines.find(l=>l.id===b.lineId);if(!l||l.kind!=='cafe')fail('Выберите позиции кафе.');if(!l.amount)return this.get(b.id);if(bill.revision!==b.revision||l.orderRevision!==b.orderRevision)fail('Счёт изменился. Обновите его.');if(typeof b.reason!=='string'||!b.reason.trim()||b.reason.length>300)fail('Укажите причину отмены.');const r=this.cafe.order(l.source_id,u),now=Date.now();if(r.details.terminalPaidAt||r.status==='CANCELLED')fail('Нужна сверка заказа.');if(typeof b.prepared!=='boolean')fail('Укажите, начали ли готовить позиции.');if(b.prepared&&!r.events.some(e=>['COOKING','READY','DELIVERED'].includes(e.kind)))this.cafe.event(r.id,'COOKING',u,{manualPreparationConfirmation:true},now);const stock=this.cafe.stock.cancel(this.cafe.order(r.id,u),u,now);this.db.prepare("UPDATE cafe_orders SET status='CANCELLED',updated=?,revision=revision+1 WHERE id=?").run(now,r.id);this.cafe.event(r.id,'CANCELLED',u,{comment:b.reason,stock,billId:bill.id},now);this.db.prepare('UPDATE guest_bill_lines SET amount=0 WHERE id=?').run(l.id);this.db.prepare('UPDATE guest_bills SET revision=revision+1 WHERE id=?').run(bill.id);this.admin.workforce.audit(u,'guest_bill_line_cancelled',bill.id,{lineId:l.id,amount:l.amount},{amount:0},b.reason,now);return this.get(bill.id);});}
 manualPaid(b,u){staff(u);if(!['cash','card'].includes(b.method)||b.confirmed!==true||b.receiptExists!==true||b.terminalIdle!==true)fail('Подтвердите оплату, фискальный чек и завершение операции на кассе.');return this.admin.workforce.tx(()=>{const bill=this.get(b.id),old=bill.payment_id?this.row(bill.payment_id):null;if(bill.paid_at&&['done','cash_done'].includes(old?.state))return this.get(b.id);if(bill.cancelled_at||bill.revision!==b.revision||!bill.totalCents||(old?.id||null)!==(b.paymentId||null))fail('Счёт изменился. Обновите его.');if(old&&!['done','cash_done','cancelled'].includes(old.state)&&Date.now()-old.created<120000)fail('Дождитесь завершения операции: до двух минут.');if(old?.slip&&b.method!=='card')fail('Подтверждена оплата картой / QR.');if(bill.deferred&&u.role!=='admin'&&!this.db.prepare('SELECT id FROM employee_work_sessions WHERE user_id=? AND ended_at IS NULL').get(u.id))fail('Сначала отметьтесь на смене: бонус получит сотрудник, принявший деньги.');const now=Date.now(),id=old?.id||randomUUID();if(!old){this.db.prepare('INSERT INTO aqsi_guest(id,request_id,device_id,amount,state,created,updated,actor) VALUES(?,?,?,?,?,?,?,?)').run(id,randomUUID(),0,bill.totalCents,'cash_done',now,now,u.id);this.db.prepare('UPDATE guest_bills SET payment_id=? WHERE id=?').run(id,bill.id);this.db.prepare('INSERT INTO guest_bill_payments VALUES(?,?)').run(id,bill.id);}else{if(old.amount!==bill.totalCents)fail('Сумма операции отличается от счёта.');this.set(id,old.slip?'paid':'cash_done');if(!bill.paid_at)this.db.prepare('UPDATE aqsi_guest SET actor=? WHERE id=?').run(u.id,id);}this.account(this.row(id),b.method);if(old?.slip)this.set(id,'done');this.admin.workforce.audit(u,'guest_bill_manual_payment',bill.id,{paymentId:old?.id||null},{method:b.method,amount:bill.totalCents,receiptConfirmed:true},'Сотрудник подтвердил оплату и фискальный чек на кассе.',now);return this.get(b.id);});}
 manualWebsite(b,u){staff(u);if(!['cash','card'].includes(b.method))fail('Укажите способ оплаты.');return this.admin.workforce.tx(()=>{const r=this.cafe.order(b.id,u),d=r.details;if(!d.manualPaymentRequired||!['customer_web','customer_nfc'].includes(r.source))fail('Это не заказ с ручной оплатой.');if(d.terminalPaidAt){if(d.paymentMethod!==b.method)fail('Оплата уже отмечена другим способом.');return {ok:true};}if(r.revision!==b.revision||r.status==='CANCELLED')fail('Заказ изменился.');const at=Date.now();d.terminalPaidAt=at;d.paymentMethod=b.method;if(b.method==='cash')d.cashPaidAt=at;this.db.prepare('UPDATE cafe_orders SET details=?,revision=revision+1 WHERE id=?').run(JSON.stringify(d),r.id);this.cafe.event(r.id,'PAID',u,{method:b.method,manual:true},at);return {ok:true};});}
}
