import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import http from 'node:http';
import {AdminStore} from './admin.mjs';
import {InventoryStore,inventoryHandler,quantity,quantityText,normalizeInventoryName} from './inventory.mjs';

function fixture(seed=false){const admin=new AdminStore(':memory:');admin.db.prepare('INSERT INTO admin_users(id,login,role,password) VALUES(1,?,?,?)').run('admin','admin','test-only');admin.db.prepare('INSERT INTO admin_users(id,login,role,password) VALUES(2,?,?,?)').run('station','staff','test-only');const store=new InventoryStore(admin,{seed}),u={id:1,login:'admin',role:'admin'},w={id:2,login:'station',role:'staff'};return {admin,store,u,w,close:()=>admin.close()};}
const body=(extra={})=>({name:'Молоко',category:'Кафе',unit:'л',current:'4',minimum:'5',target:'12',comment:'',manualBuy:false,requestId:randomUUID(),...extra});
const save=(f,extra={})=>f.store.save(body(extra),f.u).item;
const move=(f,i,kind,amount,extra={})=>f.store.move({id:i.id,revision:i.revision,kind,amount,reason:'Пересчёт',requestId:randomUUID(),...extra},f.u).item;
function check(name,fn){test(name,async()=>{const f=fixture();try{await fn(f);}finally{f.close();}});}

test('Inventory quantities use integer thousandths, including negative history',()=>{assert.equal(quantity('1,025'),1025);assert.equal(quantityText(1025),'1.025');assert.equal(quantityText(-250),'−0.25'.replace('−','-'));assert.equal(quantityText(-2500),'-2.5');for(const v of ['-1','NaN','1e2','0.0001','1000000000',0.1])assert.throws(()=>quantity(v));assert.equal(quantity('',true),null);});
check('Purchase threshold is inclusive and positive target difference only',f=>{const i=save(f);assert.equal(i.buyQuantity,'8');assert.equal(i.needsPurchase,true);const at=move(f,i,'SET','5');assert.equal(at.buyQuantity,'7');assert.equal(move(f,at,'SET','6').needsPurchase,false);const zero=save(f,{name:'Нулевой запас',current:'0',minimum:'0',target:'0'});assert.equal(zero.needsPurchase,false);});
check('Numeric stock units reject without creating items, units or audit entries',f=>{for(const unit of ['123',' 1,5 ','-2','+3.5'])assert.throws(()=>save(f,{unit}),/единицы/);for(const table of ['inventory_items','inventory_units','inventory_transactions'])assert.equal(f.admin.db.prepare('SELECT count(*) n FROM '+table).get().n,0);assert.equal(save(f,{unit:'шт.'}).unit,'шт.');});
check('Unknown numbers never become zero; manual flag supports potatoes without guesses',f=>{const i=save(f,{current:null,minimum:null,target:null});assert.equal(i.needsPurchase,false);const fries=save(f,{name:'Фри',current:null,minimum:null,target:null,manualBuy:true});assert.equal(fries.needsPurchase,true);assert.equal(fries.buyQuantity,null);assert.throws(()=>move(f,fries,'PURCHASE','5'),/до операции/);const after=move(f,fries,'PURCHASE','5',{baseline:'0'});assert.equal(after.current,'5');assert.equal(after.needsPurchase,false);});
check('Purchase adds actual amount; partial purchase stays required until threshold crossed',f=>{let i=save(f);i=move(f,i,'PURCHASE','0.5');assert.equal(i.current,'4.5');assert.equal(i.buyQuantity,'7.5');i=move(f,i,'PURCHASE','8');assert.equal(i.current,'12.5');assert.equal(i.needsPurchase,false);});
check('Fractional receipt and write-off are exact; negative stock rolls back',f=>{let i=save(f,{current:'0.1'});i=move(f,i,'RECEIPT','0.2');assert.equal(i.current,'0.3');i=move(f,i,'WRITE_OFF','0.25');assert.equal(i.current,'0.05');assert.throws(()=>move(f,i,'WRITE_OFF','0.1'),/больше/);assert.equal(f.store.row(i.id).current_milli,50);});
check('Duplicate stock operation does not credit twice; changed payload rejected',f=>{const i=save(f),b={id:i.id,revision:0,kind:'PURCHASE',amount:'3',requestId:randomUUID()};f.store.move(b,f.u);assert.equal(f.store.move(b,f.u).duplicate,true);assert.equal(f.store.row(i.id).current_milli,7000);assert.throws(()=>f.store.move({...b,amount:'4'},f.u),/Ключ/);});
check('Concurrent or stale edits cannot overwrite a newer balance',f=>{const i=save(f);move(f,i,'RECEIPT','2');assert.throws(()=>move(f,i,'SET','1'),/уже изменён/);assert.throws(()=>f.store.save(body({...i,id:i.id,revision:0,manualBuy:false,current:'2'}),f.u),/уже изменён/);assert.equal(f.store.row(i.id).current_milli,6000);});
check('Employees can receive stock and create items but cannot archive',f=>{const i=save(f);assert.equal(f.store.catalog(f.w).canEdit,false);assert.equal(f.store.summary(f.w).items.length,1);for(const u of [{...f.w,login:'ordinary'},{...f.w,login:'ordinary',role:'waiter'}]){assert.equal(f.store.catalog(u).canAdjust,true);assert.throws(()=>f.store.move({id:i.id},u));assert.throws(()=>f.store.archive({id:i.id},u),e=>e.status===403);}assert.throws(()=>f.store.catalog(null),e=>e.status===401);});
check('Normalized aliases prevent duplicates including archived products',f=>{const i=save(f,{name:'Fanta'});for(const name of [' ФАНТА ','Fanta','FANTA'])assert.throws(()=>save(f,{name}),/уже существует/);f.store.archive({id:i.id,revision:0,active:false,requestId:randomUUID()},f.u);assert.throws(()=>save(f,{name:'Фанта'}),/уже существует/);assert.equal(normalizeInventoryName('Корона'),'corona extra');});
check('Archive preserves history and removes purchase item; restore keeps balance',f=>{let i=save(f);i=f.store.archive({id:i.id,revision:0,active:false,requestId:randomUUID()},f.u).item;assert.equal(f.store.summary(f.u).items.length,0);assert.throws(()=>move(f,i,'SET','2'),/архиве/);i=f.store.archive({id:i.id,revision:1,active:true,requestId:randomUUID()},f.u).item;assert.equal(i.current,'4');assert.equal(f.store.summary(f.u).items.length,1);assert.equal(f.store.history(new URLSearchParams(),f.u).items.length,3);});
check('History snapshots keep former names, categories, units and actor',f=>{let i=save(f);i=move(f,i,'WRITE_OFF','2',{reason:'Расход на кухне'});const h=f.store.history(new URLSearchParams({type:'WRITE_OFF',item:String(i.id)}),f.u).items[0];assert.equal(h.delta,'-2');assert.equal(h.actor_login,'admin');assert.equal(h.reason,'Расход на кухне');save(f,{...i,id:i.id,revision:i.revision,name:'Молоко новое',category:'Другое',unit:'мл',current:'2000',minimum:'5000',target:'12000',manualBuy:false});assert.equal(f.store.history(new URLSearchParams({category:String(h.category_id),type:'WRITE_OFF'}),f.u).items[0].after.unit,'л');});
check('Custom categories and units are persistent, normalized and reusable',f=>{save(f,{category:'Техника',unit:'баллоны'});save(f,{name:'Газ',category:' техника ',unit:'Баллоны'});const d=f.store.catalog(f.u);assert.equal(d.categories.length,1);assert.equal(d.units.length,1);assert.throws(()=>save(f,{name:'Неверно',minimum:'10',target:'2'}),/Желаемый/);});
check('History pagination and Moscow date filters are bounded',f=>{let i=save(f);for(let n=0;n<55;n++)i=move(f,i,'SET',String(n));const first=f.store.history(new URLSearchParams(),f.u);assert.equal(first.items.length,50);const second=f.store.history(new URLSearchParams({before:String(first.next)}),f.u);assert.equal(second.items.length,6);assert.equal(new Set([...first.items,...second.items].map(x=>x.id)).size,56);assert.throws(()=>f.store.history(new URLSearchParams({date:'2026-02-31'}),f.u));assert.equal(f.store.history(new URLSearchParams({date:'2000-01-01'}),f.u).items.length,0);});
test('Seed is idempotent, keeps 148 distinct items, exact known counts and unknown quantities',()=>{const f=fixture(true);try{const d=f.store.catalog(f.u);assert.equal(d.items.length,148);assert.equal(d.categories.length,17);assert.equal(new Set(d.items.map(i=>i.normalized_name)).size,148);const corona=d.items.find(x=>x.name==='Corona Extra');assert.equal(corona.current,'20');assert.equal(corona.minimum,null);assert.equal(d.items.find(x=>x.name==='Разливное пиво / кега').current,null);assert.match(d.items.find(x=>x.name==='Сырники').comment,/Мало/);assert.deepEqual(f.store.summary(f.u).items.map(x=>x.name),['Картофель фри']);move(f,corona,'SET','19');new InventoryStore(f.admin);assert.equal(f.store.catalog(f.u).items.length,148);assert.equal(f.store.row(corona.id).current_milli,19000);}finally{f.close();}});
check('Invalid request shape cannot mutate stock',f=>{for(const b of [null,[],1])assert.throws(()=>f.store.save(b,f.u));assert.equal(f.store.catalog(f.u).items.length,0);});
check('Inventory HTTP protects auth, roles, origin, method and JSON body',async f=>{let origin;const users={admin:f.u,staff:{...f.w,login:'ordinary'},station:f.w},auth={user:t=>users[t]||null};const server=http.createServer(async(req,res)=>{await inventoryHandler(f.store,auth,origin)(req,res,new URL(req.url,origin));});await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;const req=(path,opts={})=>fetch(origin+'/api/admin/inventory/'+path,opts);const headers={'Content-Type':'application/json',Cookie:'__Host-start_session=admin'};try{assert.equal((await req('catalog')).status,401);assert.equal((await req('catalog',{headers:{Cookie:'__Host-start_session=staff'}})).status,200);assert.equal((await req('items',{method:'POST',headers:{...headers,Origin:origin,Cookie:'__Host-start_session=staff'},body:JSON.stringify(body({name:'Товар сотрудника'}))})).status,200);assert.equal((await req('items',{method:'POST',headers:{...headers,Origin:'https://evil.test'},body:JSON.stringify(body())})).status,403);assert.equal((await req('items',{method:'POST',headers:{...headers,Origin:origin},body:'x'.repeat(5000)})).status,413);assert.equal((await req('items',{method:'POST',headers:{...headers,Origin:origin},body:'[]'})).status,400);const r=await req('items',{method:'POST',headers:{...headers,Origin:origin},body:JSON.stringify(body())});assert.equal(r.status,200);assert.equal((await r.json()).item.buyQuantity,'8');assert.equal((await req('items',{method:'DELETE',headers})).status,405);const sh={...headers,Origin:origin,Cookie:'__Host-start_session=station'};const created=await req('items',{method:'POST',headers:sh,body:JSON.stringify(body({name:'Товар station'}))});assert.equal(created.status,200);const i=(await created.json()).item;assert.equal((await req('move',{method:'POST',headers:sh,body:JSON.stringify({id:i.id,revision:i.revision,kind:'RECEIPT',amount:'2',requestId:randomUUID()})})).status,200);assert.equal((await req('archive',{method:'POST',headers:sh,body:JSON.stringify({id:i.id,revision:1,active:false,requestId:randomUUID()})})).status,403);}finally{await new Promise(r=>server.close(r));}});

check('Unknown baseline purchase records actual purchase, not guessed old stock',f=>{const i=save(f,{current:null,minimum:null,target:null});move(f,i,'PURCHASE','3.125',{baseline:'2'});const h=f.store.history(new URLSearchParams({type:'PURCHASE'}),f.u).items[0];assert.equal(h.delta,'3.125');assert.equal(h.before.current_milli,null);assert.equal(h.after.current_milli,5125);assert.match(h.reason,/остаток до операции: 2 л/);});
check('Multiline comments are preserved, control characters and malformed names rejected',f=>{const i=save(f,{comment:'Мало\nПроверить утром'});assert.equal(i.comment,'Мало\nПроверить утром');assert.throws(()=>save(f,{name:'Товар\nновый'}));assert.throws(()=>save(f,{name:'Другое',comment:'test\u0000'}));});

check('Station may create and adjust stock with audit, but not edit metadata or archive',f=>{
 assert.equal(f.store.catalog(f.w).canCreate,true);assert.equal(f.store.catalog(f.w).canAdjust,true);assert.equal(f.store.catalog(f.w).canEdit,false);
 let i=f.store.save(body(),f.w).item;
 for(const [kind,amount,expected] of [['RECEIPT','2','6'],['WRITE_OFF','1','5'],['SET','3','3'],['PURCHASE','7','10']]){const b={id:i.id,revision:i.revision,kind,amount,reason:'Пересчёт',requestId:randomUUID()};i=f.store.move(b,f.w).item;assert.equal(i.current,expected);assert.equal(f.store.move(b,f.w).duplicate,true);}
 assert.throws(()=>f.store.save(body({...i,manualBuy:false,name:'Переименован'}),f.w),e=>e.status===403);
 assert.throws(()=>f.store.archive({id:i.id,revision:i.revision,active:false,requestId:randomUUID()},f.w),e=>e.status===403);
 const h=f.store.history(new URLSearchParams(),f.w).items;assert.equal(h.length,5);assert.ok(h.every(x=>x.actor===f.w.id&&x.actor_login==='station'));
});
