import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {AdminStore} from './admin.mjs';
import {CafeStore} from './cafe.mjs';
import {SmsStore} from './sms.mjs';
const now=Date.parse('2026-09-27T12:00:00+03:00'),user={id:1,role:'staff'};
function fixture(){const a=new AdminStore(':memory:');a.db.exec("INSERT INTO admin_users VALUES(1,'test','staff','unused')");a.workforce.action({requestId:randomUUID()},user,'start',now-3600000);return {a,c:new CafeStore(a,new SmsStore(a,null,{}),{env:{}})};}
test('Manual rental sale: payment, no active rental, retry, conflict, refund',()=>{const {a}=fixture();try{const b={requestId:randomUUID(),title:'Услуга',quantity:2,unitCents:12345,method:'cash'},r=a.manualSale(b,user,now);assert.equal(a.manualSale(b,user,now).id,r.id);assert.throws(()=>a.manualSale({...b,quantity:3},user,now));const {method,...withoutMethod}=b;assert.throws(()=>a.manualSale({...withoutMethod,requestId:randomUUID()},user,now),/способ полученной оплаты/);assert.equal(a.db.prepare('SELECT count(*) n FROM rentals WHERE returned IS NULL').get().n,0);assert.equal(a.db.prepare('SELECT sum(amount) n FROM payments').get().n,24690);a.refunds.create({requestId:randomUUID(),kind:'rental',id:r.id,amountCents:1000,reason:'Ошибка'},user,now+1000);assert.equal(a.refunds.info('rental',r.id,user).remainingCents,23690);assert.throws(()=>a.manualSale({...b,requestId:randomUUID(),unitCents:-1},user,now));}finally{a.close();}});
test('Legacy manual sale retry after upgrade returns the saved sale without inventing its method',()=>{const {a}=fixture();try{const b={requestId:randomUUID(),title:'Старая продажа',quantity:1,unitCents:10000,method:'cash'},r=a.manualSale(b,user,now),{method,...legacy}=b;a.db.prepare('UPDATE rentals SET custom_json=? WHERE id=?').run(JSON.stringify({title:b.title,quantity:b.quantity,unitCents:b.unitCents}),r.id);a.db.prepare("UPDATE payments SET method='unspecified' WHERE rental_id=?").run(r.id);assert.equal(a.manualSale(legacy,user,now+1).id,r.id);assert.equal(a.db.prepare('SELECT count(*) n FROM payments').get().n,1);assert.equal(a.db.prepare('SELECT method FROM payments').get().method,'unspecified');}finally{a.close();}});
test('Manual cafe lines: staff only, exact total, paid order, refunds, no ingredient usage',()=>{const {a,c}=fixture();try{const line={custom:true,itemId:'manual-'+randomUUID(),name:'Услуга кафе',unitCents:12550,quantity:2};assert.throws(()=>c.calculate([line],'pickup'));const b={requestId:randomUUID(),items:[line],fulfillment:'pickup',payment:'unspecified',expectedTotalCents:25100,quickSale:true},r=c.create(b,user,'test',now);assert.equal(c.order(r.id,user).total_cents,25100);assert.equal(c.order(r.id,user).status,'DELIVERED');assert.equal(a.db.prepare('SELECT count(*) n FROM cafe_stock_usage').get().n,0);a.refunds.create({requestId:randomUUID(),kind:'cafe',id:r.id,amountCents:12550,lines:[{index:0,quantity:1}],reason:'Ошибка'},user,now+1000);assert.equal(a.refunds.info('cafe',r.id,user).remainingCents,12550);}finally{a.close();}});
