import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createHash} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Worker} from 'node:worker_threads';
import {AdminStore} from './admin.mjs';
import {CafeStore} from './cafe.mjs';
import {SmsStore} from './sms.mjs';
import {basePayCents,distribute,workforceHandler} from './workforce.mjs';
import http from 'node:http';
const day='2026-09-25',at=t=>Date.parse(day+'T'+t+':00+03:00'),u={id:1,role:'admin'},employees=Array.from({length:5},(_,i)=>({id:i+2,role:'staff'}));
function fixture(file=':memory:'){const a=new AdminStore(file);if(!a.configured())a.db.exec("INSERT INTO admin_users VALUES(1,'admin','admin','unused'),(2,'ivan','staff','unused'),(3,'anna','staff','unused'),(4,'sergey','staff','unused'),(5,'olga','staff','unused'),(6,'oleg','staff','unused')");const w=a.workforce;w.env={TELEGRAM_BOT_TOKEN:'fake',TELEGRAM_CHAT_ID:'1',SITE_ORIGIN:'https://spotsup.ru'};a.db.prepare("UPDATE admin_config SET value=? WHERE key='workforce_reports_from'").run(day);const messages=[];w.request=async(url,b)=>{messages.push(JSON.parse(b.body));return {ok:true,json:async()=>({ok:true})};};return {a,w,messages,close:()=>a.close()};}
const start=(f,e,t)=>f.w.action({requestId:randomUUID()},e,'start',at(t));
const end=(f,e,s,t)=>f.w.action({requestId:randomUUID(),sessionId:s.id},e,'end',at(t));
const sale=(f,time,amount,method)=>f.a.create({requestId:randomUUID(),equipment:'sup',quantity:1,name:'Гость',phone:'79001234567',departed:day+'T'+time,amount,method},u,at(time));
const sales8m=f=>{sale(f,'14:00','30000','cash');sale(f,'15:00','50000','card');};
const check=(name,fn)=>test(name,async()=>{const f=fixture();try{await fn(f);}finally{f.close();}});
check('Work: five staggered employees, shared snapshot, exact times and departures',f=>{const sessions=employees.map((e,i)=>start(f,e,`${10+i}:00`));end(f,employees[0],sessions[0],'18:30');assert.equal(f.w.snapshot(employees[1],day,at('19:00')).active.length,4);const c=f.w.calculate(day,at('19:00'),8000000);assert.equal(c.employees[0].worked_ms,8.5*3600000);assert.equal(c.employees.length,5);assert.equal(c.bonus_pool_cents,400000);assert.ok(c.employees.every(e=>e.salary_cents===330000));assert.equal(c.employees.reduce((n,e)=>n+e.bonus_cents,0),400000);});
check('Work: start/end are idempotent, including separate double-tap keys; cannot end another person',f=>{const b={requestId:randomUUID()},s=f.w.action(b,employees[0],'start',at('10:00'));assert.equal(f.w.action(b,employees[0],'start',at('11:00')).id,s.id);assert.equal(start(f,employees[0],'11:00').id,s.id);assert.throws(()=>end(f,employees[1],s,'12:00'),/свою/);assert.throws(()=>f.w.action({...b,userId:3},employees[0],'start',at('11:00')),/своей/);const e=end(f,employees[0],s,'12:00');assert.equal(end(f,employees[0],s,'13:00').ended_at,e.ended_at);const next=start(f,employees[0],'14:00');end(f,employees[0],s,'15:00');assert.equal(f.w.snapshot(employees[0],day,at('15:00')).own.id,next.id);});
check('Work: hourly and proportional bonus conserve every kopeck',f=>{f.w.saveSettings({revision:0,fixedCents:250000,hourlyCents:10000,bonusPercent:5,payMode:'hourly',distribution:'hours'},u,at('08:00'));const s=start(f,employees[0],'10:00'),t=start(f,employees[1],'11:00');end(f,employees[0],s,'12:00');end(f,employees[1],t,'12:00');const c=f.w.calculate(day,at('13:00'),100020);assert.equal(c.employees[0].fixed_cents,20000);assert.equal(c.employees[1].fixed_cents,10000);assert.equal(c.bonus_pool_cents,5001);assert.deepEqual(c.employees.map(e=>e.bonus_cents),[3334,1667]);assert.deepEqual(distribute(1,[{user_id:2},{user_id:3}],'equal'),[1,0]);});
check('Work: day settings freeze; cash withdrawal restores revenue; final snapshot and payment guard',f=>{const s=start(f,employees[0],'10:00');const id=f.a.openShift({day,cashStartCents:1000000,employeeIds:[2]},u,at('10:01'));f.a.addWithdrawal({shiftId:id,amountCents:2000000,comment:'Директор'},u,at('12:00'));assert.throws(()=>f.a.pay({shiftId:id,userId:2,amountCents:1},u,at('12:00')),/после закрытия|после сохранения итога/);f.w.saveSettings({revision:0,fixedCents:999999,hourlyCents:0,bonusPercent:10,payMode:'fixed',distribution:'equal'},u,at('13:00'));sales8m(f);assert.throws(()=>f.a.closeShift({shiftId:id,cashEndCents:2000000,cashlessCents:0},u,at('20:00')),/Ушёл/);end(f,employees[0],s,'20:00');const r=f.a.closeShift({shiftId:id,cashEndCents:2000000,cashlessCents:5000000},u,at('21:00'));assert.equal(r.cash_revenue_cents,3000000);assert.equal(r.total_revenue_cents,8000000);assert.equal(r.employees[0].fixed_cents,250000);assert.equal(r.employees[0].salary_cents,650000);assert.ok(JSON.parse(r.employees[0].calculation_json).employee.sessions.length);assert.equal(f.a.pay({shiftId:id,userId:2,amountCents:650000},u,at('21:05'))[0].remaining_cents,0);assert.throws(()=>f.a.pay({shiftId:id,userId:2,amountCents:1},u),/больше/);});
check('Work: correction permission, optimistic version, overlap and audit',f=>{const s=start(f,employees[0],'10:00');end(f,employees[0],s,'12:00');const b={id:s.id,revision:1,startedAt:at('10:30'),endedAt:at('12:00'),reason:'Уточнение прихода'};assert.throws(()=>f.w.correct(b,employees[0],at('15:00')),/администратору/);f.w.correct(b,u,at('15:00'));assert.equal(f.w.calculate(day,at('15:00')).employees[0].worked_ms,5400000);assert.throws(()=>f.w.correct(b,u,at('15:00')),/изменено/);const log=f.w.history(u,day,at('15:00')).audit[0];assert.equal(log.reason,b.reason);assert.equal(JSON.parse(log.before_json).started_at,at('10:00'));assert.equal(JSON.parse(log.after_json).started_at,at('10:30'));});
check('Work: 22:00 report includes still active employee, honours configured recipient, dedupes',async f=>{for(const e of employees)start(f,e,'10:00');f.a.saveTelegramSettings({enabled:true,ownerChatId:'-12345'},u);await f.w.tick(at('21:59'));assert.equal(f.messages.length,0);await Promise.all([f.w.tick(at('22:00')),f.w.tick(at('22:00'))]);assert.equal(f.messages.length,1);assert.match(f.messages[0].text,/ещё на смене/);assert.match(f.messages[0].text,/12.00 ч/);assert.match(f.messages[0].text,/ivan/);assert.match(f.messages[0].text,/oleg/);assert.equal(f.messages[0].chat_id,'-12345');assert.match(f.messages[0].reply_markup.inline_keyboard[0][0].url,/admin\/workforce/);await f.w.tick(at('22:05'));assert.equal(f.messages.length,1);});
check('Work: late worker reconstructs 22:00, never invents end at 22 for a 23:00 departure',async f=>{const s=start(f,employees[0],'10:00');end(f,employees[0],s,'23:00');await f.w.tick(at('23:05'));const snap=JSON.parse(f.a.db.prepare('SELECT snapshot_json FROM daily_work_reports').get().snapshot_json);assert.equal(snap.employees[0].active,true);assert.equal(snap.employees[0].worked_ms,12*3600000);assert.match(f.messages[0].text,/ещё на смене/);});
test('Work: sessions, settings, salary and notification claims survive restart',async()=>{const dir=mkdtempSync(join(tmpdir(),'start-work-')),file=join(dir,'test.sqlite');let f=fixture(file);try{start(f,employees[0],'10:00');await f.w.tick(at('22:00'));f.close();f=fixture(file);assert.equal(f.w.snapshot(employees[0],day,at('22:30')).own.started_at,at('10:00'));await f.w.tick(at('22:30'));assert.equal(f.messages.length,0);}finally{f.close();rmSync(dir,{recursive:true,force:true});}});
check('Work: uncertain Telegram result never retries blindly or leaks secrets',async f=>{start(f,employees[0],'10:00');f.w.request=async()=>{throw Error('fake secret token');};await f.w.tick(at('22:00'));const r=f.a.db.prepare('SELECT * FROM daily_work_reports').get();assert.equal(r.status,'unknown');assert.doesNotMatch(r.last_error,/secret/);f.w.request=async()=>{assert.fail('Must not send twice');};await f.w.tick(at('22:01'));});
check('Work: new personal login uses the existing authentication',f=>{f.w.savePerson({name:'Иван Петров',login:'ivan_new',password:'test-only-password',role:'staff'},u);const token=f.a.login({login:'ivan_new',password:'test-only-password'},'test');assert.equal(f.a.user(token).role,'staff');assert.throws(()=>f.w.savePerson({name:'Чужой'},employees[0]),/администратору/);});
function cafe(f){const c=new CafeStore(f.a,new SmsStore(f.a,null,{}),{env:{}}),item=c.catalog().items.find(i=>/пеперони/i.test(i.name))||c.catalog().items[0],inventory=c.stock.inventory,stock=inventory.catalog(u).items.find(i=>/пеперони/i.test(i.name))||inventory.catalog(u).items[0];inventory.move({id:stock.id,revision:stock.revision,requestId:randomUUID(),kind:'SET',reason:'Проверочный пересчёт',amount:'3'},u);c.stock.save({itemId:item.id,component:'base',revision:-1,ingredients:[{id:stock.id,amount:'1'}]},u);const body=quantity=>({requestId:randomUUID(),name:'Гость',fulfillment:'pickup',payment:'cash',items:[{itemId:item.id,quantity}],expectedTotalCents:item.priceCents*quantity});return {c,item,inventory,stock,body};}
check('Stock: pizza 3 cannot sell 4, can sell 3, cannot sell at zero; rollback preserves orders',f=>{const {c,stock,body}=cafe(f);assert.throws(()=>c.create(body(4),u,'test',at('14:00')),e=>e.available===3);assert.equal(f.a.db.prepare('SELECT count(*) n FROM cafe_orders').get().n,0);const b=body(3),r=c.create(b,u,'test',at('14:00'));assert.equal(c.create(b,u,'test',at('14:00')).id,r.id);assert.equal(c.stock.inventory.row(stock.id).current_milli,0);assert.throws(()=>c.create(body(1),u,'test',at('14:00')),e=>e.available===0);assert.equal(c.publicMenu().items.find(i=>i.id===b.items[0].itemId).stock.available,0);});
check('Stock: cancellation restores once before cooking, prepared cancellation does not restore',f=>{const {c,stock,body}=cafe(f);const r=c.create(body(2),u,'test',at('14:00'));c.status({id:r.id,revision:0,status:'CANCELLED'},u,at('14:01'));c.status({id:r.id,revision:0,status:'CANCELLED'},u,at('14:02'));assert.equal(c.stock.inventory.row(stock.id).current_milli,3000);let b=c.order(c.create(body(1),u,'test',at('14:03')).id,u);for(const status of ['ACCEPTED','COOKING','CANCELLED'])b=c.status({id:b.id,revision:b.revision,status},u,at('14:04'));assert.equal(c.stock.inventory.row(stock.id).current_milli,2000);const h=c.stock.inventory.history(new URLSearchParams('type=RETURN'),u);assert.equal(h.items.length,1);});
check('Stock: missing recipes, unknown stock, modifiers, unit change and insufficient combined cart fail closed',f=>{const {c,stock,item,body}=cafe(f);const unknown=c.catalog().items.find(i=>i.id!==item.id&&!i.variants.length&&!i.restricted);assert.throws(()=>c.stock.check([{itemId:unknown.id,name:unknown.name,quantity:1}]),/не настроен/);assert.throws(()=>c.stock.check([{itemId:item.id,name:item.name,quantity:1,modifiers:[{optionId:'missing'}]}]),/не настроен/);f.a.db.prepare('UPDATE inventory_items SET current_milli=NULL WHERE id=?').run(stock.id);assert.throws(()=>c.create(body(1),u,'test',at('14:00')),e=>e.stockCode==='UNCONFIGURED');f.a.db.prepare('UPDATE inventory_items SET current_milli=3000 WHERE id=?').run(stock.id);const b=body(2);b.items.push({...b.items[0]});b.expectedTotalCents*=2;assert.throws(()=>c.create(b,u,'test',at('14:00')),/доступно/);assert.throws(()=>c.stock.save({itemId:item.id},employees[0]),/admin/);});
test('Stock: two simultaneous POS connections cannot oversell last portions',async()=>{const dir=mkdtempSync(join(tmpdir(),'start-stock-')),file=join(dir,'test.sqlite');const f=fixture(file);try{const {body,stock}=cafe(f);const workerCode=`const {parentPort,workerData}=require('node:worker_threads');(async()=>{const {AdminStore}=await import(workerData.admin),{CafeStore}=await import(workerData.cafe),{SmsStore}=await import(workerData.sms);const a=new AdminStore(workerData.file),c=new CafeStore(a,new SmsStore(a,null,{}),{env:{}});parentPort.postMessage('ready');parentPort.once('message',()=>{try{c.create(workerData.body,{id:1,role:'admin'},'test',workerData.now);parentPort.postMessage('sold');}catch(e){parentPort.postMessage(e.stockCode||e.message);}finally{a.close();}});})();`;const workers=Array.from({length:2},()=>new Worker(workerCode,{eval:true,workerData:{file,body:body(2),now:at('14:00'),admin:new URL('./admin.mjs',import.meta.url).href,cafe:new URL('./cafe.mjs',import.meta.url).href,sms:new URL('./sms.mjs',import.meta.url).href}}));await Promise.all(workers.map(w=>new Promise((r,j)=>{w.once('message',r);w.once('error',j);})));const results=await Promise.all(workers.map(w=>new Promise((r,j)=>{w.once('message',r);w.once('error',j);w.postMessage('go');})));assert.deepEqual(results.sort(),['INSUFFICIENT','sold']);assert.equal(f.a.db.prepare('SELECT current_milli FROM inventory_items WHERE id=?').get(stock.id).current_milli,1000);await Promise.all(workers.map(w=>w.terminate()));}finally{f.close();rmSync(dir,{recursive:true,force:true});}});
check('Work HTTP: auth, own identity and CSRF are enforced',async f=>{const handler=workforceHandler(f.w,f.a,'http://localhost');const server=http.createServer(async(req,res)=>handler(req,res,new URL(req.url,'http://localhost')));await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const base='http://127.0.0.1:'+server.address().port;const r=await fetch(base+'/api/admin/workforce/current');assert.equal(r.status,401);}finally{await new Promise(r=>server.close(r));}});
check('Work HTTP: employee cannot change another session/settings; same identity across devices',async f=>{const token='isolated-session',hash=createHash('sha256').update(token).digest('hex');f.a.db.prepare('INSERT INTO admin_sessions VALUES(?,?,?)').run(hash,2,Date.now()+60000);const server=http.createServer(async(req,res)=>workforceHandler(f.w,f.a,'http://localhost')(req,res,new URL(req.url,'http://localhost')));await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const base='http://127.0.0.1:'+server.address().port,headers={Cookie:'__Host-start_session='+token,'Content-Type':'application/json',Origin:'http://localhost'},post=(p,b,h=headers)=>fetch(base+'/api/admin/workforce/'+p,{method:'POST',headers:h,body:JSON.stringify(b)});assert.equal((await post('start',{requestId:randomUUID()},{...headers,Origin:'http://wrong.test'})).status,403);assert.equal((await post('start',{requestId:randomUUID(),userId:3})).status,403);assert.equal((await post('settings',{})).status,403);assert.equal((await post('start',{requestId:randomUUID()})).status,200);const read=()=>fetch(base+'/api/admin/workforce/current',{headers}).then(r=>r.json());const one=await read(),two=await read();assert.equal(one.own.id,two.own.id);assert.equal((await post('end',{requestId:randomUUID(),sessionId:one.own.id})).status,200);assert.equal((await read()).own,null);}finally{await new Promise(r=>server.close(r));}});
check('Work: a new cashier shift cannot fabricate another employee attendance',f=>{start(f,employees[0],'10:00');f.a.openShift({day,cashStartCents:0,employeeIds:[2,3,4,5,6]},u,at('10:01'));assert.deepEqual(f.w.calculate(day,at('11:00'),8000000).employees.map(e=>e.user_id),[2]);});
check('Work: recorded cash and delivered cafe revenue change preliminary earnings once',f=>{start(f,employees[0],'10:00');const {c,body}=cafe(f);const rental=f.a.create({requestId:randomUUID(),equipment:'sup',quantity:1,name:'Тест',phone:'+79001234567',departed:day+'T12:00',amount:'1000',method:'cash'},u,at('12:00'));assert.ok(rental);assert.equal(f.w.calculate(day,at('12:01')).employees[0].salary_cents,255000);let order=c.order(c.create(body(1),u,'test',at('12:02')).id,u);assert.equal(f.w.calculate(day,at('12:03')).employees[0].salary_cents,255000);for(const status of ['ACCEPTED','COOKING','READY','DELIVERED'])order=c.status({id:order.id,status,revision:order.revision},u,at('12:04'));assert.equal(f.w.calculate(day,at('12:05')).revenue.cents,100000+order.total_cents);assert.equal(f.w.calculate(day,at('12:05')).employees[0].salary_cents,255000+order.total_cents*0.05);});
check('Work: correcting hourly closed shift recalculates and audits without altering applied settings',f=>{f.w.saveSettings({revision:0,payMode:'hourly',hourlyCents:10000,fixedCents:250000,bonusPercent:5,distribution:'hours'},u,at('08:00'));const s=start(f,employees[0],'10:00');end(f,employees[0],s,'12:00');const id=f.a.openShift({day,cashStartCents:0,employeeIds:[2]},u,at('12:01'));f.a.closeShift({shiftId:id,cashEndCents:100000,cashlessCents:0},u,at('12:02'));f.w.correct({id:s.id,revision:1,startedAt:at('10:30'),endedAt:at('12:00'),reason:'Точное время'},u,at('13:00'));assert.equal(f.a.shiftDetails(id).employees[0].salary_cents,15000);assert.ok(f.w.history(u,day,at('13:00')).audit.some(a=>a.action==='salary_recalculate'));});

check('Work: admin can grant full role and existing sessions immediately reflect it; audit excludes passwords',f=>{
 const people=f.w.savePerson({name:'Мэтт',login:'matt',password:'test-matt-password',role:'waiter'},u),m=people.find(p=>p.login==='matt');
 const token=f.a.login({login:'matt',password:'test-matt-password'},'test');assert.equal(f.a.user(token).role,'waiter');
 assert.throws(()=>f.w.savePerson({id:m.id,name:'Мэтт',role:'admin',expectedRole:'waiter'},f.a.user(token)),e=>e.status===403);
 f.w.savePerson({id:m.id,name:'Мэтт',role:'admin',expectedRole:'waiter'},u);
 assert.equal(f.a.user(token).role,'admin');assert.equal(f.w.snapshot(f.a.user(token)).canEdit,true);
 const log=f.a.db.prepare("SELECT * FROM financial_audit_log WHERE action='employee_role'").get();assert.equal(JSON.parse(log.before_json).role,'waiter');assert.equal(JSON.parse(log.after_json).role,'admin');assert.doesNotMatch(JSON.stringify(log),/password|scrypt|test-matt/);
 assert.throws(()=>f.w.savePerson({id:m.id,name:'Мэтт',role:'staff',expectedRole:'waiter'},u),e=>e.status===409);
 f.w.savePerson({id:m.id,name:'Мэтт',role:'staff',expectedRole:'admin'},u);assert.equal(f.a.user(token).role,'staff');
 assert.throws(()=>f.w.savePerson({id:1,name:'Владелец',role:'staff',expectedRole:'admin'},u),/последнего/);
 f.w.savePerson({id:1,name:'Владелец'},u);assert.equal(f.w.people().find(p=>p.id===1).role,'admin');
});
check('Work: invalid roles are rejected and new full administrators use normal login',f=>{
 assert.throws(()=>f.w.savePerson({name:'Ошибка',login:'bad',password:'test-person-password',role:'superuser'},u),/роль/);
 f.w.savePerson({name:'Администратор',login:'second',password:'test-admin-password',role:'admin'},u);
 assert.equal(f.a.user(f.a.login({login:'second',password:'test-admin-password'},'test')).role,'admin');
});

check('Work: 2500 per 12 hours is exact; round once after worked time is summed',f=>{
 const settings={pay_mode:'prorated',fixed_cents:250000,full_shift_minutes:720};
 for(const [ms,cents] of [[0,0],[1,0],[60000,347],[3600000,20833],[6*3600000,125000],[12*3600000,250000],[13*3600000,270833]])assert.equal(basePayCents(settings,ms),cents);
 f.w.saveSettings({revision:0,fixedCents:250000,hourlyCents:0,fullShiftMinutes:720,bonusPercent:5,payMode:'prorated',distribution:'hours'},u,at('08:00'));
 let s=start(f,employees[0],'11:00');end(f,employees[0],s,'11:30');s=start(f,employees[0],'20:00');end(f,employees[0],s,'20:30');
 assert.equal(f.w.calculate(day,at('21:00'),0).employees[0].fixed_cents,20833);
});
check('Work: 11 and 20 starts receive time-weighted base and bonus; closed snapshot stays fixed',f=>{
 const rules={revision:0,fixedCents:250000,hourlyCents:0,fullShiftMinutes:720,bonusPercent:5,payMode:'prorated',distribution:'hours'};
 f.w.saveSettings(rules,u,at('08:00'));const first=start(f,employees[0],'11:00'),late=start(f,employees[1],'20:00');
 const shift=f.a.openShift({day,cashStartCents:0,employeeIds:[2,3]},u,at('20:01'));sales8m(f);end(f,employees[0],first,'23:00');end(f,employees[1],late,'23:00');
 const c=f.w.calculate(day,at('23:01'));assert.deepEqual(c.employees.map(e=>[e.fixed_cents,e.bonus_cents,e.salary_cents]),[[250000,320000,570000],[62500,80000,142500]]);
 assert.equal(c.employees.reduce((n,e)=>n+e.bonus_cents,0),400000);
 f.a.closeShift({shiftId:shift,cashEndCents:3000000,cashlessCents:5000000},u,at('23:02'));
 f.w.saveSettings({...rules,revision:1,fixedCents:999999,fullShiftMinutes:600},u,at('23:03'));
 const closed=f.w.calculate(day,at('23:04'));assert.equal(closed.settings.full_shift_minutes,720);assert.equal(closed.settings.fixed_cents,250000);assert.deepEqual(closed.employees.map(e=>e.salary_cents),[570000,142500]);assert.match(f.w.reportText(closed),/за 12 ч/);
});
check('Work: full shift duration validates and legacy setting requests preserve the duration',f=>{
 const rules={revision:0,fixedCents:250000,hourlyCents:0,fullShiftMinutes:720,bonusPercent:5,payMode:'prorated',distribution:'hours'};
 for(const fullShiftMinutes of [0,-1,0.5,1441,null,'720'])assert.throws(()=>f.w.saveSettings({...rules,fullShiftMinutes},u));
 assert.equal(f.w.settings().revision,0);assert.throws(()=>f.w.saveSettings(rules,employees[0]),e=>e.status===403);
 f.w.saveSettings({...rules,fullShiftMinutes:600},u);const {fullShiftMinutes,...oldClient}=rules;f.w.saveSettings({...oldClient,revision:1,payMode:'fixed'},u);assert.equal(f.w.settings().full_shift_minutes,600);
});
test('Work: existing salary settings migrate once without changing old day snapshots',()=>{
 const dir=mkdtempSync(join(tmpdir(),'start-salary12-')),file=join(dir,'test.sqlite');let f=fixture(file);
 try{
  const old={...f.w.settings()};delete old.full_shift_minutes;
  f.a.db.prepare('INSERT INTO work_day_settings(day,settings_json,created_at) VALUES(?,?,?)').run(day,JSON.stringify(old),at('08:00'));
  f.a.db.exec('ALTER TABLE salary_settings DROP COLUMN full_shift_minutes');f.close();f=fixture(file);
  assert.equal(f.w.settings().full_shift_minutes,720);assert.equal(f.w.settings().pay_mode,'fixed');
  assert.deepEqual(f.w.daySettings(day),old);
  f.w.saveSettings({revision:0,fixedCents:250000,hourlyCents:0,fullShiftMinutes:720,bonusPercent:5,payMode:'prorated',distribution:'hours'},u,at('09:00'));
  const session=start(f,employees[0],'11:00');end(f,employees[0],session,'12:00');assert.equal(f.w.calculate(day,at('13:00'),0).employees[0].fixed_cents,250000);
  f.close();f=fixture(file);assert.equal(f.w.settings().pay_mode,'prorated');assert.equal(f.w.settings().full_shift_minutes,720);assert.equal(f.w.settings().revision,1);assert.deepEqual(f.w.daySettings(day),old);
 }finally{f.close();rmSync(dir,{recursive:true,force:true});}
});
