import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import http from 'node:http';
import {Worker} from 'node:worker_threads';
import {AdminStore} from './admin.mjs';
import {CafeStore} from './cafe.mjs';
import {SmsStore} from './sms.mjs';
import {PrintStore,printHandler,canonical,payloadHash,rubles} from './print.mjs';

const date='2026-09-25',at=t=>Date.parse(date+'T'+t+':00+03:00'),u={id:1,role:'admin'},employee={id:2,role:'staff'},env={PRINT_ENABLED:'true',PRINT_AGENT_TOKEN:'test-print-token-'.repeat(4),PRINT_AGENT_DATABASE_ID:'test-database',PRINT_AGENT_ID:'station-printer-1'};
function fixture(file=':memory:'){
 const a=new AdminStore(file);if(!a.configured())a.db.exec("INSERT INTO admin_users VALUES(1,'admin','admin','unused'),(2,'ivan','staff','unused'),(3,'anna','waiter','unused')");
 const p=new PrintStore(a,{env:{...env}});a.printStore=p;return {a,p,close:()=>a.close()};
}
const check=(name,fn)=>test('Print: '+name,async()=>{const f=fixture();try{await fn(f);}finally{f.close();}});
function shift(f,{closed=true,day=date}={}){const start=f.a.workforce.action({requestId:randomUUID()},employee,'start',at('10:00')),id=f.a.openShift({day,cashStartCents:1000000,employeeIds:[2]},u,at('10:01'));if(closed){f.a.addWithdrawal({shiftId:id,amountCents:2000000,comment:'Директор'},u,at('12:00'));f.a.workforce.action({requestId:randomUUID(),sessionId:start.id},employee,'end',at('20:00'));f.a.closeShift({shiftId:id,cashEndCents:2000000,cashlessCents:5000000},u,at('21:00'));}return id;}
function receipt(f){shift(f);return f.p.report({},u,at('21:10')).job;}
function event(job,status='received',sequence=1){return {event_id:randomUUID(),job_id:job.id,attempt_id:'attempt-'+job.id,sequence,status,payload_hash:job.payload_hash,occurred_at:new Date().toISOString(),cups_id:null};}
function cafe(f){const c=new CafeStore(f.a,new SmsStore(f.a,null,{}),{env:{}}),item=c.catalog().items.find(i=>/пеперони/i.test(i.name))||c.catalog().items[0],stock=c.stock.inventory.catalog(u).items.find(i=>/пеперони/i.test(i.name))||c.stock.inventory.catalog(u).items[0];c.stock.inventory.move({id:stock.id,revision:stock.revision,requestId:randomUUID(),kind:'SET',amount:'20'},u);c.stock.save({itemId:item.id,component:'base',revision:-1,ingredients:[{id:stock.id,amount:'1'}]},u);const body={requestId:randomUUID(),name:'Гость',fulfillment:'pickup',payment:'cash',items:[{itemId:item.id,quantity:1}],expectedTotalCents:item.priceCents};return {c,item,stock,body};}

check('kopecks convert to exact decimal rubles and canonical fixture matches Python',()=>{assert.equal(rubles(8000000),'80000.00');assert.equal(rubles(1),'0.01');assert.equal(rubles(-101),'-1.01');assert.throws(()=>rubles(1.5));const f=JSON.parse(readFileSync(new URL('../start-print-agent/examples/protocol-fixture.json',import.meta.url)));assert.equal(canonical(f.payload),f.canonical);assert.equal(payloadHash(f.payload),f.sha256);});
check('final report uses saved cash total, subtracts paid only for this shift',f=>{const id=shift(f);f.a.pay({shiftId:id,userId:2,amountCents:50000},u,at('21:01'));const r=f.p.report({},u,at('21:02')).job;assert.equal(r.payload.total,'80000.00');assert.deepEqual(r.payload.transfers,[{recipient:'ivan',amount:'6000.00'}]);assert.equal(r.snapshot.employees[0].salaryCents,650000);assert.equal(r.payload.preliminary,false);assert.equal(f.a.db.prepare('SELECT count(*) n FROM payroll_payments').get().n,1);});
check('fully paid shift has no transfers; print never closes shift or makes payments',f=>{const id=shift(f);f.a.pay({shiftId:id,userId:2,amountCents:650000},u,at('21:01'));assert.deepEqual(f.p.report({},u,at('21:02')).job.payload.transfers,[]);assert.equal(f.a.db.prepare('SELECT count(*) n FROM payroll_payments').get().n,1);});
check('12-hour base uses the saved exact wage in print transfers without duplicate jobs',f=>{f.a.workforce.saveSettings({revision:0,fixedCents:250000,hourlyCents:0,fullShiftMinutes:720,bonusPercent:5,payMode:'prorated',distribution:'hours'},u,at('08:00'));shift(f);const first=f.p.report({},u,at('21:02')).job;assert.equal(first.snapshot.employees[0].salaryCents,608333);assert.deepEqual(first.payload.transfers,[{recipient:'ivan',amount:'6083.33'}]);assert.equal(f.p.report({},u,at('21:03')).job.id,first.id);});
check('preliminary report uses existing live formula, final is separate, repeated clicks reuse snapshot',f=>{const id=shift(f,{closed:false});const p=f.p.report({},u,at('11:00')),again=f.p.report({},u,at('12:00'));assert.equal(p.job.payload.preliminary,true);assert.equal(p.job.payload.total,'0.00');assert.equal(p.job.id,again.job.id);assert.equal(f.a.currentShift(date).closed_at,null);const s=f.a.workforce.snapshot(employee,date,at('20:00')).own;f.a.workforce.action({requestId:randomUUID(),sessionId:s.id},employee,'end',at('20:00'));f.a.closeShift({shiftId:id,cashEndCents:2000000,cashlessCents:0},u,at('21:00'));const fin=f.p.report({},u,at('21:01'));assert.notEqual(fin.job.id,p.job.id);assert.equal(fin.job.payload.total,'10000.00');assert.equal(fin.job.payload.preliminary,false);});
check('latest shift fallback ignores future days and old debts',f=>{const id=shift(f);f.a.db.prepare("INSERT INTO shifts(day,opened_at,opened_by,cash_start_cents,closed_at,closed_by,total_revenue_cents,bonus_pool_cents) VALUES('2026-09-24',?,1,0,?,1,999999,0)").run(at('09:00'),at('09:01'));const old=f.a.db.prepare("SELECT id FROM shifts WHERE day='2026-09-24'").get().id;f.a.db.prepare('INSERT INTO shift_employees VALUES(?,?,250000,0,250000,NULL,NULL)').run(old,2);assert.equal(f.p.reportSnapshot(undefined,at('22:00')).shiftId,id);assert.equal(f.p.report({},u,at('22:01')).job.payload.transfers[0].amount,'6500.00');assert.equal(f.p.reportSnapshot(undefined,at('22:00')+86400000).shiftId,id);});
check('new revision is explicit and idempotent against the previous document',f=>{const first=receipt(f);f.a.pay({shiftId:first.snapshot.shiftId,userId:2,amountCents:10000},u,at('21:11'));assert.equal(f.p.report({},u,at('21:12')).job.payload.transfers[0].amount,'6500.00');const b={newRevision:true,previousDocumentId:first.document_id,reason:'Учтена выплата'},second=f.p.report(b,u,at('21:13'));assert.equal(second.job.payload.transfers[0].amount,'6400.00');assert.equal(second.job.payload.revision,2);assert.equal(f.p.report(b,u,at('21:14')).job.id,second.job.id);assert.equal(f.p.job(first.id).payload.transfers[0].amount,'6500.00');});
check('poll redelivers until ACK, events deduplicate and cannot regress state',f=>{const j=receipt(f);assert.equal(f.p.poll(at('21:11')).jobs[0].job_id,j.id);assert.equal(f.p.poll(at('21:12')).jobs[0].job_id,j.id);const a=event(j),b=event(j,'printed',3);f.p.events({events:[b]},at('21:13'));f.p.events({events:[a]},at('21:14'));assert.equal(f.p.job(j.id).status,'printed');assert.deepEqual(f.p.events({events:[a]}).accepted_event_ids,[a.event_id]);assert.equal(f.p.poll().jobs.length,0);assert.throws(()=>f.p.events({events:[{...a,status:'failed'}]}),/conflict/);assert.throws(()=>f.p.events({events:[event(j,'printing',4)]}),/transition/);});
check('unoffered, wrong hash and wrong attempt events are rejected',f=>{const j=receipt(f),e=event(j);assert.throws(()=>f.p.events({events:[e]}),/conflict/);f.p.poll(at('21:11'));assert.throws(()=>f.p.events({events:[{...e,payload_hash:'wrong'}]}),/conflict/);f.p.events({events:[e]});assert.throws(()=>f.p.events({events:[{...event(j,'printed',2),attempt_id:'other'}]}),/conflict/);});
check('manual reprint has one stable command across tabs and retries, with audit',f=>{const j=receipt(f);assert.throws(()=>f.p.reprint({jobId:j.id,reason:'Не вышел'},u),/Дождитесь/);f.p.poll();f.p.events({events:[event(j,'failed')]});const r=f.p.reprint({jobId:j.id,reason:'Принтер проверен'},u),r2=f.p.reprint({jobId:j.id,reason:'Повтор запроса'},u);assert.equal(r.job.id,r2.job.id);assert.equal(r.job.payload_hash,j.payload_hash);assert.equal(r.job.operation,'reprint');assert.equal(f.a.db.prepare("SELECT count(*) n FROM print_audit WHERE action='reprint'").get().n,1);});
check('roles, paired DB and bearer token are enforced without exposing token',f=>{assert.throws(()=>f.p.report({},employee),e=>e.status===403);assert.throws(()=>f.p.reportInfo({id:3,role:'waiter'}),e=>e.status===403);const headers={authorization:'Bearer '+env.PRINT_AGENT_TOKEN,'x-print-agent-id':env.PRINT_AGENT_ID,'x-print-database-id':env.PRINT_AGENT_DATABASE_ID};assert.doesNotThrow(()=>f.p.authorize({headers}));assert.throws(()=>f.p.authorize({headers:{...headers,'x-print-database-id':'new-empty-db'}}),e=>e.status===409);assert.throws(()=>f.p.authorize({headers:{...headers,authorization:'wrong'}}),e=>e.status===401);assert.ok(!JSON.stringify(f.p.device()).includes(env.PRINT_AGENT_TOKEN));});
check('cafe NEW and ADD produce distinct immutable tickets, duplicate create does not reprint',f=>{const {c,item,body}=cafe(f),r=c.create(body,u,'test',at('12:00'));c.create(body,u,'test',at('12:01'));const first=f.p.cafeJobs(r.id,u).jobs[0];assert.equal(first.payload.order_source,'admin');assert.equal(first.payload.items.length,1);assert.equal(first.payload.items[0].price,rubles(item.priceCents));assert.equal(first.payload.fulfillment,'Заберут в кафе');const b={id:r.id,revision:r.revision,requestId:randomUUID(),items:body.items,expectedTotalCents:item.priceCents};c.append(b,u,at('12:02'));c.append(b,u,at('12:03'));const jobs=f.p.cafeJobs(r.id,u).jobs;assert.equal(jobs.length,2);assert.equal(jobs[1].payload.ticket_kind,'ADD');assert.equal(jobs[1].payload.items.length,1);assert.equal(jobs[1].payload.total,first.payload.total);assert.ok(!('phone' in first.payload));});
check('cancel before delivery removes queued ticket, after offered emits cancellation',f=>{const {c,body}=cafe(f),r=c.create(body,u,'test',at('12:00'));c.status({id:r.id,revision:r.revision,status:'CANCELLED'},u);assert.equal(f.p.cafeJobs(r.id,u).jobs[0].status,'cancelled');assert.equal(f.p.poll().jobs.length,0);const next=c.create({...body,requestId:randomUUID()},u,'test',at('12:01'));f.p.poll();c.status({id:next.id,revision:next.revision,status:'CANCELLED'},u);const jobs=f.p.cafeJobs(next.id,u).jobs;assert.equal(jobs.length,2);assert.equal(jobs[1].payload.ticket_kind,'CANCELLED');});
check('queue failure rolls back cafe order and stock consumption',f=>{const {c,body,stock}=cafe(f);const before=c.stock.inventory.row(stock.id).current_milli;f.p.enqueue=()=>{throw Error('queue unavailable');};assert.throws(()=>c.create(body,u,'test',at('12:00')),/queue unavailable/);assert.equal(f.a.db.prepare('SELECT count(*) n FROM cafe_orders').get().n,0);assert.equal(c.stock.inventory.row(stock.id).current_milli,before);});
check('disabled integration does not backfill historical orders',f=>{const {c,body}=cafe(f);f.p.env.PRINT_ENABLED='false';const r=c.create(body,u,'test',at('12:00'));f.p.env.PRINT_ENABLED='true';c.create(body,u,'test',at('12:00'));assert.equal(f.p.cafeJobs(r.id,u).jobs.length,0);assert.equal(f.p.poll().jobs.length,0);});
check('place correction has its own deduplicated ticket and cannot change the original order snapshot',f=>{const {c,body}=cafe(f),r=c.create({...body,fulfillment:'lounge'},u,'test',at('12:00')),original=f.p.cafeJobs(r.id,u).jobs[0],b={id:r.id,revision:0,requestId:randomUUID(),location:'Стол 12'};c.location(b,u,at('12:02'));c.location(b,u,at('12:03'));const current=c.order(r.id,u);c.location({...b,revision:current.revision,requestId:randomUUID()},u,at('12:04'));const jobs=f.p.cafeJobs(r.id,u).jobs;assert.equal(jobs.length,2);assert.equal(jobs[1].payload.ticket_kind,'LOCATION');assert.equal(jobs[1].payload.total,'0.00');assert.equal(jobs[1].payload.items.length,0);assert.match(jobs[1].payload.comment,/Стол 12/);assert.equal(jobs[0].payload_hash,original.payload_hash);});

check('cafe ticket preserves all allowed modifiers and the full customer comment',f=>{
 const {c,body}=cafe(f),comment='а'.repeat(399)+'Я',r=c.create({...body,location:'Причал '+ 'б'.repeat(150),comment},u,'test',at('12:00'));
 const first=f.p.cafeJobs(r.id,u).jobs[0];assert.ok(first.payload.comment.endsWith(comment));assert.ok(first.payload.comment.length>500);
 const item={...r.details.items[0],variant:{name:'Вариант'},modifiers:Array.from({length:60},(_,i)=>({name:'Добавка '+i})),comment:'Без соли'};
 c.transaction(()=>c.event(r.id,'ADD',u,{items:[item],totalCents:item.totalCents},Date.now()));
 const last=f.p.cafeJobs(r.id,u).jobs.at(-1);assert.equal(last.payload.items[0].modifiers.length,62);assert.equal(last.payload.items[0].modifiers.at(-1),'Без соли');
});
test('Print: queue, snapshots and events persist across server restart',()=>{const dir=mkdtempSync(join(tmpdir(),'start-print-')),file=join(dir,'test.sqlite');let f=fixture(file);try{const j=receipt(f);f.p.poll();const e=event(j);f.p.events({events:[e]});f.close();f=fixture(file);assert.equal(f.p.report({},u,at('22:00')).job.id,j.id);assert.equal(f.p.job(j.id).status,'received');assert.equal(f.p.poll().jobs.length,0);assert.deepEqual(f.p.events({events:[e]}).accepted_event_ids,[e.event_id]);}finally{f.close();rmSync(dir,{recursive:true,force:true});}});
test('Print: concurrent report requests from four independent connections create one job',async()=>{const dir=mkdtempSync(join(tmpdir(),'start-print-concurrent-')),file=join(dir,'test.sqlite');const f=fixture(file);try{shift(f);const ids=await Promise.all(Array.from({length:4},()=>new Promise((resolve,reject)=>{const worker=new Worker(new URL('./testing/print-report-worker.mjs',import.meta.url),{workerData:{file,env,now:at('21:10')}});worker.once('message',resolve);worker.once('error',reject);worker.once('exit',code=>{if(code)reject(Error('worker exit '+code));});})));assert.equal(new Set(ids).size,1);assert.equal(f.a.db.prepare('SELECT count(*) n FROM print_jobs').get().n,1);}finally{f.close();rmSync(dir,{recursive:true,force:true});}});
check('HTTP auth, origin, body limits and status path',async f=>{receipt(f);const origin='https://spotsup.ru',handler=printHandler(f.p,f.a,origin);const server=http.createServer(async(req,res)=>{if(!await handler(req,res,new URL(req.url,origin))){res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;try{assert.equal((await fetch(base+'/api/print-agent/v1/jobs')).status,401);const headers={Authorization:'Bearer '+env.PRINT_AGENT_TOKEN,'X-Print-Agent-Id':env.PRINT_AGENT_ID,'X-Print-Database-Id':env.PRINT_AGENT_DATABASE_ID,'Content-Type':'application/json'};const r=await fetch(base+'/api/print-agent/v1/jobs',{headers});assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');assert.equal((await r.json()).jobs.length,1);assert.equal((await fetch(base+'/api/admin/print/report')).status,401);assert.equal((await fetch(base+'/api/print-agent/v1/events',{method:'POST',headers,body:'x'.repeat(262145)})).status,413);}finally{await new Promise(r=>server.close(r));}});
check('complimentary kitchen ticket is zero, labelled and printed once; stock is consumed once',f=>{
 const {c,body,stock}=cafe(f),before=c.stock.inventory.row(stock.id).current_milli;
 const b={...body,fulfillment:'lounge',location:'Стол 5',complimentary:{reason:'owner'},expectedTotalCents:0};
 const r=c.create(b,u,'test',at('12:00')),after=c.stock.inventory.row(stock.id).current_milli;
 assert.ok(after<before);c.create(b,u,'test',at('12:01'));assert.equal(c.stock.inventory.row(stock.id).current_milli,after);
 const jobs=f.p.cafeJobs(r.id,u).jobs;assert.equal(jobs.length,1);assert.match(jobs[0].payload.fulfillment,/БЕСПЛАТНО/);assert.match(jobs[0].payload.comment,/Стол 5/);assert.equal(jobs[0].payload.total,'0.00');assert.equal(jobs[0].payload.items[0].price,'0.00');
 c.status({id:r.id,revision:r.revision,status:'CANCELLED'},u,at('12:02'));assert.equal(c.stock.inventory.row(stock.id).current_milli,before);
});
check('public website order queues immediately before acceptance; acceptance never reprints',f=>{
 const {c,body}=cafe(f);f.a.workforce.action({requestId:randomUUID()},employee,'start',at('10:00'));
 const b={...body,phone:'+79000000000',consent:true};const r=c.create(b,null,'test-public',at('12:00'));
 assert.equal(r.status,'NEW');assert.equal(f.p.cafeJobs(r.id,u).jobs[0].payload.order_source,'site');assert.equal(f.p.cafeJobs(r.id,u).jobs.length,1);assert.equal(f.p.poll().jobs.length,1);
 c.create(b,null,'test-public',at('12:01'));c.status({id:r.id,revision:r.revision,status:'ACCEPTED'},u,at('12:02'));
 assert.equal(f.p.cafeJobs(r.id,u).jobs.length,1);
});
