import test from 'node:test';
import assert from 'node:assert/strict';
import {AdminStore} from './admin.mjs';
import {SmsStore,SmsService,phone} from './sms.mjs';

const now=Date.parse('2026-10-01T12:00:00+03:00');
function fixture(time='16:00'){
 const admin=new AdminStore(':memory:');admin.db.prepare('INSERT INTO admin_users(id,login,role,password) VALUES(1,?,?,?)').run('admin','admin','unused');
 const env={SMSAERO_EMAIL:'test@example.org',SMSAERO_API_KEY:'test-only',SMS_ENABLED:'true'};
 const sms=new SmsStore(admin,null,env),user={id:1,role:'admin'};
 sms.save({...sms.settings(),enabled:true},user);
 const b={name:'Анна',phone:'8 (903) 000-00-00',equipment:'sup',plan:'hour',date:'2026-10-01',time,quantity:1,duration:1};
 const id=admin.receive('test',b,now);admin.inquiryStatus({id,revision:0,status:'confirmed'},user,now);sms.sync(now);
 let sends=0;const messages=[];const service={send:async(number,text)=>{sends++;messages.push({number,text});return {ok:true,data:{id:sends,status:0}};},status:async()=>({ok:true,data:{status:1}})};
 return {admin,sms,id,user,service,messages,get sends(){return sends;},move(time,at=now){const r=admin.db.prepare('SELECT revision FROM inquiries WHERE id=?').get(id);sms.reschedule({id,revision:r.revision,date:'2026-10-01',time},user,at);},close(){admin.close();}};
}
test('1. More than one hour: due exactly one hour before start (Moscow)',async()=>{const f=fixture();try{assert.equal(f.sms.jobs(f.id)[0].due,Date.parse('2026-10-01T15:00:00+03:00'));await f.sms.tick(f.service,now);assert.equal(f.sends,0);await f.sms.tick(f.service,now+3*3600000);assert.equal(f.sends,1);}finally{f.close();}});
test('2. Less than an hour: immediately after confirmation',async()=>{const f=fixture('12:30');try{await f.sms.tick(f.service,now);assert.equal(f.sends,1);assert.equal(f.sms.jobs(f.id)[0].sent_at,now);}finally{f.close();}});
test('3. Cancel before sending',async()=>{const f=fixture();try{f.admin.inquiryStatus({id:f.id,revision:1,status:'cancelled'},f.user,now);await f.sms.tick(f.service,now+3*3600000);assert.equal(f.sends,0);assert.equal(f.sms.jobs(f.id)[0].cancel_reason,'cancelled');}finally{f.close();}});
test('4 & 14. Reschedule cancels original due job',async()=>{const f=fixture();try{f.move('18:00');await f.sms.tick(f.service,now+3*3600000);assert.equal(f.sends,0);assert.equal(f.sms.jobs(f.id)[1].cancel_reason,'rescheduled');await f.sms.tick(f.service,now+5*3600000);assert.equal(f.sends,1);assert.match(f.messages[0].text,/18:00/);}finally{f.close();}});
test('5. Move after old SMS sends changed-time notice immediately even >1h',async()=>{const f=fixture('12:30');try{await f.sms.tick(f.service,now);f.move('18:00',now+60000);await f.sms.tick(f.service,now+60000);assert.equal(f.sends,2);assert.match(f.messages[1].text,/время брони изменено.*18:00/);}finally{f.close();}});
test('6. Multiple moves including back to earlier slot keep only latest generation',async()=>{const f=fixture();try{f.move('18:00');f.move('17:00');f.move('16:00');await f.sms.tick(f.service,now+3*3600000);assert.equal(f.sends,1);assert.equal(f.sms.jobs(f.id).filter(j=>j.status==='cancelled').length,3);}finally{f.close();}});
test('7. Repeated and concurrent workers do not resend',async()=>{const f=fixture('12:30');try{await Promise.all([f.sms.tick(f.service,now),f.sms.tick(f.service,now)]);await f.sms.tick(f.service,now+1);assert.equal(f.sends,1);}finally{f.close();}});
test('8 & 9. Explicit provider rejection retries, retains attempts and last error',async()=>{const f=fixture('12:30');try{let n=0;const service={...f.service,send:async()=>++n===1?{ok:false,retry:true,error:'Temporary rejection'}:{ok:true,data:{id:17}}};await f.sms.tick(service,now);assert.equal(f.sms.jobs(f.id)[0].status,'retry');assert.equal(f.sms.jobs(f.id)[0].last_error,'Temporary rejection');await f.sms.tick(service,now+60000);assert.equal(f.sms.jobs(f.id)[0].status,'accepted');assert.equal(f.sms.jobs(f.id)[0].attempts,2);await f.sms.tick(service,now+120000);assert.equal(n,2);}finally{f.close();}});
test('10, 11, 12. Shared navigator/phone/late rule feed both scenarios',async()=>{const f=fixture('12:30');try{f.sms.content={live:()=>({phone:'+79991112233',inventory:[]})};f.sms.save({...f.sms.settings(),YANDEX_NAVIGATOR_URL:'https://yandex.ru/maps/-/TEST',BOOKING_LATE_CANCEL_MINUTES:20},f.user);f.sms.promo({name:'Анна',phone:'+79030000000',consent:true},'127.0.0.1',now);await f.sms.tick(f.service,now);assert.equal(f.sends,2);for(const m of f.messages){assert.doesNotMatch(m.text,/https?:\/\//i);assert.match(m.text,/yandex.ru\/maps\/-\/TEST/);assert.match(m.text,/СТАРТ/);}assert.match(f.messages[0].text,/более 20 мин — бронь отменяется/);assert.match(f.messages[0].text,/\+79991112233/);assert.match(f.messages[1].text,/АЭЛИТА/);}finally{f.close();}});
test('13. Deleted / issued / completed bookings never send',async()=>{for(const state of ['deleted','issued','completed']){const f=fixture('12:30');try{f.admin.db.prepare('UPDATE inquiries SET status=? WHERE id=?').run(state,f.id);await f.sms.tick(f.service,now);assert.equal(f.sends,0);}finally{f.close();}}});
test('13b. Physically removed booking cancels job',async()=>{const f=fixture('12:30');try{f.admin.db.prepare('DELETE FROM inquiry_events WHERE inquiry_id=?').run(f.id);f.admin.db.prepare('DELETE FROM inquiries WHERE id=?').run(f.id);await f.sms.tick(f.service,now);assert.equal(f.sends,0);assert.equal(f.sms.jobs(f.id)[0].status,'cancelled');}finally{f.close();}});
test('15. Move within the hour sends immediately',async()=>{const f=fixture();try{f.move('12:30');await f.sms.tick(f.service,now);assert.equal(f.sends,1);}finally{f.close();}});
test('Unknown network outcome is never blindly retried',async()=>{const f=fixture('12:30');try{let n=0;const service={...f.service,send:async()=>{n++;return {ok:false,unknown:true,error:'Timeout'};}};await f.sms.tick(service,now);await f.sms.tick(service,now+60000);assert.equal(n,1);assert.equal(f.sms.jobs(f.id)[0].status,'unknown');}finally{f.close();}});
test('Interrupted sending becomes unknown after restart grace',async()=>{const f=fixture('12:30');try{f.admin.db.prepare("UPDATE sms_jobs SET status='sending',claimed_at=?").run(now-180000);await f.sms.tick(f.service,now);assert.equal(f.sends,0);assert.equal(f.sms.jobs(f.id)[0].status,'unknown');}finally{f.close();}});
test('Discount deduplication, shared client, optional marketing, disabled gate',async()=>{const f=fixture();try{const b={name:'Анна',phone:'+7 903 000-00-00',consent:true,marketing:false};f.sms.promo(b,'a',now);f.sms.promo({...b,phone:'89030000000'},'a',now);assert.equal(f.admin.db.prepare('SELECT count(*) n FROM clients').get().n,1);assert.equal(f.admin.db.prepare('SELECT count(*) n FROM discounts').get().n,1);await f.sms.tick(f.service,now);assert.equal(f.sends,1);assert.equal(f.sms.clients()[0].marketing_consent,0);f.sms.save({...f.sms.settings(),enabled:false},f.user);assert.throws(()=>f.sms.promo(b,'b',now));}finally{f.close();}});
test('Daily quota stops sends and expired reminder never catches up',async()=>{const f=fixture('12:30');try{f.sms.save({...f.sms.settings(),dailyLimit:1},f.user);f.sms.promo({name:'Анна',phone:'79030000000',consent:true},'a',now);await f.sms.tick(f.service,now);assert.equal(f.sends,1);await f.sms.tick(f.service,now+86400000);assert.equal(f.sends,2);}finally{f.close();}});
test('Settings role/revision validation and normalized phones',()=>{const f=fixture();try{assert.equal(phone('8 (903) 000-00-00'),'79030000000');assert.throws(()=>f.sms.save(f.sms.settings(),{id:2,role:'staff'}));assert.throws(()=>f.sms.save({...f.sms.settings(),YANDEX_NAVIGATOR_URL:'https://evil.test'},f.user));assert.throws(()=>f.sms.save({...f.sms.settings(),revision:-1},f.user));}finally{f.close();}});
test('SMS service redacts failures and uses Authorization without credentials in URL',async()=>{const svc=new SmsService({SMSAERO_EMAIL:'email',SMSAERO_API_KEY:'secret'},async(url,opts)=>{assert.equal(url,'https://gate.smsaero.ru/v2/sms/send');assert.match(opts.headers.Authorization,/^Basic /);throw Error('secret');});const r=await svc.send('79030000000','СТАРТ: тест','СТАРТ');assert.equal(r.unknown,true);assert.ok(!r.error.includes('secret'));});
