import {withSiteChrome} from './site-shell.mjs';
import {readFileSync} from 'node:fs';
import {analyticsTag} from './analytics.mjs';
const section=readFileSync(new URL('./storage-section.html',import.meta.url),'utf8');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderStorage(d){
 const body=section.replace('<h2 id="storage-title">','<h1 id="storage-title">').replace('САПов</h2>','САПов</h1>').replace('loading="lazy"','fetchpriority="high"').replaceAll('https://t.me/Alexandrem2','https://t.me/'+esc(d.telegram));
 return withSiteChrome(`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Хранение личных САПов в Ореховой бухте — от 10 000 ₽ за сезон | СТАРТ</title><meta name="description" content="Хранение своего САПа на станции СТАРТ в Болтино: 10 000 или 15 000 рублей за сезон. Душ, туалет, раздевалка, камера хранения и подкачка включены."><meta name="robots" content="${d.seo.indexable?'index,follow':'noindex,nofollow'}"><link rel="canonical" href="https://spotsup.ru/storage/"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/services.css"><link rel="stylesheet" href="/storage.css"><style>.personal-storage{margin-top:24px;padding-top:0;border:0}.storage-visual{max-width:100%}#storage-title{font-size:clamp(32px,5vw,60px)}.section-heading p{line-height:1.6}</style>${analyticsTag()}<meta property="og:title" content="Хранение личных САПов — СТАРТ"><meta property="og:url" content="https://spotsup.ru/storage/"><meta property="og:image" content="https://spotsup.ru/assets/personal-sup-storage-w1600.webp"></head><body><header><a class="brand" href="/">СТАРТ<span>Ореховая бухта</span></a><a href="tel:${esc(d.phone.replace(/[^+\d]/g,''))}">${esc(d.phone)}</a></header><main><nav aria-label="Хлебные крошки"><a href="/">Главная</a> / Хранение личных САПов</nav>${body}</main><footer><a href="/">Вернуться на главную</a><p>${esc(d.texts.address.value)}</p></footer></body></html>`,d);
}
