import {readFileSync} from 'node:fs';
import {randomBytes,scryptSync,createHash} from 'node:crypto';

const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
const staff=u=>{if(!['admin','staff','waiter'].includes(u?.role))fail('Войдите в админку.',401);};
const owner=u=>{staff(u);if(u.role!=='admin')fail('Доступно только администратору.',403);};
const integer=(n,max=100000000)=>{if(!Number.isSafeInteger(n)||n<0||n>max)fail('Проверьте числовое значение.');return n;};
const reason=s=>{if(typeof s!=='string'||!s.trim()||s.length>300)fail('Укажите причину изменения.');return s.trim();};
export const workDay=(now=Date.now())=>new Date(now+10800000).toISOString().slice(0,10);
const bounds=day=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(day||''))fail('Проверьте дату.');const start=Date.parse(day+'T00:00:00+03:00');if(!Number.isFinite(start)||workDay(start)!==day)fail('Проверьте дату.');return [start,start+86400000];};
const roundRatio=(n,d)=>Number((n+BigInt(d)/2n)/BigInt(d));
export function basePayCents(settings,workedMs){
 integer(workedMs,Number.MAX_SAFE_INTEGER);
 if(settings.pay_mode==='prorated'){
  const minutes=integer(settings.full_shift_minutes,1440);if(!minutes)fail('Укажите продолжительность полного выхода.');
  return roundRatio(BigInt(settings.fixed_cents)*BigInt(workedMs),minutes*60000);
 }
 return settings.pay_mode==='hourly'?roundRatio(BigInt(settings.hourly_cents)*BigInt(workedMs),3600000):settings.fixed_cents;
}
export function distribute(pool,rows,rule){
 const weights=rows.map(r=>rule==='hours'?r.worked_ms:1),total=weights.reduce((n,x)=>n+BigInt(x),0n);
 if(!total)return rows.map(()=>0);
 const parts=weights.map((w,i)=>({i,amount:Number(BigInt(pool)*BigInt(w)/total),rest:BigInt(pool)*BigInt(w)%total,id:rows[i].user_id}));
 let left=pool-parts.reduce((n,p)=>n+p.amount,0);
 for(const p of [...parts].sort((a,b)=>a.rest===b.rest?a.id-b.id:a.rest>b.rest?-1:1)){if(left-->0)p.amount++;}
 return parts.map(p=>p.amount);
}
export class WorkforceStore{
 constructor(admin,{env=process.env,request=fetch}={}){this.admin=admin;this.db=admin.db;this.env=env;this.request=request;this.busy=false;
  this.db.exec(readFileSync(new URL('./migrations/002-workforce.sql',import.meta.url),'utf8'));
  const column=(table,name,type)=>{if(!this.db.prepare('PRAGMA table_info('+table+')').all().some(c=>c.name===name))this.db.exec('ALTER TABLE '+table+' ADD COLUMN '+name+' '+type);};
  column('salary_settings','pay_mode',"TEXT NOT NULL DEFAULT 'fixed'");column('salary_settings','hourly_cents','INTEGER NOT NULL DEFAULT 0');column('salary_settings','distribution',"TEXT NOT NULL DEFAULT 'equal'");column('salary_settings','revision','INTEGER NOT NULL DEFAULT 0');column('salary_settings','full_shift_minutes','INTEGER NOT NULL DEFAULT 720');
  column('shifts','salary_settings_json','TEXT');column('shift_employees','worked_ms','INTEGER');column('shift_employees','calculation_json','TEXT');
  this.db.prepare("INSERT OR IGNORE INTO admin_config(key,value) VALUES('workforce_reports_from',?)").run(workDay());
 }
 tx(fn){this.db.exec('BEGIN IMMEDIATE');try{const r=fn();this.db.exec('COMMIT');return r;}catch(e){this.db.exec('ROLLBACK');throw e;}}
 audit(u,action,id,before,after,why,now){this.db.prepare('INSERT INTO financial_audit_log(actor,action,entity_id,before_json,after_json,reason,created_at) VALUES(?,?,?,?,?,?,?)').run(u.id,action,id,JSON.stringify(before),JSON.stringify(after),why,now);}
 settings(){return this.db.prepare('SELECT * FROM salary_settings WHERE id=1').get();}
 daySettings(day,now=Date.now(),save=false){let r=this.db.prepare('SELECT settings_json FROM work_day_settings WHERE day=?').get(day);if(!r&&save){this.db.prepare('INSERT OR IGNORE INTO work_day_settings VALUES(?,?,?)').run(day,JSON.stringify(this.settings()),now);r=this.db.prepare('SELECT settings_json FROM work_day_settings WHERE day=?').get(day);}return r?JSON.parse(r.settings_json):this.settings();}
 saveSettings(b,u,now=Date.now()){owner(u);return this.tx(()=>{const old=this.settings();if(b.revision!==old.revision)fail('Настройки изменились. Обновите страницу.',409);integer(b.fixedCents);integer(b.hourlyCents);integer(b.bonusPercent,100);const fullShiftMinutes=b.fullShiftMinutes===undefined?old.full_shift_minutes:integer(b.fullShiftMinutes,1440);if(!fullShiftMinutes)fail('Укажите продолжительность полного выхода.');if(!['fixed','hourly','prorated'].includes(b.payMode)||!['equal','hours'].includes(b.distribution))fail('Проверьте правила оплаты.');this.db.prepare('UPDATE salary_settings SET fixed_cents=?,hourly_cents=?,bonus_percent=?,pay_mode=?,distribution=?,full_shift_minutes=?,revision=revision+1 WHERE id=1').run(b.fixedCents,b.hourlyCents,b.bonusPercent,b.payMode,b.distribution,fullShiftMinutes);const after=this.settings();this.audit(u,'salary_settings',1,old,after,'Настройки для новых рабочих дней',now);return after;});}
 people(){return this.db.prepare("SELECT u.id,u.login,u.role,coalesce(p.display_name,u.login) name FROM admin_users u LEFT JOIN employee_profiles p ON p.user_id=u.id WHERE role IN ('admin','staff','waiter') ORDER BY u.id").all();}
 savePerson(b,u,now=Date.now()){
  owner(u);if(typeof b.name!=='string'||!b.name.trim()||b.name.length>80||/[\x00-\x1f]/.test(b.name))fail('Укажите имя сотрудника.');
  return this.tx(()=>{
   let id=b.id,old=id?this.people().find(x=>x.id===id):null;if(id&&!old)fail('Сотрудник не найден.',404);
   const role=b.role??old?.role;if(!['admin','staff','waiter'].includes(role))fail('Выберите роль сотрудника.');
   if(old){
    if(b.role!==undefined&&b.expectedRole!==old.role)fail('Права уже изменились. Обновите страницу.',409);
    if(old.role==='admin'&&role!=='admin'&&this.db.prepare("SELECT count(*) n FROM admin_users WHERE role='admin'").get().n<=1)fail('Нельзя убрать последнего администратора.',409);
    if(role!==old.role)this.db.prepare('UPDATE admin_users SET role=? WHERE id=?').run(role,id);
   }else{
    if(!/^[a-z][a-z0-9_-]{2,30}$/.test(b.login||'')||typeof b.password!=='string'||b.password.length<12||b.password.length>128)fail('Логин 3–31 латинских символов; пароль от 12 символов.');
    if(this.db.prepare('SELECT id FROM admin_users WHERE login=?').get(b.login))fail('Логин уже существует.',409);
    const salt=randomBytes(16).toString('hex'),pw=salt+':'+scryptSync(b.password,salt,64).toString('hex');id=Number(this.db.prepare('INSERT INTO admin_users(login,role,password) VALUES(?,?,?)').run(b.login,role,pw).lastInsertRowid);
   }
   this.db.prepare('INSERT INTO employee_profiles VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET display_name=excluded.display_name').run(id,b.name.trim());
   const after=this.people().find(p=>p.id===id);this.audit(u,old&&old.role!==role?'employee_role':'employee_profile',id,old,after,old?(old.role!==role?'Изменение прав сотрудника':'Имя сотрудника'):'Личный доступ сотрудника',now);return this.people();
  });
 }

 action(b,u,kind,now=Date.now()){staff(u);if(!/^[a-f0-9-]{36}$/.test(b.requestId||''))fail('Обновите страницу.');if(b.userId!==undefined&&b.userId!==u.id)fail('Можно управлять только своей сменой.',403);return this.tx(()=>{const prev=this.db.prepare('SELECT * FROM work_actions WHERE request_id=?').get(b.requestId);if(prev){if(prev.user_id!==u.id||prev.kind!==kind)fail('Операция уже использована.',409);return this.db.prepare('SELECT * FROM employee_work_sessions WHERE id=?').get(prev.session_id);}
   let row=this.db.prepare('SELECT * FROM employee_work_sessions WHERE user_id=? AND ended_at IS NULL').get(u.id);const before=row||null;
   if(kind==='start'){if(!row){if(this.admin.currentShift(workDay(now))?.closed_at)fail('Кассовая смена за сегодня уже закрыта.',409);this.daySettings(workDay(now),now,true);const id=Number(this.db.prepare('INSERT INTO employee_work_sessions(user_id,started_at) VALUES(?,?)').run(u.id,now).lastInsertRowid);row=this.db.prepare('SELECT * FROM employee_work_sessions WHERE id=?').get(id);this.audit(u,'work_start',row.id,null,row,'Я на смене',now);}}
   else{if(!Number.isSafeInteger(b.sessionId))fail('Обновите свою смену.');const target=this.db.prepare('SELECT * FROM employee_work_sessions WHERE id=? AND user_id=?').get(b.sessionId,u.id);if(!target)fail('Можно завершить только свою смену.',403);if(target.ended_at!==null)row=target;else{if(row?.id!==target.id||now<target.started_at)fail('Смена изменилась. Обновите страницу.',409);for(let t=bounds(workDay(target.started_at))[0];t<=now;t+=86400000)this.daySettings(workDay(t),now,true);this.db.prepare('UPDATE employee_work_sessions SET ended_at=?,revision=revision+1 WHERE id=?').run(now,target.id);row=this.db.prepare('SELECT * FROM employee_work_sessions WHERE id=?').get(target.id);this.audit(u,'work_end',row.id,before,row,'Ушёл со смены',now);}}
   this.db.prepare('INSERT INTO work_actions VALUES(?,?,?,?)').run(b.requestId,u.id,kind,row.id);return row;});}
 revenue(day,now){const s=this.admin.currentShift(day);if(s?.closed_at&&s.closed_at<=now)return {cents:s.total_revenue_cents,source:'Кассовая смена закрыта',final:true};const [start,end]=bounds(day),until=Math.min(now,end);const rental=this.db.prepare('SELECT coalesce(sum(amount),0) n FROM payments WHERE day=? AND created<=?').get(day,until).n;const hasCafe=this.db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='cafe_orders'").get();const cafe=hasCafe?this.db.prepare("SELECT coalesce(sum(total_cents),0) n FROM cafe_orders WHERE status='DELIVERED' AND updated>=? AND updated<?").get(start,until+1).n:0;return {cents:rental+cafe,rental_cents:rental,cafe_cents:cafe,source:'Оплаты проката и выданные заказы кафе; итог после сверки кассы',final:false};}
 calculate(day,now=Date.now(),overrideRevenue){const [start,end]=bounds(day),until=Math.min(now,end),shift=this.admin.currentShift(day),settings=shift?.salary_settings_json?JSON.parse(shift.salary_settings_json):this.daySettings(day),revenue=this.revenue(day,now);if(overrideRevenue!==undefined){revenue.cents=overrideRevenue;revenue.final=true;}const sessions=this.db.prepare('SELECT w.*,coalesce(p.display_name,u.login) name FROM employee_work_sessions w JOIN admin_users u ON u.id=w.user_id LEFT JOIN employee_profiles p ON p.user_id=u.id WHERE w.started_at<? AND (w.ended_at IS NULL OR w.ended_at>=?) ORDER BY w.started_at,w.id').all(until+1,start);const map=new Map();
  for(const original of sessions){const w={...original,ended_at:original.ended_at===null||original.ended_at>until?null:original.ended_at};const ms=Math.max(0,Math.min(w.ended_at??until,until)-Math.max(start,w.started_at));if(!ms&&w.ended_at!==null)continue;let e=map.get(w.user_id);if(!e){e={user_id:w.user_id,name:w.name,worked_ms:0,started_at:w.started_at,ended_at:w.ended_at,active:w.ended_at===null,sessions:[]};map.set(w.user_id,e);}e.worked_ms+=ms;e.active ||= w.ended_at===null;e.ended_at=e.active?null:Math.max(e.ended_at||0,w.ended_at||0);e.sessions.push(w);}
  // Existing cash rosters are retained for older manually opened shifts.
  if(shift&&!shift.salary_settings_json)for(const p of this.db.prepare('SELECT e.*,coalesce(p.display_name,u.login) name FROM shift_employees e JOIN admin_users u ON u.id=e.user_id LEFT JOIN employee_profiles p ON p.user_id=u.id WHERE shift_id=?').all(shift.id))if(!map.has(p.user_id)&&p.calculation_json===null)map.set(p.user_id,{user_id:p.user_id,name:p.name,worked_ms:0,started_at:null,ended_at:null,active:false,sessions:[],legacy:true});
  const rows=[...map.values()].sort((a,b)=>a.user_id-b.user_id),pool=Number(BigInt(Math.max(0,revenue.cents))*BigInt(settings.bonus_percent)/100n),bonuses=distribute(pool,rows,settings.distribution);rows.forEach((r,i)=>{r.fixed_cents=basePayCents(settings,r.worked_ms);r.bonus_cents=bonuses[i];r.salary_cents=r.fixed_cents+r.bonus_cents;});
  if(shift?.closed_at&&shift.closed_at<=now&&overrideRevenue===undefined){const fixed=this.db.prepare('SELECT * FROM shift_employees WHERE shift_id=?').all(shift.id);return {day,asOf:now,settings,revenue,bonus_pool_cents:shift.bonus_pool_cents,employees:fixed.map(e=>({...rows.find(x=>x.user_id===e.user_id),...(e.calculation_json?JSON.parse(e.calculation_json).employee:{}),...e,calculation:e.calculation_json?JSON.parse(e.calculation_json):null})),final:true};}
  return {day,asOf:now,settings,revenue,bonus_pool_cents:pool,employees:rows,final:false};}
 snapshot(u,day=workDay(),now=Date.now()){staff(u);bounds(day);const calc=this.calculate(day,now),activeSessions=this.db.prepare('SELECT * FROM employee_work_sessions WHERE ended_at IS NULL').all(),today=day===workDay(now)?calc:this.calculate(workDay(now),now);return {user:u,day,own:activeSessions.find(w=>w.user_id===u.id)||null,active:activeSessions.map(w=>{const p=this.people().find(p=>p.id===w.user_id),e=today.employees.find(e=>e.user_id===w.user_id);return {id:w.id,user_id:w.user_id,name:p?.name||'',started_at:w.started_at,worked_ms:now-w.started_at,salary_cents:e?.salary_cents??0};}),calculation:u.role==='admin'?calc:{...calc,employees:calc.employees.filter(e=>e.user_id===u.id)},canEdit:u.role==='admin'};}
 correct(b,u,now=Date.now()){owner(u);const why=reason(b.reason);integer(b.id);integer(b.revision);integer(b.startedAt,now);if(b.endedAt!==null)integer(b.endedAt,now);if(b.endedAt!==null&&b.endedAt<b.startedAt)fail('Окончание раньше начала.');return this.tx(()=>{const old=this.db.prepare('SELECT * FROM employee_work_sessions WHERE id=?').get(b.id);if(!old)fail('Смена не найдена.',404);if(workDay(old.started_at)!==workDay(b.startedAt))fail('Перенос между кассовыми днями требует отдельной сверки начислений.',409);if(old.revision!==b.revision)fail('Время уже изменено. Обновите историю.',409);if(this.db.prepare('SELECT id FROM employee_work_sessions WHERE user_id=? AND id<>? AND started_at<? AND coalesce(ended_at,9223372036854775807)>?').get(old.user_id,old.id,b.endedAt??Number.MAX_SAFE_INTEGER,b.startedAt))fail('Пересечение со второй сменой сотрудника.',409);const first=Math.min(old.started_at,b.startedAt),last=Math.max(old.ended_at??now,b.endedAt??now);if(last-first>366*86400000)fail('Слишком большой интервал корректировки.');this.db.prepare('UPDATE employee_work_sessions SET started_at=?,ended_at=?,revision=revision+1 WHERE id=?').run(b.startedAt,b.endedAt,b.id);for(let t=bounds(workDay(first))[0];t<=last;t+=86400000){const d=workDay(t);this.daySettings(d,now,true);const s=this.admin.currentShift(d);if(s?.closed_at){if(b.endedAt===null)fail('Нельзя открыть личную смену в закрытом кассовом дне.',409);const beforePay=this.admin.shiftDetails(s.id);this.freeze(s,this.calculate(d,now,s.total_revenue_cents),u,now);this.audit(u,'salary_recalculate',s.id,beforePay,this.admin.shiftDetails(s.id),why,now);}}const row=this.db.prepare('SELECT * FROM employee_work_sessions WHERE id=?').get(b.id);this.audit(u,'work_correct',b.id,old,row,why,now);return row;});}
 freeze(shift,calc,u,now){const all=this.db.prepare('SELECT * FROM shift_employees WHERE shift_id=?').all(shift.id);for(const old of all)if(!calc.employees.some(e=>e.user_id===old.user_id))fail('Сотрудник исчез из расчёта. Требуется сверка.',409);for(const e of calc.employees){const paid=this.db.prepare('SELECT coalesce(sum(amount_cents),0) n FROM payroll_payments WHERE shift_id=? AND user_id=?').get(shift.id,e.user_id).n;if(paid>e.salary_cents)fail('Новый расчёт меньше уже выплаченного. Сначала необходима сверка с сотрудником.',409);this.db.prepare('INSERT INTO shift_employees(shift_id,user_id,fixed_cents,bonus_cents,salary_cents,worked_ms,calculation_json) VALUES(?,?,?,?,?,?,?) ON CONFLICT(shift_id,user_id) DO UPDATE SET fixed_cents=excluded.fixed_cents,bonus_cents=excluded.bonus_cents,salary_cents=excluded.salary_cents,worked_ms=excluded.worked_ms,calculation_json=excluded.calculation_json').run(shift.id,e.user_id,e.fixed_cents,e.bonus_cents,e.salary_cents,e.worked_ms,JSON.stringify({settings:calc.settings,revenue_cents:calc.revenue.cents,pool_cents:calc.bonus_pool_cents,people:calc.employees.length,total_worked_ms:calc.employees.reduce((n,x)=>n+x.worked_ms,0),employee:e,calculated_at:now}));}this.db.prepare('UPDATE shifts SET salary_settings_json=?,bonus_pool_cents=? WHERE id=?').run(JSON.stringify(calc.settings),calc.bonus_pool_cents,shift.id);}
 preview(b,u,now=Date.now()){staff(u);integer(b.shiftId);integer(b.cashEndCents);integer(b.cashlessCents);const shift=this.db.prepare('SELECT * FROM shifts WHERE id=?').get(b.shiftId);if(!shift||shift.closed_at)fail('Смена закрыта или не найдена.',409);const withdrawals=this.db.prepare("SELECT coalesce(sum(amount_cents),0) n FROM cash_movements WHERE shift_id=? AND type='DIRECTOR_WITHDRAWAL' AND voided_at IS NULL").get(shift.id).n,cash=b.cashEndCents-shift.cash_start_cents+withdrawals;if(cash<0)fail('Отрицательная наличная выручка. Проверьте суммы.');const calculation=this.calculate(shift.day,now,cash+b.cashlessCents),previewHash=createHash('sha256').update(JSON.stringify({shift,withdrawals,cashEnd:b.cashEndCents,cashless:b.cashlessCents,settings:calculation.settings,employees:calculation.employees})).digest('hex');return {shift,withdrawals,cash,cashless:b.cashlessCents,cashEnd:b.cashEndCents,calculation,previewHash};}
 closeCashShift(b,u,now=Date.now()){staff(u);integer(b.shiftId);integer(b.cashEndCents);integer(b.cashlessCents);return this.tx(()=>{const s=this.db.prepare('SELECT * FROM shifts WHERE id=?').get(b.shiftId);if(!s||s.closed_at)fail('Смена уже закрыта.',409);const w=this.db.prepare("SELECT coalesce(sum(amount_cents),0) n FROM cash_movements WHERE shift_id=? AND type='DIRECTOR_WITHDRAWAL' AND voided_at IS NULL").get(s.id).n,cash=b.cashEndCents-s.cash_start_cents+w,total=cash+b.cashlessCents;if(cash<0)fail('Наличная выручка отрицательная. Проверьте кассу и изъятия.');integer(total);this.daySettings(s.day,now,true);const calc=this.calculate(s.day,now,total);if(b.previewHash&&b.previewHash!==this.preview(b,u,now).previewHash)fail('Данные изменились после проверки. Посмотрите обновлённый итог.',409);if(calc.employees.some(e=>e.active))fail('Сначала сотрудники должны нажать «Ушёл со смены».',409);if(!calc.employees.length)fail('Нет сотрудников для расчёта зарплаты.');if(calc.settings.distribution==='hours'&&calc.employees.some(e=>!e.worked_ms))fail('Для распределения по времени заполните время всех сотрудников.');this.freeze(s,calc,u,now);this.db.prepare('UPDATE shifts SET closed_at=?,closed_by=?,cash_end_cents=?,cashless_cents=?,cash_revenue_cents=?,total_revenue_cents=? WHERE id=?').run(now,u.id,b.cashEndCents,b.cashlessCents,cash,total,s.id);const result=this.admin.shiftDetails(s.id);this.audit(u,'cash_shift_close',s.id,s,result,'Закрытие и окончательный расчёт',now);this.db.prepare('INSERT OR IGNORE INTO shift_report_jobs(shift_id,body) VALUES(?,?)').run(s.id,this.admin.shiftTelegram(result)+'\n\n'+this.reportText({...calc,final:true}));return result;});}
 pay(b,u,now=Date.now()){owner(u);integer(b.shiftId);integer(b.userId);integer(b.amountCents);if(!b.amountCents)fail('Укажите сумму.');return this.tx(()=>{const s=this.db.prepare('SELECT * FROM shifts WHERE id=?').get(b.shiftId);if(!s?.closed_at)fail('Выплата доступна после закрытия кассовой смены.',409);const e=this.db.prepare('SELECT * FROM shift_employees WHERE shift_id=? AND user_id=?').get(b.shiftId,b.userId);if(!e)fail('Начисление не найдено.',404);const paid=this.db.prepare('SELECT coalesce(sum(amount_cents),0) n FROM payroll_payments WHERE shift_id=? AND user_id=?').get(b.shiftId,b.userId).n;if(paid+b.amountCents>e.salary_cents)fail('Сумма выплаты больше остатка начисления.',409);this.db.prepare('INSERT INTO payroll_payments(shift_id,user_id,amount_cents,paid_at,paid_by) VALUES(?,?,?,?,?)').run(b.shiftId,b.userId,b.amountCents,now,u.id);this.audit(u,'payroll_payment',b.shiftId,{paid},{paid:paid+b.amountCents,userId:b.userId},'Отметка выплаты',now);return this.admin.payroll(u);});}
 reportText(calc){const rub=n=>(n/100).toLocaleString('ru-RU')+' ₽',clock=t=>t===null?'не указано':new Date(t).toLocaleTimeString('ru-RU',{timeZone:'Europe/Moscow',hour:'2-digit',minute:'2-digit'});const shift=this.admin.currentShift(calc.day),rows=calc.employees.map(e=>{const paid=shift?this.db.prepare('SELECT coalesce(sum(amount_cents),0) n FROM payroll_payments WHERE shift_id=? AND user_id=? AND paid_at<=?').get(shift.id,e.user_id,calc.asOf).n:0;return {...e,due:Math.max(0,e.salary_cents-paid)};});return [`СТАРТ — ${calc.final?'итоги смены':'отчёт на 22:00'}`,calc.day,`Выручка: ${rub(calc.revenue.cents)}${calc.final?'':' (предварительно)'}`,calc.settings.pay_mode==='prorated'?`База: ${rub(calc.settings.fixed_cents)} за ${calc.settings.full_shift_minutes/60} ч, пропорционально времени`:'',`Бонусный фонд ${calc.settings.bonus_percent}%: ${rub(calc.bonus_pool_cents)}`,`Распределение: ${calc.settings.distribution==='hours'?'по отработанному времени':'поровну'}`,...rows.flatMap(e=>['',e.name||String(e.user_id),`${clock(e.started_at)} — ${e.active?'ещё на смене':clock(e.ended_at)} · ${(e.worked_ms/3600000).toFixed(2)} ч`,`База: ${rub(e.fixed_cents)}; бонус: ${rub(e.bonus_cents)}; итого: ${rub(e.salary_cents)}`]),'',calc.final?'Кому сколько перевести':'Кому сколько перевести — предварительно',...rows.map(e=>`${e.name||e.user_id} — ${rub(e.due)}`),`Итого к выплате: ${rub(rows.reduce((n,e)=>n+e.due,0))}`,calc.final?'':'Окончательная сумма фиксируется после закрытия кассовой смены.'].filter(Boolean).join('\n');}
 telegramConfig(){const s=this.db.prepare('SELECT * FROM telegram_settings WHERE id=1').get();return {enabled:!!s.enabled,token:this.env.TELEGRAM_BOT_TOKEN,chat:s.owner_chat_id||this.env.TELEGRAM_OWNER_CHAT_ID||this.env.TELEGRAM_CHAT_ID,origin:this.env.SITE_ORIGIN||'https://spotsup.ru'};}
 async tick(now=Date.now()){if(this.busy)return;this.busy=true;try{const from=this.db.prepare("SELECT value FROM admin_config WHERE key='workforce_reports_from'").get().value,today=workDay(now);this.db.prepare("UPDATE daily_work_reports SET status='unknown',last_error='Отправка прервалась; автоматический повтор отключён.' WHERE status='sending' AND claimed_at<?").run(now-60000);this.db.prepare("UPDATE shift_report_jobs SET status='unknown',last_error='Отправка прервалась; автоматический повтор отключён.' WHERE status='sending' AND claimed_at<?").run(now-60000);
   const dates=new Set([today]);for(const w of this.db.prepare('SELECT started_at,ended_at FROM employee_work_sessions WHERE coalesce(ended_at,?)>=?').all(now,bounds(from)[0]))for(let t=bounds(workDay(Math.max(w.started_at,bounds(from)[0])))[0];t<=Math.min(w.ended_at??now,now);t+=86400000)dates.add(workDay(t));
   for(const d of [...dates].sort()){const cutoff=bounds(d)[0]+22*3600000;if(d<from||now<cutoff||this.db.prepare('SELECT day FROM daily_work_reports WHERE day=?').get(d))continue;this.tx(()=>{const snapshot=this.calculate(d,cutoff);this.db.prepare('INSERT OR IGNORE INTO daily_work_reports(day,created_at,snapshot_json) VALUES(?,?,?)').run(d,now,JSON.stringify(snapshot));});}
   const cfg=this.telegramConfig();if(!cfg.enabled||!cfg.token||!/^[-]?\d+$/.test(cfg.chat||''))return;
   for(const kind of ['daily','closed']){const table=kind==='daily'?'daily_work_reports':'shift_report_jobs',key=kind==='daily'?'day':'shift_id';for(const job of this.db.prepare(`SELECT * FROM ${table} WHERE status='queued' LIMIT 5`).all()){if(!this.db.prepare(`UPDATE ${table} SET status='sending',claimed_at=? WHERE ${key}=? AND status='queued'`).run(now,job[key]).changes)continue;const text=kind==='daily'?this.reportText(JSON.parse(job.snapshot_json)):job.body;try{const chunks=[];for(const line of text.split('\n')){if(!chunks.length||chunks[chunks.length-1].length+line.length+1>3500)chunks.push(line);else chunks[chunks.length-1]+='\n'+line;}let r,body;for(const part of chunks){r=await this.request(`https://api.telegram.org/bot${cfg.token}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:cfg.chat,text:part,protect_content:true,link_preview_options:{is_disabled:true},reply_markup:{inline_keyboard:[[{text:'Смены и зарплата',url:cfg.origin+'/admin/workforce/'}]]}}),signal:AbortSignal.timeout(10000)});body=await r.json();if(!r.ok||body.ok!==true)break;}this.db.prepare(`UPDATE ${table} SET status=?,last_error=? WHERE ${key}=?`).run(r.ok&&body.ok===true?'sent':body.ok===false?'error':'unknown',r.ok&&body.ok===true?'':'Telegram не подтвердил доставку. Автоматического повтора нет.',job[key]);if(kind==='daily'&&r.ok&&body.ok===true)this.db.prepare('UPDATE daily_work_reports SET sent_at=? WHERE day=?').run(now,job.day);}catch{this.db.prepare(`UPDATE ${table} SET status='unknown',last_error='Результат отправки неизвестен. Автоматического повтора нет.' WHERE ${key}=?`).run(job[key]);}}}
  }finally{this.busy=false;}}
 history(u,day,now=Date.now()){owner(u);const calc=this.calculate(day,now);return {...calc,audit:this.db.prepare('SELECT a.*,u.login FROM financial_audit_log a JOIN admin_users u ON u.id=a.actor ORDER BY a.id DESC LIMIT 100').all(),report:this.db.prepare('SELECT day,created_at,status,sent_at,last_error FROM daily_work_reports WHERE day=?').get(day)||null};}
}
export function workforceHandler(store,admin,origin){return async(req,res,url)=>{if(!url.pathname.startsWith('/api/admin/workforce/'))return false;const reply=(status,b)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(b));return true;};try{if(!store||!admin)fail('Сервис не настроен.',503);const token=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('__Host-start_session='))?.slice(21),u=admin.user(token);staff(u);const p=url.pathname.slice('/api/admin/workforce/'.length);if(req.method==='GET'){if(p==='current')return reply(200,store.snapshot(u));if(p==='history')return reply(200,store.history(u,url.searchParams.get('day')||workDay()));if(p==='settings'){owner(u);return reply(200,{settings:store.settings(),people:store.people(),telegram:admin.telegramSettings(u)});}return reply(404,{error:'Не найдено.'});}if(req.method!=='POST')return reply(405,{error:'Метод не поддерживается.'});if(req.headers.origin!==origin||!req.headers['content-type']?.startsWith('application/json'))fail('Недопустимый источник запроса.',403);let size=0,chunks=[];for await(const c of req){size+=c.length;if(size>4096)fail('Запрос слишком большой.',413);chunks.push(c);}let b;try{b=JSON.parse(Buffer.concat(chunks).toString());}catch{fail('Неверный запрос.');}if(!b||typeof b!=='object'||Array.isArray(b))fail('Неверный запрос.');if(p==='start'||p==='end')return reply(200,store.action(b,u,p));if(p==='preview')return reply(200,store.preview(b,u));if(p==='correct')return reply(200,store.correct(b,u));if(p==='settings')return reply(200,store.saveSettings(b,u));if(p==='people')return reply(200,{items:store.savePerson(b,u)});return reply(404,{error:'Не найдено.'});}catch(e){return reply(e.status||500,{error:e.status?e.message:'Не удалось выполнить действие со сменой.'});}};}
